/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class AttributeUpdateMessage extends DeviceMessage {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected AttributeUpdateMessage(long cPtr, boolean cMemoryOwn) {
    super(stiJNI.AttributeUpdateMessage_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AttributeUpdateMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        stiJNI.delete_AttributeUpdateMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.AttributeUpdateMessage_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.AttributeUpdateMessage_change_ownership(this, swigCPtr, true);
  }

  public AttributeUpdateMessage(DeviceTrace trace) {
    this(stiJNI.new_AttributeUpdateMessage__SWIG_0(DeviceTrace.getCPtr(trace), trace), true);
    stiJNI.AttributeUpdateMessage_director_connect(this, swigCPtr, true, true);
  }

  public AttributeUpdateMessage(DeviceTrace trace, String key, String value) {
    this(stiJNI.new_AttributeUpdateMessage__SWIG_1(DeviceTrace.getCPtr(trace), trace, key, value), true);
    stiJNI.AttributeUpdateMessage_director_connect(this, swigCPtr, true, true);
  }

  public static DeviceMessageType getMessageClassType() {
    return DeviceMessageType.swigToEnum(stiJNI.AttributeUpdateMessage_getMessageClassType());
  }

  public boolean appendMessage(AttributeUpdateMessage mess) {
    return stiJNI.AttributeUpdateMessage_appendMessage(swigCPtr, this, AttributeUpdateMessage.getCPtr(mess), mess);
  }

  public boolean groupable() {
    return stiJNI.AttributeUpdateMessage_groupable(swigCPtr, this);
  }

  public AttributeUpdateMessage get() {
    return new AttributeUpdateMessage(stiJNI.AttributeUpdateMessage_get(swigCPtr, this), true);
  }

  public void setAttributes(StringMap value) {
    stiJNI.AttributeUpdateMessage_attributes_set(swigCPtr, this, StringMap.getCPtr(value), value);
  }

  public StringMap getAttributes() {
    long cPtr = stiJNI.AttributeUpdateMessage_attributes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringMap(cPtr, false);
  }

  public String toString() {
    return stiJNI.AttributeUpdateMessage_toString(swigCPtr, this);
  }

}
