/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class ChannelManager {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ChannelManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_ChannelManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.ChannelManager_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.ChannelManager_change_ownership(this, swigCPtr, true);
  }

  public void getChannels(ChannelVector channels) {
    stiJNI.ChannelManager_getChannels(swigCPtr, this, ChannelVector.getCPtr(channels), channels);
  }

  public boolean getChannel(short channelNumber, Channel channel) {
    return stiJNI.ChannelManager_getChannel(swigCPtr, this, channelNumber, Channel.getCPtr(channel), channel);
  }

  public boolean writeChannel(short channel, MixedValue value) {
    return stiJNI.ChannelManager_writeChannel(swigCPtr, this, channel, MixedValue.getCPtr(value), value);
  }

  public boolean readChannel(short channel, MixedValue value, MixedValue data) {
    return stiJNI.ChannelManager_readChannel(swigCPtr, this, channel, MixedValue.getCPtr(value), value, MixedValue.getCPtr(data), data);
  }

  public ChannelManager() {
    this(stiJNI.new_ChannelManager(), true);
    stiJNI.ChannelManager_director_connect(this, swigCPtr, true, true);
  }

}
