/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class Channel {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Channel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Channel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_Channel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.Channel_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.Channel_change_ownership(this, swigCPtr, true);
  }

  public short getChannelNumber() {
    return stiJNI.Channel_getChannelNumber(swigCPtr, this);
  }

  public ChannelType getType() {
    return ChannelType.swigToEnum(stiJNI.Channel_getType(swigCPtr, this));
  }

  public MixedValueType getInputType() {
    return MixedValueType.swigToEnum(stiJNI.Channel_getInputType(swigCPtr, this));
  }

  public MixedValueType getOutputType() {
    return MixedValueType.swigToEnum(stiJNI.Channel_getOutputType(swigCPtr, this));
  }

  public void setChannelName(String name) {
    stiJNI.Channel_setChannelName(swigCPtr, this, name);
  }

  public String getChannelName() {
    return stiJNI.Channel_getChannelName(swigCPtr, this);
  }

  public void saveLastValue(MixedValue value) {
    stiJNI.Channel_saveLastValue(swigCPtr, this, MixedValue.getCPtr(value), value);
  }

  public MixedValue getLastValue() {
    return new MixedValue(stiJNI.Channel_getLastValue(swigCPtr, this), true);
  }

  public MixedValue getMetaData() {
    return new MixedValue(stiJNI.Channel_getMetaData__SWIG_0(swigCPtr, this), false);
  }

  public MixedValue getMetaData(String key) {
    return new MixedValue(stiJNI.Channel_getMetaData__SWIG_1(swigCPtr, this, key), true);
  }

  public Channel() {
    this(stiJNI.new_Channel(), true);
    stiJNI.Channel_director_connect(this, swigCPtr, true, true);
  }

}
