/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class ChannelVector extends java.util.AbstractList<Channel> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChannelVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_ChannelVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChannelVector(Channel[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Channel element : initialElements) {
      add(element);
    }
  }

  public ChannelVector(Iterable<Channel> initialElements) {
    this();
    for (Channel element : initialElements) {
      add(element);
    }
  }

  public Channel get(int index) {
    return doGet(index);
  }

  public Channel set(int index, Channel e) {
    return doSet(index, e);
  }

  public boolean add(Channel e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Channel e) {
    modCount++;
    doAdd(index, e);
  }

  public Channel remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public ChannelVector() {
    this(stiJNI.new_ChannelVector__SWIG_0(), true);
  }

  public ChannelVector(ChannelVector other) {
    this(stiJNI.new_ChannelVector__SWIG_1(ChannelVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return stiJNI.ChannelVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    stiJNI.ChannelVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return stiJNI.ChannelVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.ChannelVector_clear(swigCPtr, this);
  }

  public ChannelVector(int count, Channel value) {
    this(stiJNI.new_ChannelVector__SWIG_2(count, Channel.getCPtr(value), value), true);
  }

  private int doSize() {
    return stiJNI.ChannelVector_doSize(swigCPtr, this);
  }

  private void doAdd(Channel x) {
    stiJNI.ChannelVector_doAdd__SWIG_0(swigCPtr, this, Channel.getCPtr(x), x);
  }

  private void doAdd(int index, Channel x) {
    stiJNI.ChannelVector_doAdd__SWIG_1(swigCPtr, this, index, Channel.getCPtr(x), x);
  }

  private Channel doRemove(int index) {
    long cPtr = stiJNI.ChannelVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Channel(cPtr, true);
  }

  private Channel doGet(int index) {
    long cPtr = stiJNI.ChannelVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Channel(cPtr, true);
  }

  private Channel doSet(int index, Channel val) {
    long cPtr = stiJNI.ChannelVector_doSet(swigCPtr, this, index, Channel.getCPtr(val), val);
    return (cPtr == 0) ? null : new Channel(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    stiJNI.ChannelVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
