/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class ChannelUpdateMessage extends DeviceMessage {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ChannelUpdateMessage(long cPtr, boolean cMemoryOwn) {
    super(stiJNI.ChannelUpdateMessage_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelUpdateMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        stiJNI.delete_ChannelUpdateMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.ChannelUpdateMessage_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.ChannelUpdateMessage_change_ownership(this, swigCPtr, true);
  }

  public ChannelUpdateMessage(DeviceTrace trace) {
    this(stiJNI.new_ChannelUpdateMessage__SWIG_0(DeviceTrace.getCPtr(trace), trace), true);
    stiJNI.ChannelUpdateMessage_director_connect(this, swigCPtr, true, true);
  }

  public ChannelUpdateMessage(DeviceTrace trace, short channel, MixedValue value) {
    this(stiJNI.new_ChannelUpdateMessage__SWIG_1(DeviceTrace.getCPtr(trace), trace, channel, MixedValue.getCPtr(value), value), true);
    stiJNI.ChannelUpdateMessage_director_connect(this, swigCPtr, true, true);
  }

  public ChannelUpdateMessage(DeviceTrace trace, short channel, String name) {
    this(stiJNI.new_ChannelUpdateMessage__SWIG_2(DeviceTrace.getCPtr(trace), trace, channel, name), true);
    stiJNI.ChannelUpdateMessage_director_connect(this, swigCPtr, true, true);
  }

  public static DeviceMessageType getMessageClassType() {
    return DeviceMessageType.swigToEnum(stiJNI.ChannelUpdateMessage_getMessageClassType());
  }

  public boolean appendMessage(ChannelUpdateMessage mess) {
    return stiJNI.ChannelUpdateMessage_appendMessage(swigCPtr, this, ChannelUpdateMessage.getCPtr(mess), mess);
  }

  public boolean groupable() {
    return stiJNI.ChannelUpdateMessage_groupable(swigCPtr, this);
  }

  public ChannelUpdateMessage get() {
    return new ChannelUpdateMessage(stiJNI.ChannelUpdateMessage_get(swigCPtr, this), true);
  }

  public void setChannelUpdateType(ChannelUpdateMessage.ChannelUpdateMessageType value) {
    stiJNI.ChannelUpdateMessage_channelUpdateType_set(swigCPtr, this, value.swigValue());
  }

  public ChannelUpdateMessage.ChannelUpdateMessageType getChannelUpdateType() {
    return ChannelUpdateMessage.ChannelUpdateMessageType.swigToEnum(stiJNI.ChannelUpdateMessage_channelUpdateType_get(swigCPtr, this));
  }

  public void setChannelValues(SWIGTYPE_p_std__mapT_short_STI__Utils__MixedValue_std__lessT_short_t_t value) {
    stiJNI.ChannelUpdateMessage_channelValues_set(swigCPtr, this, SWIGTYPE_p_std__mapT_short_STI__Utils__MixedValue_std__lessT_short_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__mapT_short_STI__Utils__MixedValue_std__lessT_short_t_t getChannelValues() {
    long cPtr = stiJNI.ChannelUpdateMessage_channelValues_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__mapT_short_STI__Utils__MixedValue_std__lessT_short_t_t(cPtr, false);
  }

  public void setChannelNumber(short value) {
    stiJNI.ChannelUpdateMessage_channelNumber_set(swigCPtr, this, value);
  }

  public short getChannelNumber() {
    return stiJNI.ChannelUpdateMessage_channelNumber_get(swigCPtr, this);
  }

  public void setChannelName(String value) {
    stiJNI.ChannelUpdateMessage_channelName_set(swigCPtr, this, value);
  }

  public String getChannelName() {
    return stiJNI.ChannelUpdateMessage_channelName_get(swigCPtr, this);
  }

  public final static class ChannelUpdateMessageType {
    public final static ChannelUpdateMessage.ChannelUpdateMessageType ChannelValue = new ChannelUpdateMessage.ChannelUpdateMessageType("ChannelValue");
    public final static ChannelUpdateMessage.ChannelUpdateMessageType ChannelName = new ChannelUpdateMessage.ChannelUpdateMessageType("ChannelName");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ChannelUpdateMessageType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ChannelUpdateMessageType.class + " with value " + swigValue);
    }

    private ChannelUpdateMessageType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ChannelUpdateMessageType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ChannelUpdateMessageType(String swigName, ChannelUpdateMessageType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ChannelUpdateMessageType[] swigValues = { ChannelValue, ChannelName };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
