/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class DeviceMessage {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected DeviceMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeviceMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_DeviceMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.DeviceMessage_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.DeviceMessage_change_ownership(this, swigCPtr, true);
  }

  public DeviceMessage() {
    this(stiJNI.new_DeviceMessage__SWIG_0(), true);
    stiJNI.DeviceMessage_director_connect(this, swigCPtr, true, true);
  }

  public DeviceMessage(DeviceID source, DeviceMessageType type) {
    this(stiJNI.new_DeviceMessage__SWIG_1(DeviceID.getCPtr(source), source, type.swigValue()), true);
    stiJNI.DeviceMessage_director_connect(this, swigCPtr, true, true);
  }

  public DeviceID sourceID() {
    return new DeviceID(stiJNI.DeviceMessage_sourceID(swigCPtr, this), false);
  }

  public DeviceMessageType getType() {
    return DeviceMessageType.swigToEnum(stiJNI.DeviceMessage_getType(swigCPtr, this));
  }

  public static DeviceMessageType getMessageClassType() {
    return DeviceMessageType.swigToEnum(stiJNI.DeviceMessage_getMessageClassType());
  }

  public static String typeToString(DeviceMessageType type) {
    return stiJNI.DeviceMessage_typeToString(type.swigValue());
  }

}
