/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class DeviceAttributeMap extends java.util.AbstractMap<DeviceID, StringMap> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DeviceAttributeMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeviceAttributeMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_DeviceAttributeMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof DeviceID)) {
      return false;
    }

    return containsImpl((DeviceID)key);
  }

  public StringMap get(java.lang.Object key) {
    if (!(key instanceof DeviceID)) {
      return null;
    }

    Iterator itr = find((DeviceID) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public StringMap put(DeviceID key, StringMap value) {
    Iterator itr = find((DeviceID) key);
    if (itr.isNot(end())) {
      StringMap oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public StringMap remove(java.lang.Object key) {
    if (!(key instanceof DeviceID)) {
      return null;
    }

    Iterator itr = find((DeviceID) key);
    if (itr.isNot(end())) {
      StringMap oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<DeviceID, StringMap>> entrySet() {
    java.util.Set<Entry<DeviceID, StringMap>> setToReturn =
        new java.util.HashSet<Entry<DeviceID, StringMap>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<DeviceID, StringMap>() {
        private Iterator iterator;

        private Entry<DeviceID, StringMap> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public DeviceID getKey() {
          return iterator.getKey();
        }

        public StringMap getValue() {
          return iterator.getValue();
        }

        public StringMap setValue(StringMap newValue) {
          StringMap oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public DeviceAttributeMap() {
    this(stiJNI.new_DeviceAttributeMap__SWIG_0(), true);
  }

  public DeviceAttributeMap(DeviceAttributeMap other) {
    this(stiJNI.new_DeviceAttributeMap__SWIG_1(DeviceAttributeMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stiJNI.delete_DeviceAttributeMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private DeviceAttributeMap.Iterator getNextUnchecked() {
      return new DeviceAttributeMap.Iterator(stiJNI.DeviceAttributeMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(DeviceAttributeMap.Iterator other) {
      return stiJNI.DeviceAttributeMap_Iterator_isNot(swigCPtr, this, DeviceAttributeMap.Iterator.getCPtr(other), other);
    }
  
    private DeviceID getKey() {
      return new DeviceID(stiJNI.DeviceAttributeMap_Iterator_getKey(swigCPtr, this), true);
    }
  
    private StringMap getValue() {
      return new StringMap(stiJNI.DeviceAttributeMap_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(StringMap newValue) {
      stiJNI.DeviceAttributeMap_Iterator_setValue(swigCPtr, this, StringMap.getCPtr(newValue), newValue);
    }
  
  }

  public boolean isEmpty() {
    return stiJNI.DeviceAttributeMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.DeviceAttributeMap_clear(swigCPtr, this);
  }

  private DeviceAttributeMap.Iterator find(DeviceID key) {
    return new DeviceAttributeMap.Iterator(stiJNI.DeviceAttributeMap_find(swigCPtr, this, DeviceID.getCPtr(key), key), true);
  }

  private DeviceAttributeMap.Iterator begin() {
    return new DeviceAttributeMap.Iterator(stiJNI.DeviceAttributeMap_begin(swigCPtr, this), true);
  }

  private DeviceAttributeMap.Iterator end() {
    return new DeviceAttributeMap.Iterator(stiJNI.DeviceAttributeMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return stiJNI.DeviceAttributeMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(DeviceID key) {
    return stiJNI.DeviceAttributeMap_containsImpl(swigCPtr, this, DeviceID.getCPtr(key), key);
  }

  private void putUnchecked(DeviceID key, StringMap value) {
    stiJNI.DeviceAttributeMap_putUnchecked(swigCPtr, this, DeviceID.getCPtr(key), key, StringMap.getCPtr(value), value);
  }

  private void removeUnchecked(DeviceAttributeMap.Iterator itr) {
    stiJNI.DeviceAttributeMap_removeUnchecked(swigCPtr, this, DeviceAttributeMap.Iterator.getCPtr(itr), itr);
  }

}
