/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class DeviceTrace {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DeviceTrace(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeviceTrace obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_DeviceTrace(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DeviceTrace() {
    this(stiJNI.new_DeviceTrace__SWIG_0(), true);
  }

  public DeviceTrace(DeviceID first) {
    this(stiJNI.new_DeviceTrace__SWIG_1(DeviceID.getCPtr(first), first), true);
  }

  public DeviceTrace(DeviceTrace src) {
    this(stiJNI.new_DeviceTrace__SWIG_2(DeviceTrace.getCPtr(src), src), true);
  }

  public void addID(DeviceID id) {
    stiJNI.DeviceTrace_addID(swigCPtr, this, DeviceID.getCPtr(id), id);
  }

  public boolean includesID(DeviceID id) {
    return stiJNI.DeviceTrace_includesID(swigCPtr, this, DeviceID.getCPtr(id), id);
  }

  public DeviceID first() {
    return new DeviceID(stiJNI.DeviceTrace_first(swigCPtr, this), true);
  }

  public DeviceID last() {
    return new DeviceID(stiJNI.DeviceTrace_last(swigCPtr, this), true);
  }

  public long size() {
    return stiJNI.DeviceTrace_size(swigCPtr, this);
  }

  public DeviceIDvector getIDs() {
    return new DeviceIDvector(stiJNI.DeviceTrace_getIDs(swigCPtr, this), false);
  }

  public String print(String separator) {
    return stiJNI.DeviceTrace_print__SWIG_0(swigCPtr, this, separator);
  }

  public String print() {
    return stiJNI.DeviceTrace_print__SWIG_1(swigCPtr, this);
  }

}
