/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class EngineParserDeviceMessage extends DeviceMessage {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected EngineParserDeviceMessage(long cPtr, boolean cMemoryOwn) {
    super(stiJNI.EngineParserDeviceMessage_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineParserDeviceMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        stiJNI.delete_EngineParserDeviceMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.EngineParserDeviceMessage_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.EngineParserDeviceMessage_change_ownership(this, swigCPtr, true);
  }

  public EngineParserDeviceMessage(DeviceTrace trace, ParseID parseID) {
    this(stiJNI.new_EngineParserDeviceMessage(DeviceTrace.getCPtr(trace), trace, ParseID.getCPtr(parseID), parseID), true);
    stiJNI.EngineParserDeviceMessage_director_connect(this, swigCPtr, true, true);
  }

  public void addParseMessage(EngineParsingMessage message) {
    stiJNI.EngineParserDeviceMessage_addParseMessage(swigCPtr, this, EngineParsingMessage.getCPtr(message), message);
  }

  public void setPid(ParseID value) {
    stiJNI.EngineParserDeviceMessage_pid_set(swigCPtr, this, ParseID.getCPtr(value), value);
  }

  public ParseID getPid() {
    long cPtr = stiJNI.EngineParserDeviceMessage_pid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ParseID(cPtr, false);
  }

  public void setMessages(EngineParserMessageVector value) {
    stiJNI.EngineParserDeviceMessage_messages_set(swigCPtr, this, EngineParserMessageVector.getCPtr(value), value);
  }

  public EngineParserMessageVector getMessages() {
    long cPtr = stiJNI.EngineParserDeviceMessage_messages_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineParserMessageVector(cPtr, false);
  }

}
