/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class EngineJobUpdateDeviceMessageListener {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected EngineJobUpdateDeviceMessageListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineJobUpdateDeviceMessageListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_EngineJobUpdateDeviceMessageListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.EngineJobUpdateDeviceMessageListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.EngineJobUpdateDeviceMessageListener_change_ownership(this, swigCPtr, true);
  }

  public EngineJobUpdateDeviceMessageListener() {
    this(stiJNI.new_EngineJobUpdateDeviceMessageListener(), true);
    stiJNI.EngineJobUpdateDeviceMessageListener_director_connect(this, swigCPtr, true, true);
  }

  public void handleMessage(EngineJobUpdateDeviceMessage mess) {
    stiJNI.EngineJobUpdateDeviceMessageListener_handleMessage(swigCPtr, this, EngineJobUpdateDeviceMessage.getCPtr(mess), mess);
  }

}
