/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class EngineJobUpdateDeviceMessage extends DeviceMessage {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected EngineJobUpdateDeviceMessage(long cPtr, boolean cMemoryOwn) {
    super(stiJNI.EngineJobUpdateDeviceMessage_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineJobUpdateDeviceMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        stiJNI.delete_EngineJobUpdateDeviceMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.EngineJobUpdateDeviceMessage_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.EngineJobUpdateDeviceMessage_change_ownership(this, swigCPtr, true);
  }

  public EngineJobUpdateDeviceMessage(DeviceTrace trace) {
    this(stiJNI.new_EngineJobUpdateDeviceMessage(DeviceTrace.getCPtr(trace), trace), true);
    stiJNI.EngineJobUpdateDeviceMessage_director_connect(this, swigCPtr, true, true);
  }

  public static DeviceMessageType getMessageClassType() {
    return DeviceMessageType.swigToEnum(stiJNI.EngineJobUpdateDeviceMessage_getMessageClassType());
  }

  public void toQueuedList(SWIGTYPE_p_std__shared_ptrT_STI__Engine__EventEngineJob_t job) {
    stiJNI.EngineJobUpdateDeviceMessage_toQueuedList(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_STI__Engine__EventEngineJob_t.getCPtr(job));
  }

  public void toRunningList(SWIGTYPE_p_std__shared_ptrT_STI__Engine__EventEngineJob_t job) {
    stiJNI.EngineJobUpdateDeviceMessage_toRunningList(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_STI__Engine__EventEngineJob_t.getCPtr(job));
  }

  public void toCompleteList(SWIGTYPE_p_std__shared_ptrT_STI__Engine__EventEngineJob_t job) {
    stiJNI.EngineJobUpdateDeviceMessage_toCompleteList(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_STI__Engine__EventEngineJob_t.getCPtr(job));
  }

  public void setTargetList(EngineJobUpdateTarget value) {
    stiJNI.EngineJobUpdateDeviceMessage_targetList_set(swigCPtr, this, value.swigValue());
  }

  public EngineJobUpdateTarget getTargetList() {
    return EngineJobUpdateTarget.swigToEnum(stiJNI.EngineJobUpdateDeviceMessage_targetList_get(swigCPtr, this));
  }

  public void setEngineJob(SWIGTYPE_p_std__shared_ptrT_STI__Engine__EventEngineJob_t value) {
    stiJNI.EngineJobUpdateDeviceMessage_engineJob_set(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_STI__Engine__EventEngineJob_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__shared_ptrT_STI__Engine__EventEngineJob_t getEngineJob() {
    long cPtr = stiJNI.EngineJobUpdateDeviceMessage_engineJob_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__shared_ptrT_STI__Engine__EventEngineJob_t(cPtr, false);
  }

  public static String jobTargetToString(EngineJobUpdateTarget target) {
    return stiJNI.EngineJobUpdateDeviceMessage_jobTargetToString(target.swigValue());
  }

}
