/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class EventEngineMessageListener {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected EventEngineMessageListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventEngineMessageListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_EventEngineMessageListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.EventEngineMessageListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.EventEngineMessageListener_change_ownership(this, swigCPtr, true);
  }

  public void handleEvent(EventEngineMessage evt) {
    stiJNI.EventEngineMessageListener_handleEvent(swigCPtr, this, EventEngineMessage.getCPtr(evt), evt);
  }

  public EventEngineMessageListener() {
    this(stiJNI.new_EventEngineMessageListener(), true);
    stiJNI.EventEngineMessageListener_director_connect(this, swigCPtr, true, true);
  }

}
