/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JDeviceCollection {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected JDeviceCollection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JDeviceCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JDeviceCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean add(DeviceID id, JDevice node) {
    return stiJNI.JDeviceCollection_add(swigCPtr, this, DeviceID.getCPtr(id), id, JDevice.getCPtr(node), node);
  }

  public JDevice get(DeviceID id) {
    long cPtr = stiJNI.JDeviceCollection_get(swigCPtr, this, DeviceID.getCPtr(id), id);
    return (cPtr == 0) ? null : new JDevice(cPtr, true);
  }

  public DeviceIDset getIDs() {
    return new DeviceIDset(stiJNI.JDeviceCollection_getIDs(swigCPtr, this), false);
  }

  public boolean remove(DeviceID id) {
    return stiJNI.JDeviceCollection_remove(swigCPtr, this, DeviceID.getCPtr(id), id);
  }

  public boolean contains(DeviceID id) {
    return stiJNI.JDeviceCollection_contains(swigCPtr, this, DeviceID.getCPtr(id), id);
  }

  public long size() {
    return stiJNI.JDeviceCollection_size(swigCPtr, this);
  }

  public void cleanup() {
    stiJNI.JDeviceCollection_cleanup(swigCPtr, this);
  }

  public void clear() {
    stiJNI.JDeviceCollection_clear(swigCPtr, this);
  }

}
