/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JEngineJobUpdateDeviceMessageListener extends EngineJobUpdateDeviceMessageListener {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected JEngineJobUpdateDeviceMessageListener(long cPtr, boolean cMemoryOwn) {
    super(stiJNI.JEngineJobUpdateDeviceMessageListener_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JEngineJobUpdateDeviceMessageListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        stiJNI.delete_JEngineJobUpdateDeviceMessageListener(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.JEngineJobUpdateDeviceMessageListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.JEngineJobUpdateDeviceMessageListener_change_ownership(this, swigCPtr, true);
  }

  public JEngineJobUpdateDeviceMessageListener() {
    this(stiJNI.new_JEngineJobUpdateDeviceMessageListener(), true);
    stiJNI.JEngineJobUpdateDeviceMessageListener_director_connect(this, swigCPtr, true, true);
  }

  public void handleMessage(JEngineJobUpdateDeviceMessage mess) {
    stiJNI.JEngineJobUpdateDeviceMessageListener_handleMessage__SWIG_0(swigCPtr, this, JEngineJobUpdateDeviceMessage.getCPtr(mess), mess);
  }

  public void handleMessage(EngineJobUpdateDeviceMessage mess) {
    if (getClass() == JEngineJobUpdateDeviceMessageListener.class) stiJNI.JEngineJobUpdateDeviceMessageListener_handleMessage__SWIG_1(swigCPtr, this, EngineJobUpdateDeviceMessage.getCPtr(mess), mess); else stiJNI.JEngineJobUpdateDeviceMessageListener_handleMessageSwigExplicitJEngineJobUpdateDeviceMessageListener__SWIG_1(swigCPtr, this, EngineJobUpdateDeviceMessage.getCPtr(mess), mess);
  }

}
