/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JEventEngine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected JEventEngine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JEventEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JEventEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void play(JEventEngineJob job) {
    stiJNI.JEventEngine_play(swigCPtr, this, JEventEngineJob.getCPtr(job), job);
  }

  public void stop() {
    stiJNI.JEventEngine_stop(swigCPtr, this);
  }

  public void pause() {
    stiJNI.JEventEngine_pause(swigCPtr, this);
  }

  public void unpause(boolean retrigger) {
    stiJNI.JEventEngine_unpause(swigCPtr, this, retrigger);
  }

  public DeviceID getDeviceID() {
    return new DeviceID(stiJNI.JEventEngine_getDeviceID(swigCPtr, this), true);
  }

  public EngineState getState() {
    return EngineState.swigToEnum(stiJNI.JEventEngine_getState(swigCPtr, this));
  }

}
