/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JHubGraphNode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JHubGraphNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JHubGraphNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JHubGraphNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HubID getHubID() {
    return new HubID(stiJNI.JHubGraphNode_getHubID(swigCPtr, this), false);
  }

  public JDeviceGraphNodeVector getNodes() {
    return new JDeviceGraphNodeVector(stiJNI.JHubGraphNode_getNodes(swigCPtr, this), false);
  }

}
