/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JLocalDevice extends JDevice {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected JLocalDevice(long cPtr, boolean cMemoryOwn) {
    super(stiJNI.JLocalDevice_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JLocalDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        stiJNI.delete_JLocalDevice(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.JLocalDevice_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.JLocalDevice_change_ownership(this, swigCPtr, true);
  }

  public JLocalDevice(String name, String address, int module, String targetServer) {
    this(stiJNI.new_JLocalDevice(name, address, module, targetServer), true);
    stiJNI.JLocalDevice_director_connect(this, swigCPtr, true, true);
  }

  public JDeviceEventReceiver getEventReceiver() {
    long cPtr = stiJNI.JLocalDevice_getEventReceiver(swigCPtr, this);
    return (cPtr == 0) ? null : new JDeviceEventReceiver(cPtr, true);
  }

  public JEventEngineScheduler getEngineScheduler() {
    long cPtr = stiJNI.JLocalDevice_getEngineScheduler(swigCPtr, this);
    return (cPtr == 0) ? null : new JEventEngineScheduler(cPtr, true);
  }

  public void parseEvents(int temp) {
    stiJNI.JLocalDevice_parseEvents(swigCPtr, this, temp);
  }

  public LocalChannel addChannel(int channelNumber, ChannelType type, MixedValueType inputType, MixedValueType outputType, String defaultName) {
    return new LocalChannel(stiJNI.JLocalDevice_addChannel(swigCPtr, this, channelNumber, type.swigValue(), inputType.swigValue(), outputType.swigValue(), defaultName), true);
  }

  public void addEventEngine(EngineID engineID) {
    stiJNI.JLocalDevice_addEventEngine(swigCPtr, this, EngineID.getCPtr(engineID), engineID);
  }

}
