/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JShot {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected JShot(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JShot obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JShot(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JShot(SWIGTYPE_p_std__shared_ptrT_STI__Engine__Shot_t shot) {
    this(stiJNI.new_JShot(SWIGTYPE_p_std__shared_ptrT_STI__Engine__Shot_t.getCPtr(shot)), true);
  }

  public RawEventVector getEvents() {
    long cPtr = stiJNI.JShot_getEvents(swigCPtr, this);
    return (cPtr == 0) ? null : new RawEventVector(cPtr, true);
  }

}
