/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class LocalChannel extends Channel {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected LocalChannel(long cPtr, boolean cMemoryOwn) {
    super(stiJNI.LocalChannel_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LocalChannel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        stiJNI.delete_LocalChannel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.LocalChannel_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.LocalChannel_change_ownership(this, swigCPtr, true);
  }

  public LocalChannel() {
    this(stiJNI.new_LocalChannel__SWIG_0(), true);
    stiJNI.LocalChannel_director_connect(this, swigCPtr, true, true);
  }

  public LocalChannel(int channelNumber, ChannelType type, MixedValueType inputType, MixedValueType outputType, String defaultName) {
    this(stiJNI.new_LocalChannel__SWIG_1(channelNumber, type.swigValue(), inputType.swigValue(), outputType.swigValue(), defaultName), true);
    stiJNI.LocalChannel_director_connect(this, swigCPtr, true, true);
  }

  public short getChannelNumber() {
    return (getClass() == LocalChannel.class) ? stiJNI.LocalChannel_getChannelNumber(swigCPtr, this) : stiJNI.LocalChannel_getChannelNumberSwigExplicitLocalChannel(swigCPtr, this);
  }

  public ChannelType getType() {
    return ChannelType.swigToEnum((getClass() == LocalChannel.class) ? stiJNI.LocalChannel_getType(swigCPtr, this) : stiJNI.LocalChannel_getTypeSwigExplicitLocalChannel(swigCPtr, this));
  }

  public MixedValueType getInputType() {
    return MixedValueType.swigToEnum((getClass() == LocalChannel.class) ? stiJNI.LocalChannel_getInputType(swigCPtr, this) : stiJNI.LocalChannel_getInputTypeSwigExplicitLocalChannel(swigCPtr, this));
  }

  public MixedValueType getOutputType() {
    return MixedValueType.swigToEnum((getClass() == LocalChannel.class) ? stiJNI.LocalChannel_getOutputType(swigCPtr, this) : stiJNI.LocalChannel_getOutputTypeSwigExplicitLocalChannel(swigCPtr, this));
  }

  public String getChannelName() {
    return (getClass() == LocalChannel.class) ? stiJNI.LocalChannel_getChannelName(swigCPtr, this) : stiJNI.LocalChannel_getChannelNameSwigExplicitLocalChannel(swigCPtr, this);
  }

  public MixedValue getLastValue() {
    return new MixedValue((getClass() == LocalChannel.class) ? stiJNI.LocalChannel_getLastValue(swigCPtr, this) : stiJNI.LocalChannel_getLastValueSwigExplicitLocalChannel(swigCPtr, this), true);
  }

  public MixedValue getMetaData() {
    return new MixedValue((getClass() == LocalChannel.class) ? stiJNI.LocalChannel_getMetaData__SWIG_0(swigCPtr, this) : stiJNI.LocalChannel_getMetaDataSwigExplicitLocalChannel__SWIG_0(swigCPtr, this), false);
  }

  public MixedValue getMetaData(String key) {
    return new MixedValue((getClass() == LocalChannel.class) ? stiJNI.LocalChannel_getMetaData__SWIG_1(swigCPtr, this, key) : stiJNI.LocalChannel_getMetaDataSwigExplicitLocalChannel__SWIG_1(swigCPtr, this, key), true);
  }

  public void setChannelName(String name) {
    if (getClass() == LocalChannel.class) stiJNI.LocalChannel_setChannelName(swigCPtr, this, name); else stiJNI.LocalChannel_setChannelNameSwigExplicitLocalChannel(swigCPtr, this, name);
  }

  public void saveLastValue(MixedValue value) {
    if (getClass() == LocalChannel.class) stiJNI.LocalChannel_saveLastValue(swigCPtr, this, MixedValue.getCPtr(value), value); else stiJNI.LocalChannel_saveLastValueSwigExplicitLocalChannel(swigCPtr, this, MixedValue.getCPtr(value), value);
  }

  public LocalChannel addMetaData(String key, MixedValue value) {
    return new LocalChannel(stiJNI.LocalChannel_addMetaData(swigCPtr, this, key, MixedValue.getCPtr(value), value), true);
  }

}
