/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public final class ParsingMessageType {
  public final static ParsingMessageType Error = new ParsingMessageType("Error");
  public final static ParsingMessageType Warning = new ParsingMessageType("Warning");
  public final static ParsingMessageType Information = new ParsingMessageType("Information");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ParsingMessageType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ParsingMessageType.class + " with value " + swigValue);
  }

  private ParsingMessageType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ParsingMessageType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ParsingMessageType(String swigName, ParsingMessageType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ParsingMessageType[] swigValues = { Error, Warning, Information };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

