/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class ParseID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParseID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParseID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_ParseID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParseTimestamp(TimeStamp value) {
    stiJNI.ParseID_parseTimestamp_set(swigCPtr, this, TimeStamp.getCPtr(value), value);
  }

  public TimeStamp getParseTimestamp() {
    long cPtr = stiJNI.ParseID_parseTimestamp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TimeStamp(cPtr, false);
  }

  public void setFile(String value) {
    stiJNI.ParseID_file_set(swigCPtr, this, value);
  }

  public String getFile() {
    return stiJNI.ParseID_file_get(swigCPtr, this);
  }

  public void setJobSourceID(EngineJobSourceID value) {
    stiJNI.ParseID_jobSourceID_set(swigCPtr, this, EngineJobSourceID.getCPtr(value), value);
  }

  public EngineJobSourceID getJobSourceID() {
    long cPtr = stiJNI.ParseID_jobSourceID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineJobSourceID(cPtr, false);
  }

  public void setComment(String value) {
    stiJNI.ParseID_comment_set(swigCPtr, this, value);
  }

  public String getComment() {
    return stiJNI.ParseID_comment_get(swigCPtr, this);
  }

  public boolean opLess(ParseID rhs) {
    return stiJNI.ParseID_opLess(swigCPtr, this, ParseID.getCPtr(rhs), rhs);
  }

  public boolean opEquals(ParseID rhs) {
    return stiJNI.ParseID_opEquals(swigCPtr, this, ParseID.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(ParseID rhs) {
    return stiJNI.ParseID_opNotEquals(swigCPtr, this, ParseID.getCPtr(rhs), rhs);
  }

  public ParseID() {
    this(stiJNI.new_ParseID(), true);
  }

  public final static class ShotType {
    public final static ParseID.ShotType Single = new ParseID.ShotType("Single");
    public final static ParseID.ShotType Sequence = new ParseID.ShotType("Sequence");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ShotType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ShotType.class + " with value " + swigValue);
    }

    private ShotType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ShotType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ShotType(String swigName, ShotType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ShotType[] swigValues = { Single, Sequence };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
