/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class RawEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RawEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RawEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_RawEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RawEvent() {
    this(stiJNI.new_RawEvent__SWIG_0(), true);
  }

  public RawEvent(DeviceID targetDeviceID, double time, int channel, MixedValue value, String description, long eventNumber, RawEventType eventType) {
    this(stiJNI.new_RawEvent__SWIG_1(DeviceID.getCPtr(targetDeviceID), targetDeviceID, time, channel, MixedValue.getCPtr(value), value, description, eventNumber, eventType.swigValue()), true);
  }

  public RawEvent(RawEvent newEvent, RawEvent referenceEvent, long eventNumber) {
    this(stiJNI.new_RawEvent__SWIG_2(RawEvent.getCPtr(newEvent), newEvent, RawEvent.getCPtr(referenceEvent), referenceEvent, eventNumber), true);
  }

  public String print() {
    return stiJNI.RawEvent_print(swigCPtr, this);
  }

  public double time() {
    return stiJNI.RawEvent_time(swigCPtr, this);
  }

  public int channel() {
    return stiJNI.RawEvent_channel(swigCPtr, this);
  }

  public MixedValue value() {
    return new MixedValue(stiJNI.RawEvent_value(swigCPtr, this), false);
  }

  public String description() {
    return stiJNI.RawEvent_description(swigCPtr, this);
  }

  public RawEventType type() {
    return RawEventType.swigToEnum(stiJNI.RawEvent_type(swigCPtr, this));
  }

  public DeviceID targetDevice() {
    return new DeviceID(stiJNI.RawEvent_targetDevice(swigCPtr, this), false);
  }

  public EventStackTrace getStackTrace() {
    return new EventStackTrace(stiJNI.RawEvent_getStackTrace(swigCPtr, this), false);
  }

  public UIntVector getEventGraphPath() {
    return new UIntVector(stiJNI.RawEvent_getEventGraphPath(swigCPtr, this), false);
  }

  public boolean isMeasurementEvent() {
    return stiJNI.RawEvent_isMeasurementEvent(swigCPtr, this);
  }

  public boolean opEquals(RawEvent rhs) {
    return stiJNI.RawEvent_opEquals(swigCPtr, this, RawEvent.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(RawEvent rhs) {
    return stiJNI.RawEvent_opNotEquals(swigCPtr, this, RawEvent.getCPtr(rhs), rhs);
  }

  public void setTargetID(DeviceID targetID) {
    stiJNI.RawEvent_setTargetID(swigCPtr, this, DeviceID.getCPtr(targetID), targetID);
  }

  public void setTime(double time) {
    stiJNI.RawEvent_setTime(swigCPtr, this, time);
  }

  public void setChannel(int channel) {
    stiJNI.RawEvent_setChannel(swigCPtr, this, channel);
  }

  public void setValue(MixedValue value) {
    stiJNI.RawEvent_setValue(swigCPtr, this, MixedValue.getCPtr(value), value);
  }

  public void setDescription(String description) {
    stiJNI.RawEvent_setDescription(swigCPtr, this, description);
  }

  public void setEventGraphPath(UIntVector pathLabel) {
    stiJNI.RawEvent_setEventGraphPath(swigCPtr, this, UIntVector.getCPtr(pathLabel), pathLabel);
  }

  public void setEventType(RawEventType eventType) {
    stiJNI.RawEvent_setEventType(swigCPtr, this, eventType.swigValue());
  }

}
