/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class RawEventMap extends java.util.AbstractMap<DeviceID, RawEventVector> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RawEventMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RawEventMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_RawEventMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof DeviceID)) {
      return false;
    }

    return containsImpl((DeviceID)key);
  }

  public RawEventVector get(java.lang.Object key) {
    if (!(key instanceof DeviceID)) {
      return null;
    }

    Iterator itr = find((DeviceID) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public RawEventVector put(DeviceID key, RawEventVector value) {
    Iterator itr = find((DeviceID) key);
    if (itr.isNot(end())) {
      RawEventVector oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public RawEventVector remove(java.lang.Object key) {
    if (!(key instanceof DeviceID)) {
      return null;
    }

    Iterator itr = find((DeviceID) key);
    if (itr.isNot(end())) {
      RawEventVector oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<DeviceID, RawEventVector>> entrySet() {
    java.util.Set<Entry<DeviceID, RawEventVector>> setToReturn =
        new java.util.HashSet<Entry<DeviceID, RawEventVector>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<DeviceID, RawEventVector>() {
        private Iterator iterator;

        private Entry<DeviceID, RawEventVector> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public DeviceID getKey() {
          return iterator.getKey();
        }

        public RawEventVector getValue() {
          return iterator.getValue();
        }

        public RawEventVector setValue(RawEventVector newValue) {
          RawEventVector oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public RawEventMap() {
    this(stiJNI.new_RawEventMap__SWIG_0(), true);
  }

  public RawEventMap(RawEventMap other) {
    this(stiJNI.new_RawEventMap__SWIG_1(RawEventMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stiJNI.delete_RawEventMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private RawEventMap.Iterator getNextUnchecked() {
      return new RawEventMap.Iterator(stiJNI.RawEventMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(RawEventMap.Iterator other) {
      return stiJNI.RawEventMap_Iterator_isNot(swigCPtr, this, RawEventMap.Iterator.getCPtr(other), other);
    }
  
    private DeviceID getKey() {
      return new DeviceID(stiJNI.RawEventMap_Iterator_getKey(swigCPtr, this), true);
    }
  
    private RawEventVector getValue() {
      return new RawEventVector(stiJNI.RawEventMap_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(RawEventVector newValue) {
      stiJNI.RawEventMap_Iterator_setValue(swigCPtr, this, RawEventVector.getCPtr(newValue), newValue);
    }
  
  }

  public boolean isEmpty() {
    return stiJNI.RawEventMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.RawEventMap_clear(swigCPtr, this);
  }

  private RawEventMap.Iterator find(DeviceID key) {
    return new RawEventMap.Iterator(stiJNI.RawEventMap_find(swigCPtr, this, DeviceID.getCPtr(key), key), true);
  }

  private RawEventMap.Iterator begin() {
    return new RawEventMap.Iterator(stiJNI.RawEventMap_begin(swigCPtr, this), true);
  }

  private RawEventMap.Iterator end() {
    return new RawEventMap.Iterator(stiJNI.RawEventMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return stiJNI.RawEventMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(DeviceID key) {
    return stiJNI.RawEventMap_containsImpl(swigCPtr, this, DeviceID.getCPtr(key), key);
  }

  private void putUnchecked(DeviceID key, RawEventVector value) {
    stiJNI.RawEventMap_putUnchecked(swigCPtr, this, DeviceID.getCPtr(key), key, RawEventVector.getCPtr(value), value);
  }

  private void removeUnchecked(RawEventMap.Iterator itr) {
    stiJNI.RawEventMap_removeUnchecked(swigCPtr, this, RawEventMap.Iterator.getCPtr(itr), itr);
  }

}
