/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class sti {
  public static String printShotType(ShotType type) {
    return stiJNI.printShotType(type.swigValue());
  }

  public static String print(EngineState state) {
    return stiJNI.print(state.swigValue());
  }

}
