/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class stiJNI {
  public final static native long new_DeviceID__SWIG_0();
  public final static native long new_DeviceID__SWIG_1(String jarg1);
  public final static native long new_DeviceID__SWIG_2(String jarg1, String jarg2, int jarg3);
  public final static native long new_DeviceID__SWIG_3(String jarg1, String jarg2, int jarg3, String jarg4);
  public final static native boolean DeviceID_opLess(long jarg1, DeviceID jarg1_, long jarg2, DeviceID jarg2_);
  public final static native boolean DeviceID_opEquals(long jarg1, DeviceID jarg1_, long jarg2, DeviceID jarg2_);
  public final static native boolean DeviceID_opNotEquals(long jarg1, DeviceID jarg1_, long jarg2, DeviceID jarg2_);
  public final static native String DeviceID_getName(long jarg1, DeviceID jarg1_);
  public final static native String DeviceID_getAddress(long jarg1, DeviceID jarg1_);
  public final static native int DeviceID_getModule(long jarg1, DeviceID jarg1_);
  public final static native String DeviceID_getID(long jarg1, DeviceID jarg1_);
  public final static native String DeviceID_getTargetServerID(long jarg1, DeviceID jarg1_);
  public final static native boolean DeviceID_stringToDeviceID(String jarg1, long jarg2, DeviceID jarg2_);
  public final static native String DeviceID_generateID(String jarg1, String jarg2, int jarg3);
  public final static native String DeviceID_generateContext(long jarg1, DeviceID jarg1_);
  public final static native void delete_DeviceID(long jarg1);
  public final static native void DeviceIDset_Iterator_incrementUnchecked(long jarg1, DeviceIDset.Iterator jarg1_);
  public final static native long DeviceIDset_Iterator_derefUnchecked(long jarg1, DeviceIDset.Iterator jarg1_);
  public final static native boolean DeviceIDset_Iterator_isNot(long jarg1, DeviceIDset.Iterator jarg1_, long jarg2, DeviceIDset.Iterator jarg2_);
  public final static native void delete_DeviceIDset_Iterator(long jarg1);
  public final static native long new_DeviceIDset__SWIG_0();
  public final static native long new_DeviceIDset__SWIG_1(long jarg1, DeviceIDset jarg1_);
  public final static native boolean DeviceIDset_isEmpty(long jarg1, DeviceIDset jarg1_);
  public final static native void DeviceIDset_clear(long jarg1, DeviceIDset jarg1_);
  public final static native long DeviceIDset_begin(long jarg1, DeviceIDset jarg1_);
  public final static native long DeviceIDset_end(long jarg1, DeviceIDset jarg1_);
  public final static native boolean DeviceIDset_addImpl(long jarg1, DeviceIDset jarg1_, long jarg2, DeviceID jarg2_);
  public final static native boolean DeviceIDset_containsImpl(long jarg1, DeviceIDset jarg1_, long jarg2, DeviceID jarg2_);
  public final static native boolean DeviceIDset_removeImpl(long jarg1, DeviceIDset jarg1_, long jarg2, DeviceID jarg2_);
  public final static native int DeviceIDset_sizeImpl(long jarg1, DeviceIDset jarg1_);
  public final static native boolean DeviceIDset_hasNextImpl(long jarg1, DeviceIDset jarg1_, long jarg2, DeviceIDset.Iterator jarg2_);
  public final static native void delete_DeviceIDset(long jarg1);
  public final static native long new_DeviceIDvector__SWIG_0();
  public final static native long new_DeviceIDvector__SWIG_1(long jarg1, DeviceIDvector jarg1_);
  public final static native long DeviceIDvector_capacity(long jarg1, DeviceIDvector jarg1_);
  public final static native void DeviceIDvector_reserve(long jarg1, DeviceIDvector jarg1_, long jarg2);
  public final static native boolean DeviceIDvector_isEmpty(long jarg1, DeviceIDvector jarg1_);
  public final static native void DeviceIDvector_clear(long jarg1, DeviceIDvector jarg1_);
  public final static native long new_DeviceIDvector__SWIG_2(int jarg1, long jarg2, DeviceID jarg2_);
  public final static native int DeviceIDvector_doSize(long jarg1, DeviceIDvector jarg1_);
  public final static native void DeviceIDvector_doAdd__SWIG_0(long jarg1, DeviceIDvector jarg1_, long jarg2, DeviceID jarg2_);
  public final static native void DeviceIDvector_doAdd__SWIG_1(long jarg1, DeviceIDvector jarg1_, int jarg2, long jarg3, DeviceID jarg3_);
  public final static native long DeviceIDvector_doRemove(long jarg1, DeviceIDvector jarg1_, int jarg2);
  public final static native long DeviceIDvector_doGet(long jarg1, DeviceIDvector jarg1_, int jarg2);
  public final static native long DeviceIDvector_doSet(long jarg1, DeviceIDvector jarg1_, int jarg2, long jarg3, DeviceID jarg3_);
  public final static native void DeviceIDvector_doRemoveRange(long jarg1, DeviceIDvector jarg1_, int jarg2, int jarg3);
  public final static native void delete_DeviceIDvector(long jarg1);
  public final static native long new_EngineID__SWIG_0();
  public final static native long new_EngineID__SWIG_1(short jarg1);
  public final static native boolean EngineID_opLess(long jarg1, EngineID jarg1_, long jarg2, EngineID jarg2_);
  public final static native boolean EngineID_opEquals(long jarg1, EngineID jarg1_, long jarg2, EngineID jarg2_);
  public final static native boolean EngineID_opNotEquals(long jarg1, EngineID jarg1_, long jarg2, EngineID jarg2_);
  public final static native short EngineID_getNumber(long jarg1, EngineID jarg1_);
  public final static native void EngineID_setNumber(long jarg1, EngineID jarg1_, short jarg2);
  public final static native void delete_EngineID(long jarg1);
  public final static native long new_UIntVector__SWIG_0();
  public final static native long new_UIntVector__SWIG_1(long jarg1, UIntVector jarg1_);
  public final static native long UIntVector_capacity(long jarg1, UIntVector jarg1_);
  public final static native void UIntVector_reserve(long jarg1, UIntVector jarg1_, long jarg2);
  public final static native boolean UIntVector_isEmpty(long jarg1, UIntVector jarg1_);
  public final static native void UIntVector_clear(long jarg1, UIntVector jarg1_);
  public final static native long new_UIntVector__SWIG_2(int jarg1, long jarg2);
  public final static native int UIntVector_doSize(long jarg1, UIntVector jarg1_);
  public final static native void UIntVector_doAdd__SWIG_0(long jarg1, UIntVector jarg1_, long jarg2);
  public final static native void UIntVector_doAdd__SWIG_1(long jarg1, UIntVector jarg1_, int jarg2, long jarg3);
  public final static native long UIntVector_doRemove(long jarg1, UIntVector jarg1_, int jarg2);
  public final static native long UIntVector_doGet(long jarg1, UIntVector jarg1_, int jarg2);
  public final static native long UIntVector_doSet(long jarg1, UIntVector jarg1_, int jarg2, long jarg3);
  public final static native void UIntVector_doRemoveRange(long jarg1, UIntVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_UIntVector(long jarg1);
  public final static native String EventStackTrace_file(long jarg1, EventStackTrace jarg1_);
  public final static native int EventStackTrace_line(long jarg1, EventStackTrace jarg1_);
  public final static native String EventStackTrace_print__SWIG_0(long jarg1, EventStackTrace jarg1_, String jarg2);
  public final static native String EventStackTrace_print__SWIG_1(long jarg1, EventStackTrace jarg1_);
  public final static native long new_EventStackTrace();
  public final static native void delete_EventStackTrace(long jarg1);
  public final static native long new_RawEvent__SWIG_0();
  public final static native long new_RawEvent__SWIG_1(long jarg1, DeviceID jarg1_, double jarg2, int jarg3, long jarg4, MixedValue jarg4_, String jarg5, long jarg6, int jarg7);
  public final static native long new_RawEvent__SWIG_2(long jarg1, RawEvent jarg1_, long jarg2, RawEvent jarg2_, long jarg3);
  public final static native void delete_RawEvent(long jarg1);
  public final static native String RawEvent_print(long jarg1, RawEvent jarg1_);
  public final static native double RawEvent_time(long jarg1, RawEvent jarg1_);
  public final static native int RawEvent_channel(long jarg1, RawEvent jarg1_);
  public final static native long RawEvent_value(long jarg1, RawEvent jarg1_);
  public final static native String RawEvent_description(long jarg1, RawEvent jarg1_);
  public final static native int RawEvent_type(long jarg1, RawEvent jarg1_);
  public final static native long RawEvent_targetDevice(long jarg1, RawEvent jarg1_);
  public final static native long RawEvent_getStackTrace(long jarg1, RawEvent jarg1_);
  public final static native long RawEvent_getEventGraphPath(long jarg1, RawEvent jarg1_);
  public final static native boolean RawEvent_isMeasurementEvent(long jarg1, RawEvent jarg1_);
  public final static native boolean RawEvent_opEquals(long jarg1, RawEvent jarg1_, long jarg2, RawEvent jarg2_);
  public final static native boolean RawEvent_opNotEquals(long jarg1, RawEvent jarg1_, long jarg2, RawEvent jarg2_);
  public final static native void RawEvent_setTargetID(long jarg1, RawEvent jarg1_, long jarg2, DeviceID jarg2_);
  public final static native void RawEvent_setTime(long jarg1, RawEvent jarg1_, double jarg2);
  public final static native void RawEvent_setChannel(long jarg1, RawEvent jarg1_, int jarg2);
  public final static native void RawEvent_setValue(long jarg1, RawEvent jarg1_, long jarg2, MixedValue jarg2_);
  public final static native void RawEvent_setDescription(long jarg1, RawEvent jarg1_, String jarg2);
  public final static native void RawEvent_setEventGraphPath(long jarg1, RawEvent jarg1_, long jarg2, UIntVector jarg2_);
  public final static native void RawEvent_setEventType(long jarg1, RawEvent jarg1_, int jarg2);
  public final static native long new_RawEventVector__SWIG_0();
  public final static native long new_RawEventVector__SWIG_1(long jarg1, RawEventVector jarg1_);
  public final static native long RawEventVector_capacity(long jarg1, RawEventVector jarg1_);
  public final static native void RawEventVector_reserve(long jarg1, RawEventVector jarg1_, long jarg2);
  public final static native boolean RawEventVector_isEmpty(long jarg1, RawEventVector jarg1_);
  public final static native void RawEventVector_clear(long jarg1, RawEventVector jarg1_);
  public final static native long new_RawEventVector__SWIG_2(int jarg1, long jarg2, RawEvent jarg2_);
  public final static native int RawEventVector_doSize(long jarg1, RawEventVector jarg1_);
  public final static native void RawEventVector_doAdd__SWIG_0(long jarg1, RawEventVector jarg1_, long jarg2, RawEvent jarg2_);
  public final static native void RawEventVector_doAdd__SWIG_1(long jarg1, RawEventVector jarg1_, int jarg2, long jarg3, RawEvent jarg3_);
  public final static native long RawEventVector_doRemove(long jarg1, RawEventVector jarg1_, int jarg2);
  public final static native long RawEventVector_doGet(long jarg1, RawEventVector jarg1_, int jarg2);
  public final static native long RawEventVector_doSet(long jarg1, RawEventVector jarg1_, int jarg2, long jarg3, RawEvent jarg3_);
  public final static native void RawEventVector_doRemoveRange(long jarg1, RawEventVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_RawEventVector(long jarg1);
  public final static native long new_JDeviceCollection(long jarg1);
  public final static native void delete_JDeviceCollection(long jarg1);
  public final static native boolean JDeviceCollection_add(long jarg1, JDeviceCollection jarg1_, long jarg2, DeviceID jarg2_, long jarg3, JDevice jarg3_);
  public final static native long JDeviceCollection_get(long jarg1, JDeviceCollection jarg1_, long jarg2, DeviceID jarg2_);
  public final static native long JDeviceCollection_getIDs(long jarg1, JDeviceCollection jarg1_);
  public final static native boolean JDeviceCollection_remove(long jarg1, JDeviceCollection jarg1_, long jarg2, DeviceID jarg2_);
  public final static native boolean JDeviceCollection_contains(long jarg1, JDeviceCollection jarg1_, long jarg2, DeviceID jarg2_);
  public final static native long JDeviceCollection_size(long jarg1, JDeviceCollection jarg1_);
  public final static native void JDeviceCollection_cleanup(long jarg1, JDeviceCollection jarg1_);
  public final static native void JDeviceCollection_clear(long jarg1, JDeviceCollection jarg1_);
  public final static native long new_JDevice__SWIG_0(long jarg1);
  public final static native long new_JDevice__SWIG_1(String jarg1, String jarg2, int jarg3, String jarg4);
  public final static native void delete_JDevice(long jarg1);
  public final static native long JDevice_getID(long jarg1, JDevice jarg1_);
  public final static native boolean JDevice_refresh(long jarg1, JDevice jarg1_);
  public final static native long JDevice_getCollection(long jarg1, JDevice jarg1_);
  public final static native long JDevice_getMessageDispatcher(long jarg1, JDevice jarg1_);
  public final static native long JDevice_getEngineScheduler(long jarg1, JDevice jarg1_);
  public final static native long JDevice_getChannelManager(long jarg1, JDevice jarg1_);
  public final static native void JDevice_director_connect(JDevice obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void JDevice_change_ownership(JDevice obj, long cptr, boolean take_or_release);
  public final static native long new_DeviceMessage__SWIG_0();
  public final static native long new_DeviceMessage__SWIG_1(long jarg1, DeviceID jarg1_, int jarg2);
  public final static native void delete_DeviceMessage(long jarg1);
  public final static native long DeviceMessage_sourceID(long jarg1, DeviceMessage jarg1_);
  public final static native int DeviceMessage_getType(long jarg1, DeviceMessage jarg1_);
  public final static native int DeviceMessage_getMessageClassType();
  public final static native String DeviceMessage_typeToString(int jarg1);
  public final static native void DeviceMessage_director_connect(DeviceMessage obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void DeviceMessage_change_ownership(DeviceMessage obj, long cptr, boolean take_or_release);
  public final static native long new_RefreshDeviceMessage(long jarg1, DeviceID jarg1_);
  public final static native int RefreshDeviceMessage_getMessageClassType();
  public final static native void delete_RefreshDeviceMessage(long jarg1);
  public final static native void RefreshDeviceMessage_director_connect(RefreshDeviceMessage obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void RefreshDeviceMessage_change_ownership(RefreshDeviceMessage obj, long cptr, boolean take_or_release);
  public final static native long new_ChannelUpdateDeviceMessage(long jarg1, DeviceID jarg1_);
  public final static native int ChannelUpdateDeviceMessage_getMessageClassType();
  public final static native void delete_ChannelUpdateDeviceMessage(long jarg1);
  public final static native void ChannelUpdateDeviceMessage_director_connect(ChannelUpdateDeviceMessage obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ChannelUpdateDeviceMessage_change_ownership(ChannelUpdateDeviceMessage obj, long cptr, boolean take_or_release);
  public final static native long new_AttributeUpdateMessage(long jarg1, DeviceID jarg1_, String jarg2, String jarg3);
  public final static native int AttributeUpdateMessage_getMessageClassType();
  public final static native boolean AttributeUpdateMessage_appendMessage(long jarg1, AttributeUpdateMessage jarg1_, long jarg2, AttributeUpdateMessage jarg2_);
  public final static native long AttributeUpdateMessage_get(long jarg1, AttributeUpdateMessage jarg1_);
  public final static native void AttributeUpdateMessage_attributes_set(long jarg1, AttributeUpdateMessage jarg1_, long jarg2, StringMap jarg2_);
  public final static native long AttributeUpdateMessage_attributes_get(long jarg1, AttributeUpdateMessage jarg1_);
  public final static native String AttributeUpdateMessage_toString(long jarg1, AttributeUpdateMessage jarg1_);
  public final static native void delete_AttributeUpdateMessage(long jarg1);
  public final static native void AttributeUpdateMessage_director_connect(AttributeUpdateMessage obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void AttributeUpdateMessage_change_ownership(AttributeUpdateMessage obj, long cptr, boolean take_or_release);
  public final static native long new_EngineSchedulerMessage(long jarg1, DeviceID jarg1_, long jarg2, DeviceID jarg2_, int jarg3);
  public final static native int EngineSchedulerMessage_getMessageClassType();
  public final static native void EngineSchedulerMessage_schedulerMessageType_set(long jarg1, EngineSchedulerMessage jarg1_, int jarg2);
  public final static native int EngineSchedulerMessage_schedulerMessageType_get(long jarg1, EngineSchedulerMessage jarg1_);
  public final static native void EngineSchedulerMessage_originalSource_set(long jarg1, EngineSchedulerMessage jarg1_, long jarg2, DeviceID jarg2_);
  public final static native long EngineSchedulerMessage_originalSource_get(long jarg1, EngineSchedulerMessage jarg1_);
  public final static native void EngineSchedulerMessage_jobID_set(long jarg1, EngineSchedulerMessage jarg1_, long jarg2, EngineJobID jarg2_);
  public final static native long EngineSchedulerMessage_jobID_get(long jarg1, EngineSchedulerMessage jarg1_);
  public final static native void EngineSchedulerMessage_engine_set(long jarg1, EngineSchedulerMessage jarg1_, long jarg2);
  public final static native long EngineSchedulerMessage_engine_get(long jarg1, EngineSchedulerMessage jarg1_);
  public final static native void EngineSchedulerMessage_handledEvents_set(long jarg1, EngineSchedulerMessage jarg1_, long jarg2, RawEventVector jarg2_);
  public final static native long EngineSchedulerMessage_handledEvents_get(long jarg1, EngineSchedulerMessage jarg1_);
  public final static native void EngineSchedulerMessage_unhandledEvents_set(long jarg1, EngineSchedulerMessage jarg1_, long jarg2, RawEventVector jarg2_);
  public final static native long EngineSchedulerMessage_unhandledEvents_get(long jarg1, EngineSchedulerMessage jarg1_);
  public final static native void delete_EngineSchedulerMessage(long jarg1);
  public final static native void EngineSchedulerMessage_director_connect(EngineSchedulerMessage obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void EngineSchedulerMessage_change_ownership(EngineSchedulerMessage obj, long cptr, boolean take_or_release);
  public final static native void STIParsingMessage_id_code_set(long jarg1, STIParsingMessage jarg1_, long jarg2);
  public final static native long STIParsingMessage_id_code_get(long jarg1, STIParsingMessage jarg1_);
  public final static native void STIParsingMessage_name_set(long jarg1, STIParsingMessage jarg1_, String jarg2);
  public final static native String STIParsingMessage_name_get(long jarg1, STIParsingMessage jarg1_);
  public final static native void STIParsingMessage_message_set(long jarg1, STIParsingMessage jarg1_, String jarg2);
  public final static native String STIParsingMessage_message_get(long jarg1, STIParsingMessage jarg1_);
  public final static native void STIParsingMessage_events_set(long jarg1, STIParsingMessage jarg1_, long jarg2, RawEventVector jarg2_);
  public final static native long STIParsingMessage_events_get(long jarg1, STIParsingMessage jarg1_);
  public final static native long new_STIParsingMessage();
  public final static native void delete_STIParsingMessage(long jarg1);
  public final static native void EngineParserMessage_pid_set(long jarg1, EngineParserMessage jarg1_, long jarg2, ParseID jarg2_);
  public final static native long EngineParserMessage_pid_get(long jarg1, EngineParserMessage jarg1_);
  public final static native void EngineParserMessage_messages_set(long jarg1, EngineParserMessage jarg1_, long jarg2);
  public final static native long EngineParserMessage_messages_get(long jarg1, EngineParserMessage jarg1_);
  public final static native long new_EngineParserMessage();
  public final static native void delete_EngineParserMessage(long jarg1);
  public final static native void EngineParserMessage_director_connect(EngineParserMessage obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void EngineParserMessage_change_ownership(EngineParserMessage obj, long cptr, boolean take_or_release);
  public final static native long new_EventEngineMessage();
  public final static native void delete_EventEngineMessage(long jarg1);
  public final static native void EventEngineMessage_director_connect(EventEngineMessage obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void EventEngineMessage_change_ownership(EventEngineMessage obj, long cptr, boolean take_or_release);
  public final static native void DeviceMessageListenerID_type_set(long jarg1, DeviceMessageListenerID jarg1_, int jarg2);
  public final static native int DeviceMessageListenerID_type_get(long jarg1, DeviceMessageListenerID jarg1_);
  public final static native void DeviceMessageListenerID_name_set(long jarg1, DeviceMessageListenerID jarg1_, String jarg2);
  public final static native String DeviceMessageListenerID_name_get(long jarg1, DeviceMessageListenerID jarg1_);
  public final static native boolean DeviceMessageListenerID_opLess(long jarg1, DeviceMessageListenerID jarg1_, long jarg2, DeviceMessageListenerID jarg2_);
  public final static native boolean DeviceMessageListenerID_opEquals(long jarg1, DeviceMessageListenerID jarg1_, long jarg2, DeviceMessageListenerID jarg2_);
  public final static native long new_DeviceMessageListenerID();
  public final static native void delete_DeviceMessageListenerID(long jarg1);
  public final static native void delete_RefreshDeviceMessageListener(long jarg1);
  public final static native void RefreshDeviceMessageListener_handleMessage(long jarg1, RefreshDeviceMessageListener jarg1_, long jarg2, RefreshDeviceMessage jarg2_);
  public final static native long new_RefreshDeviceMessageListener();
  public final static native void RefreshDeviceMessageListener_director_connect(RefreshDeviceMessageListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void RefreshDeviceMessageListener_change_ownership(RefreshDeviceMessageListener obj, long cptr, boolean take_or_release);
  public final static native void delete_ChannelUpdateDeviceMessageListener(long jarg1);
  public final static native void ChannelUpdateDeviceMessageListener_handleMessage(long jarg1, ChannelUpdateDeviceMessageListener jarg1_, long jarg2, ChannelUpdateDeviceMessage jarg2_);
  public final static native long new_ChannelUpdateDeviceMessageListener();
  public final static native void ChannelUpdateDeviceMessageListener_director_connect(ChannelUpdateDeviceMessageListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ChannelUpdateDeviceMessageListener_change_ownership(ChannelUpdateDeviceMessageListener obj, long cptr, boolean take_or_release);
  public final static native void delete_AttributeUpdateMessageListener(long jarg1);
  public final static native void AttributeUpdateMessageListener_handleMessage(long jarg1, AttributeUpdateMessageListener jarg1_, long jarg2, AttributeUpdateMessage jarg2_);
  public final static native long new_AttributeUpdateMessageListener();
  public final static native void AttributeUpdateMessageListener_director_connect(AttributeUpdateMessageListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void AttributeUpdateMessageListener_change_ownership(AttributeUpdateMessageListener obj, long cptr, boolean take_or_release);
  public final static native void delete_EngineSchedulerMessageListener(long jarg1);
  public final static native void EngineSchedulerMessageListener_handleMessage(long jarg1, EngineSchedulerMessageListener jarg1_, long jarg2, EngineSchedulerMessage jarg2_);
  public final static native long new_EngineSchedulerMessageListener();
  public final static native void EngineSchedulerMessageListener_director_connect(EngineSchedulerMessageListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void EngineSchedulerMessageListener_change_ownership(EngineSchedulerMessageListener obj, long cptr, boolean take_or_release);
  public final static native void delete_EngineParserMessageListener(long jarg1);
  public final static native void EngineParserMessageListener_handleMessage(long jarg1, EngineParserMessageListener jarg1_, long jarg2, EngineParserMessage jarg2_);
  public final static native long new_EngineParserMessageListener();
  public final static native void EngineParserMessageListener_director_connect(EngineParserMessageListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void EngineParserMessageListener_change_ownership(EngineParserMessageListener obj, long cptr, boolean take_or_release);
  public final static native void delete_EventEngineMessageListener(long jarg1);
  public final static native void EventEngineMessageListener_handleMessage(long jarg1, EventEngineMessageListener jarg1_, long jarg2, EventEngineMessage jarg2_);
  public final static native long new_EventEngineMessageListener();
  public final static native void EventEngineMessageListener_director_connect(EventEngineMessageListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void EventEngineMessageListener_change_ownership(EventEngineMessageListener obj, long cptr, boolean take_or_release);
  public final static native long new_JDeviceMessageReceiver(long jarg1);
  public final static native void delete_JDeviceMessageReceiver(long jarg1);
  public final static native void JDeviceMessageReceiver_addListener__SWIG_0(long jarg1, JDeviceMessageReceiver jarg1_, long jarg2, DeviceID jarg2_, long jarg3, DeviceMessageListenerID jarg3_, long jarg4, RefreshDeviceMessageListener jarg4_);
  public final static native void JDeviceMessageReceiver_addListener__SWIG_1(long jarg1, JDeviceMessageReceiver jarg1_, long jarg2, DeviceID jarg2_, long jarg3, DeviceMessageListenerID jarg3_, long jarg4, ChannelUpdateDeviceMessageListener jarg4_);
  public final static native void JDeviceMessageReceiver_removeListener(long jarg1, JDeviceMessageReceiver jarg1_, long jarg2, DeviceID jarg2_, long jarg3, DeviceMessageListenerID jarg3_);
  public final static native long new_JDeviceMessageDispatcher(long jarg1);
  public final static native void delete_JDeviceMessageDispatcher(long jarg1);
  public final static native void JDeviceMessageDispatcher_addMessage(long jarg1, JDeviceMessageDispatcher jarg1_, long jarg2, DeviceMessage jarg2_);
  public final static native void JDeviceMessageDispatcher_clearMessages(long jarg1, JDeviceMessageDispatcher jarg1_);
  public final static native void delete_Channel(long jarg1);
  public final static native short Channel_getChannelNumber(long jarg1, Channel jarg1_);
  public final static native int Channel_getType(long jarg1, Channel jarg1_);
  public final static native int Channel_getInputType(long jarg1, Channel jarg1_);
  public final static native int Channel_getOutputType(long jarg1, Channel jarg1_);
  public final static native void Channel_setChannelName(long jarg1, Channel jarg1_, String jarg2);
  public final static native String Channel_getChannelName(long jarg1, Channel jarg1_);
  public final static native void Channel_saveLastValue(long jarg1, Channel jarg1_, long jarg2, MixedValue jarg2_);
  public final static native long Channel_getLastValue(long jarg1, Channel jarg1_);
  public final static native long Channel_getMetaData__SWIG_0(long jarg1, Channel jarg1_);
  public final static native long Channel_getMetaData__SWIG_1(long jarg1, Channel jarg1_, String jarg2);
  public final static native String Channel_typeToString(int jarg1);
  public final static native long new_Channel();
  public final static native void Channel_director_connect(Channel obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void Channel_change_ownership(Channel obj, long cptr, boolean take_or_release);
  public final static native long new_ChannelVector__SWIG_0();
  public final static native long new_ChannelVector__SWIG_1(long jarg1, ChannelVector jarg1_);
  public final static native long ChannelVector_capacity(long jarg1, ChannelVector jarg1_);
  public final static native void ChannelVector_reserve(long jarg1, ChannelVector jarg1_, long jarg2);
  public final static native boolean ChannelVector_isEmpty(long jarg1, ChannelVector jarg1_);
  public final static native void ChannelVector_clear(long jarg1, ChannelVector jarg1_);
  public final static native long new_ChannelVector__SWIG_2(int jarg1, long jarg2, Channel jarg2_);
  public final static native int ChannelVector_doSize(long jarg1, ChannelVector jarg1_);
  public final static native void ChannelVector_doAdd__SWIG_0(long jarg1, ChannelVector jarg1_, long jarg2, Channel jarg2_);
  public final static native void ChannelVector_doAdd__SWIG_1(long jarg1, ChannelVector jarg1_, int jarg2, long jarg3, Channel jarg3_);
  public final static native long ChannelVector_doRemove(long jarg1, ChannelVector jarg1_, int jarg2);
  public final static native long ChannelVector_doGet(long jarg1, ChannelVector jarg1_, int jarg2);
  public final static native long ChannelVector_doSet(long jarg1, ChannelVector jarg1_, int jarg2, long jarg3, Channel jarg3_);
  public final static native void ChannelVector_doRemoveRange(long jarg1, ChannelVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_ChannelVector(long jarg1);
  public final static native long new_JChannelManager(long jarg1);
  public final static native void delete_JChannelManager(long jarg1);
  public final static native long JChannelManager_getChannels(long jarg1, JChannelManager jarg1_);
  public final static native long JChannelManager_getChannel(long jarg1, JChannelManager jarg1_, short jarg2);
  public final static native boolean JChannelManager_writeChannel(long jarg1, JChannelManager jarg1_, short jarg2, long jarg3, MixedValue jarg3_);
  public final static native long JChannelManager_readChannel(long jarg1, JChannelManager jarg1_, short jarg2, long jarg3, MixedValue jarg3_);
  public final static native long new_LocalChannel__SWIG_0();
  public final static native long new_LocalChannel__SWIG_1(int jarg1, int jarg2, int jarg3, int jarg4, String jarg5);
  public final static native void delete_LocalChannel(long jarg1);
  public final static native short LocalChannel_getChannelNumber(long jarg1, LocalChannel jarg1_);
  public final static native short LocalChannel_getChannelNumberSwigExplicitLocalChannel(long jarg1, LocalChannel jarg1_);
  public final static native int LocalChannel_getType(long jarg1, LocalChannel jarg1_);
  public final static native int LocalChannel_getTypeSwigExplicitLocalChannel(long jarg1, LocalChannel jarg1_);
  public final static native int LocalChannel_getInputType(long jarg1, LocalChannel jarg1_);
  public final static native int LocalChannel_getInputTypeSwigExplicitLocalChannel(long jarg1, LocalChannel jarg1_);
  public final static native int LocalChannel_getOutputType(long jarg1, LocalChannel jarg1_);
  public final static native int LocalChannel_getOutputTypeSwigExplicitLocalChannel(long jarg1, LocalChannel jarg1_);
  public final static native String LocalChannel_getChannelName(long jarg1, LocalChannel jarg1_);
  public final static native String LocalChannel_getChannelNameSwigExplicitLocalChannel(long jarg1, LocalChannel jarg1_);
  public final static native long LocalChannel_getLastValue(long jarg1, LocalChannel jarg1_);
  public final static native long LocalChannel_getLastValueSwigExplicitLocalChannel(long jarg1, LocalChannel jarg1_);
  public final static native long LocalChannel_getMetaData__SWIG_0(long jarg1, LocalChannel jarg1_);
  public final static native long LocalChannel_getMetaDataSwigExplicitLocalChannel__SWIG_0(long jarg1, LocalChannel jarg1_);
  public final static native long LocalChannel_getMetaData__SWIG_1(long jarg1, LocalChannel jarg1_, String jarg2);
  public final static native long LocalChannel_getMetaDataSwigExplicitLocalChannel__SWIG_1(long jarg1, LocalChannel jarg1_, String jarg2);
  public final static native void LocalChannel_setChannelName(long jarg1, LocalChannel jarg1_, String jarg2);
  public final static native void LocalChannel_setChannelNameSwigExplicitLocalChannel(long jarg1, LocalChannel jarg1_, String jarg2);
  public final static native void LocalChannel_saveLastValue(long jarg1, LocalChannel jarg1_, long jarg2, MixedValue jarg2_);
  public final static native void LocalChannel_saveLastValueSwigExplicitLocalChannel(long jarg1, LocalChannel jarg1_, long jarg2, MixedValue jarg2_);
  public final static native long LocalChannel_addMetaData(long jarg1, LocalChannel jarg1_, String jarg2, long jarg3, MixedValue jarg3_);
  public final static native void LocalChannel_director_connect(LocalChannel obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void LocalChannel_change_ownership(LocalChannel obj, long cptr, boolean take_or_release);
  public final static native void TimeStamp_timestamp_set(long jarg1, TimeStamp jarg1_, double jarg2);
  public final static native double TimeStamp_timestamp_get(long jarg1, TimeStamp jarg1_);
  public final static native String TimeStamp_print(long jarg1, TimeStamp jarg1_);
  public final static native boolean TimeStamp_opLess(long jarg1, TimeStamp jarg1_, long jarg2, TimeStamp jarg2_);
  public final static native boolean TimeStamp_opEquals(long jarg1, TimeStamp jarg1_, long jarg2, TimeStamp jarg2_);
  public final static native boolean TimeStamp_opNotEquals(long jarg1, TimeStamp jarg1_, long jarg2, TimeStamp jarg2_);
  public final static native long new_TimeStamp();
  public final static native void delete_TimeStamp(long jarg1);
  public final static native void EngineJobSourceID_user_set(long jarg1, EngineJobSourceID jarg1_, String jarg2);
  public final static native String EngineJobSourceID_user_get(long jarg1, EngineJobSourceID jarg1_);
  public final static native void EngineJobSourceID_machine_set(long jarg1, EngineJobSourceID jarg1_, String jarg2);
  public final static native String EngineJobSourceID_machine_get(long jarg1, EngineJobSourceID jarg1_);
  public final static native long new_EngineJobSourceID();
  public final static native void delete_EngineJobSourceID(long jarg1);
  public final static native void ParseID_parseTimestamp_set(long jarg1, ParseID jarg1_, long jarg2, TimeStamp jarg2_);
  public final static native long ParseID_parseTimestamp_get(long jarg1, ParseID jarg1_);
  public final static native void ParseID_file_set(long jarg1, ParseID jarg1_, String jarg2);
  public final static native String ParseID_file_get(long jarg1, ParseID jarg1_);
  public final static native void ParseID_jobSourceID_set(long jarg1, ParseID jarg1_, long jarg2, EngineJobSourceID jarg2_);
  public final static native long ParseID_jobSourceID_get(long jarg1, ParseID jarg1_);
  public final static native void ParseID_comment_set(long jarg1, ParseID jarg1_, String jarg2);
  public final static native String ParseID_comment_get(long jarg1, ParseID jarg1_);
  public final static native boolean ParseID_opLess(long jarg1, ParseID jarg1_, long jarg2, ParseID jarg2_);
  public final static native boolean ParseID_opEquals(long jarg1, ParseID jarg1_, long jarg2, ParseID jarg2_);
  public final static native boolean ParseID_opNotEquals(long jarg1, ParseID jarg1_, long jarg2, ParseID jarg2_);
  public final static native long new_ParseID();
  public final static native void delete_ParseID(long jarg1);
  public final static native void ShotID_parseID_set(long jarg1, ShotID jarg1_, long jarg2, ParseID jarg2_);
  public final static native long ShotID_parseID_get(long jarg1, ShotID jarg1_);
  public final static native void ShotID_submissionTime_set(long jarg1, ShotID jarg1_, long jarg2, TimeStamp jarg2_);
  public final static native long ShotID_submissionTime_get(long jarg1, ShotID jarg1_);
  public final static native void ShotID_playTime_set(long jarg1, ShotID jarg1_, long jarg2, TimeStamp jarg2_);
  public final static native long ShotID_playTime_get(long jarg1, ShotID jarg1_);
  public final static native void ShotID_jobSourceID_set(long jarg1, ShotID jarg1_, long jarg2, EngineJobSourceID jarg2_);
  public final static native long ShotID_jobSourceID_get(long jarg1, ShotID jarg1_);
  public final static native boolean ShotID_opLess(long jarg1, ShotID jarg1_, long jarg2, ShotID jarg2_);
  public final static native boolean ShotID_opEquals(long jarg1, ShotID jarg1_, long jarg2, ShotID jarg2_);
  public final static native boolean ShotID_opNotEquals(long jarg1, ShotID jarg1_, long jarg2, ShotID jarg2_);
  public final static native long new_ShotID();
  public final static native void delete_ShotID(long jarg1);
  public final static native long new_StringMap__SWIG_0();
  public final static native long new_StringMap__SWIG_1(long jarg1, StringMap jarg1_);
  public final static native long StringMap_Iterator_getNextUnchecked(long jarg1, StringMap.Iterator jarg1_);
  public final static native boolean StringMap_Iterator_isNot(long jarg1, StringMap.Iterator jarg1_, long jarg2, StringMap.Iterator jarg2_);
  public final static native String StringMap_Iterator_getKey(long jarg1, StringMap.Iterator jarg1_);
  public final static native String StringMap_Iterator_getValue(long jarg1, StringMap.Iterator jarg1_);
  public final static native void StringMap_Iterator_setValue(long jarg1, StringMap.Iterator jarg1_, String jarg2);
  public final static native void delete_StringMap_Iterator(long jarg1);
  public final static native boolean StringMap_isEmpty(long jarg1, StringMap jarg1_);
  public final static native void StringMap_clear(long jarg1, StringMap jarg1_);
  public final static native long StringMap_find(long jarg1, StringMap jarg1_, String jarg2);
  public final static native long StringMap_begin(long jarg1, StringMap jarg1_);
  public final static native long StringMap_end(long jarg1, StringMap jarg1_);
  public final static native int StringMap_sizeImpl(long jarg1, StringMap jarg1_);
  public final static native boolean StringMap_containsImpl(long jarg1, StringMap jarg1_, String jarg2);
  public final static native void StringMap_putUnchecked(long jarg1, StringMap jarg1_, String jarg2, String jarg3);
  public final static native void StringMap_removeUnchecked(long jarg1, StringMap jarg1_, long jarg2, StringMap.Iterator jarg2_);
  public final static native void delete_StringMap(long jarg1);
  public final static native long new_JLocalDevice(String jarg1, String jarg2, int jarg3, String jarg4);
  public final static native void delete_JLocalDevice(long jarg1);
  public final static native long JLocalDevice_getMessageReceiver(long jarg1, JLocalDevice jarg1_);
  public final static native long JLocalDevice_getEngineScheduler(long jarg1, JLocalDevice jarg1_);
  public final static native void JLocalDevice_parseEvents(long jarg1, JLocalDevice jarg1_, int jarg2);
  public final static native long JLocalDevice_addChannel(long jarg1, JLocalDevice jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, String jarg6);
  public final static native void JLocalDevice_addEventEngine(long jarg1, JLocalDevice jarg1_, long jarg2, EngineID jarg2_);
  public final static native void JLocalDevice_director_connect(JLocalDevice obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void JLocalDevice_change_ownership(JLocalDevice obj, long cptr, boolean take_or_release);
  public final static native boolean EngineJobID_opEquals(long jarg1, EngineJobID jarg1_, long jarg2, EngineJobID jarg2_);
  public final static native boolean EngineJobID_opLess(long jarg1, EngineJobID jarg1_, long jarg2, EngineJobID jarg2_);
  public final static native void EngineJobID_type_set(long jarg1, EngineJobID jarg1_, int jarg2);
  public final static native int EngineJobID_type_get(long jarg1, EngineJobID jarg1_);
  public final static native void EngineJobID_pid_set(long jarg1, EngineJobID jarg1_, long jarg2, ParseID jarg2_);
  public final static native long EngineJobID_pid_get(long jarg1, EngineJobID jarg1_);
  public final static native void EngineJobID_sid_set(long jarg1, EngineJobID jarg1_, long jarg2, ShotID jarg2_);
  public final static native long EngineJobID_sid_get(long jarg1, EngineJobID jarg1_);
  public final static native long new_EngineJobID();
  public final static native void delete_EngineJobID(long jarg1);
  public final static native long new_MixedValue__SWIG_0();
  public final static native long new_MixedValue__SWIG_2(long jarg1, MixedValue jarg1_);
  public final static native void delete_MixedValue(long jarg1);
  public final static native boolean MixedValue_opEquals(long jarg1, MixedValue jarg1_, long jarg2, MixedValue jarg2_);
  public final static native boolean MixedValue_opNotEquals(long jarg1, MixedValue jarg1_, long jarg2, MixedValue jarg2_);
  public final static native void MixedValue_setValue__SWIG_2(long jarg1, MixedValue jarg1_, boolean jarg2);
  public final static native void MixedValue_setValue__SWIG_3(long jarg1, MixedValue jarg1_, int jarg2);
  public final static native void MixedValue_setValue__SWIG_4(long jarg1, MixedValue jarg1_, double jarg2);
  public final static native void MixedValue_setValue__SWIG_5(long jarg1, MixedValue jarg1_, String jarg2);
  public final static native void MixedValue_setValue__SWIG_6(long jarg1, MixedValue jarg1_, long jarg2, MixedValue jarg2_);
  public final static native void MixedValue_setValue__SWIG_7(long jarg1, MixedValue jarg1_);
  public final static native void MixedValue_setValue__SWIG_10(long jarg1, MixedValue jarg1_, short jarg2);
  public final static native void MixedValue_clear(long jarg1, MixedValue jarg1_);
  public final static native int MixedValue_getType(long jarg1, MixedValue jarg1_);
  public final static native boolean MixedValue_getBoolean(long jarg1, MixedValue jarg1_);
  public final static native int MixedValue_getInt(long jarg1, MixedValue jarg1_);
  public final static native double MixedValue_getDouble(long jarg1, MixedValue jarg1_);
  public final static native double MixedValue_getNumber(long jarg1, MixedValue jarg1_);
  public final static native String MixedValue_getString(long jarg1, MixedValue jarg1_);
  public final static native long MixedValue_getVector(long jarg1, MixedValue jarg1_);
  public final static native String MixedValue_print(long jarg1, MixedValue jarg1_);
  public final static native String MixedValue_TypeToString(int jarg1);
  public final static native void MixedValue_director_connect(MixedValue obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MixedValue_change_ownership(MixedValue obj, long cptr, boolean take_or_release);
  public final static native long new_MixedValueVec__SWIG_0();
  public final static native long new_MixedValueVec__SWIG_1(long jarg1, MixedValueVec jarg1_);
  public final static native long MixedValueVec_capacity(long jarg1, MixedValueVec jarg1_);
  public final static native void MixedValueVec_reserve(long jarg1, MixedValueVec jarg1_, long jarg2);
  public final static native boolean MixedValueVec_isEmpty(long jarg1, MixedValueVec jarg1_);
  public final static native void MixedValueVec_clear(long jarg1, MixedValueVec jarg1_);
  public final static native long new_MixedValueVec__SWIG_2(int jarg1, long jarg2, MixedValue jarg2_);
  public final static native int MixedValueVec_doSize(long jarg1, MixedValueVec jarg1_);
  public final static native void MixedValueVec_doAdd__SWIG_0(long jarg1, MixedValueVec jarg1_, long jarg2, MixedValue jarg2_);
  public final static native void MixedValueVec_doAdd__SWIG_1(long jarg1, MixedValueVec jarg1_, int jarg2, long jarg3, MixedValue jarg3_);
  public final static native long MixedValueVec_doRemove(long jarg1, MixedValueVec jarg1_, int jarg2);
  public final static native long MixedValueVec_doGet(long jarg1, MixedValueVec jarg1_, int jarg2);
  public final static native long MixedValueVec_doSet(long jarg1, MixedValueVec jarg1_, int jarg2, long jarg3, MixedValue jarg3_);
  public final static native void MixedValueVec_doRemoveRange(long jarg1, MixedValueVec jarg1_, int jarg2, int jarg3);
  public final static native void delete_MixedValueVec(long jarg1);
  public final static native void delete_ParsedShot(long jarg1);
  public final static native void ParsedShot_getEvents(long jarg1, ParsedShot jarg1_, long jarg2, RawEventVector jarg2_);
  public final static native long new_ParsedShot();
  public final static native void ParsedShot_director_connect(ParsedShot obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ParsedShot_change_ownership(ParsedShot obj, long cptr, boolean take_or_release);
  public final static native long new_JEventEngineScheduler(long jarg1);
  public final static native void delete_JEventEngineScheduler(long jarg1);
  public final static native void JEventEngineScheduler_id_set(long jarg1, JEventEngineScheduler jarg1_, long jarg2, DeviceID jarg2_);
  public final static native long JEventEngineScheduler_id_get(long jarg1, JEventEngineScheduler jarg1_);
  public final static native void JEventEngineScheduler_parse(long jarg1, JEventEngineScheduler jarg1_, long jarg2, ParseID jarg2_, long jarg3, ParsedShot jarg3_);
  public final static native void JEventEngineScheduler_play(long jarg1, JEventEngineScheduler jarg1_, long jarg2, ShotID jarg2_);
  public final static native void JEventEngineScheduler_cancelJob(long jarg1, JEventEngineScheduler jarg1_, long jarg2, EngineJobID jarg2_);
  public final static native long new_JNetworkDeviceHub__SWIG_0(String jarg1);
  public final static native long new_JNetworkDeviceHub__SWIG_1(String jarg1, String jarg2, int jarg3, String jarg4);
  public final static native void delete_JNetworkDeviceHub(long jarg1);
  public final static native boolean JNetworkDeviceHub_addNode(long jarg1, JNetworkDeviceHub jarg1_, long jarg2, JDevice jarg2_);
  public final static native void JNetworkDeviceHub_run__SWIG_0(long jarg1, JNetworkDeviceHub jarg1_);
  public final static native void JNetworkDeviceHub_run__SWIG_1(long jarg1, JNetworkDeviceHub jarg1_, boolean jarg2);
  public final static native long JNetworkDeviceHub_walk(long jarg1, JNetworkDeviceHub jarg1_);
  public final static native long new_HubID__SWIG_0();
  public final static native long new_HubID__SWIG_1(String jarg1, String jarg2, int jarg3);
  public final static native boolean HubID_opLess(long jarg1, HubID jarg1_, long jarg2, HubID jarg2_);
  public final static native boolean HubID_opEquals(long jarg1, HubID jarg1_, long jarg2, HubID jarg2_);
  public final static native boolean HubID_opNotEquals(long jarg1, HubID jarg1_, long jarg2, HubID jarg2_);
  public final static native void HubID_name_set(long jarg1, HubID jarg1_, String jarg2);
  public final static native String HubID_name_get(long jarg1, HubID jarg1_);
  public final static native void HubID_address_set(long jarg1, HubID jarg1_, String jarg2);
  public final static native String HubID_address_get(long jarg1, HubID jarg1_);
  public final static native void HubID_module_set(long jarg1, HubID jarg1_, int jarg2);
  public final static native int HubID_module_get(long jarg1, HubID jarg1_);
  public final static native String HubID_id(long jarg1, HubID jarg1_);
  public final static native boolean HubID_stringToHubID(String jarg1, long jarg2, HubID jarg2_);
  public final static native void delete_HubID(long jarg1);
  public final static native long new_JHubGraphNode(long jarg1);
  public final static native void delete_JHubGraphNode(long jarg1);
  public final static native long JHubGraphNode_getHubID(long jarg1, JHubGraphNode jarg1_);
  public final static native long JHubGraphNode_getNodes(long jarg1, JHubGraphNode jarg1_);
  public final static native long new_JNodeWalker(long jarg1);
  public final static native void delete_JNodeWalker(long jarg1);
  public final static native long JNodeWalker_getNode(long jarg1, JNodeWalker jarg1_);
  public final static native long JNodeWalker_getConnections(long jarg1, JNodeWalker jarg1_);
  public final static native long new_JDeviceGraphNode(long jarg1);
  public final static native void delete_JDeviceGraphNode(long jarg1);
  public final static native long JDeviceGraphNode_getID(long jarg1, JDeviceGraphNode jarg1_);
  public final static native long JDeviceGraphNode_getNode(long jarg1, JDeviceGraphNode jarg1_);
  public final static native long JDeviceGraphNode_getOutConnections(long jarg1, JDeviceGraphNode jarg1_);
  public final static native long new_JNodeWalkerVector__SWIG_0();
  public final static native long new_JNodeWalkerVector__SWIG_1(long jarg1, JNodeWalkerVector jarg1_);
  public final static native long JNodeWalkerVector_capacity(long jarg1, JNodeWalkerVector jarg1_);
  public final static native void JNodeWalkerVector_reserve(long jarg1, JNodeWalkerVector jarg1_, long jarg2);
  public final static native boolean JNodeWalkerVector_isEmpty(long jarg1, JNodeWalkerVector jarg1_);
  public final static native void JNodeWalkerVector_clear(long jarg1, JNodeWalkerVector jarg1_);
  public final static native long new_JNodeWalkerVector__SWIG_2(int jarg1, long jarg2, JNodeWalker jarg2_);
  public final static native int JNodeWalkerVector_doSize(long jarg1, JNodeWalkerVector jarg1_);
  public final static native void JNodeWalkerVector_doAdd__SWIG_0(long jarg1, JNodeWalkerVector jarg1_, long jarg2, JNodeWalker jarg2_);
  public final static native void JNodeWalkerVector_doAdd__SWIG_1(long jarg1, JNodeWalkerVector jarg1_, int jarg2, long jarg3, JNodeWalker jarg3_);
  public final static native long JNodeWalkerVector_doRemove(long jarg1, JNodeWalkerVector jarg1_, int jarg2);
  public final static native long JNodeWalkerVector_doGet(long jarg1, JNodeWalkerVector jarg1_, int jarg2);
  public final static native long JNodeWalkerVector_doSet(long jarg1, JNodeWalkerVector jarg1_, int jarg2, long jarg3, JNodeWalker jarg3_);
  public final static native void JNodeWalkerVector_doRemoveRange(long jarg1, JNodeWalkerVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_JNodeWalkerVector(long jarg1);
  public final static native long new_JDeviceGraphNodeVector__SWIG_0();
  public final static native long new_JDeviceGraphNodeVector__SWIG_1(long jarg1, JDeviceGraphNodeVector jarg1_);
  public final static native long JDeviceGraphNodeVector_capacity(long jarg1, JDeviceGraphNodeVector jarg1_);
  public final static native void JDeviceGraphNodeVector_reserve(long jarg1, JDeviceGraphNodeVector jarg1_, long jarg2);
  public final static native boolean JDeviceGraphNodeVector_isEmpty(long jarg1, JDeviceGraphNodeVector jarg1_);
  public final static native void JDeviceGraphNodeVector_clear(long jarg1, JDeviceGraphNodeVector jarg1_);
  public final static native long new_JDeviceGraphNodeVector__SWIG_2(int jarg1, long jarg2, JDeviceGraphNode jarg2_);
  public final static native int JDeviceGraphNodeVector_doSize(long jarg1, JDeviceGraphNodeVector jarg1_);
  public final static native void JDeviceGraphNodeVector_doAdd__SWIG_0(long jarg1, JDeviceGraphNodeVector jarg1_, long jarg2, JDeviceGraphNode jarg2_);
  public final static native void JDeviceGraphNodeVector_doAdd__SWIG_1(long jarg1, JDeviceGraphNodeVector jarg1_, int jarg2, long jarg3, JDeviceGraphNode jarg3_);
  public final static native long JDeviceGraphNodeVector_doRemove(long jarg1, JDeviceGraphNodeVector jarg1_, int jarg2);
  public final static native long JDeviceGraphNodeVector_doGet(long jarg1, JDeviceGraphNodeVector jarg1_, int jarg2);
  public final static native long JDeviceGraphNodeVector_doSet(long jarg1, JDeviceGraphNodeVector jarg1_, int jarg2, long jarg3, JDeviceGraphNode jarg3_);
  public final static native void JDeviceGraphNodeVector_doRemoveRange(long jarg1, JDeviceGraphNodeVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_JDeviceGraphNodeVector(long jarg1);
  public final static native long RefreshDeviceMessage_SWIGSmartPtrUpcast(long jarg1);
  public final static native long ChannelUpdateDeviceMessage_SWIGSmartPtrUpcast(long jarg1);
  public final static native long AttributeUpdateMessage_SWIGSmartPtrUpcast(long jarg1);
  public final static native long EngineSchedulerMessage_SWIGSmartPtrUpcast(long jarg1);
  public final static native long EngineParserMessage_SWIGSmartPtrUpcast(long jarg1);
  public final static native long EventEngineMessage_SWIGSmartPtrUpcast(long jarg1);
  public final static native long LocalChannel_SWIGSmartPtrUpcast(long jarg1);
  public final static native long JLocalDevice_SWIGSmartPtrUpcast(long jarg1);

  public static void SwigDirector_RefreshDeviceMessageListener_handleMessage(RefreshDeviceMessageListener jself, long mess) {
    jself.handleMessage((mess == 0) ? null : new RefreshDeviceMessage(mess, true));
  }
  public static void SwigDirector_ChannelUpdateDeviceMessageListener_handleMessage(ChannelUpdateDeviceMessageListener jself, long mess) {
    jself.handleMessage((mess == 0) ? null : new ChannelUpdateDeviceMessage(mess, true));
  }
  public static void SwigDirector_AttributeUpdateMessageListener_handleMessage(AttributeUpdateMessageListener jself, long mess) {
    jself.handleMessage((mess == 0) ? null : new AttributeUpdateMessage(mess, true));
  }
  public static void SwigDirector_EngineSchedulerMessageListener_handleMessage(EngineSchedulerMessageListener jself, long mess) {
    jself.handleMessage((mess == 0) ? null : new EngineSchedulerMessage(mess, true));
  }
  public static void SwigDirector_EngineParserMessageListener_handleMessage(EngineParserMessageListener jself, long mess) {
    jself.handleMessage((mess == 0) ? null : new EngineParserMessage(mess, true));
  }
  public static void SwigDirector_EventEngineMessageListener_handleMessage(EventEngineMessageListener jself, long mess) {
    jself.handleMessage((mess == 0) ? null : new EventEngineMessage(mess, true));
  }
  public static short SwigDirector_Channel_getChannelNumber(Channel jself) {
    return jself.getChannelNumber();
  }
  public static int SwigDirector_Channel_getType(Channel jself) {
    return (jself.getType()).swigValue();
  }
  public static int SwigDirector_Channel_getInputType(Channel jself) {
    return (jself.getInputType()).swigValue();
  }
  public static int SwigDirector_Channel_getOutputType(Channel jself) {
    return (jself.getOutputType()).swigValue();
  }
  public static void SwigDirector_Channel_setChannelName(Channel jself, String name) {
    jself.setChannelName(name);
  }
  public static String SwigDirector_Channel_getChannelName(Channel jself) {
    return jself.getChannelName();
  }
  public static void SwigDirector_Channel_saveLastValue(Channel jself, long value) {
    jself.saveLastValue(new MixedValue(value, false));
  }
  public static long SwigDirector_Channel_getLastValue(Channel jself) {
    return MixedValue.getCPtr(jself.getLastValue());
  }
  public static long SwigDirector_Channel_getMetaData__SWIG_0(Channel jself) {
    return MixedValue.getCPtr(jself.getMetaData());
  }
  public static long SwigDirector_Channel_getMetaData__SWIG_1(Channel jself, String key) {
    return MixedValue.getCPtr(jself.getMetaData(key));
  }
  public static short SwigDirector_LocalChannel_getChannelNumber(LocalChannel jself) {
    return jself.getChannelNumber();
  }
  public static int SwigDirector_LocalChannel_getType(LocalChannel jself) {
    return (jself.getType()).swigValue();
  }
  public static int SwigDirector_LocalChannel_getInputType(LocalChannel jself) {
    return (jself.getInputType()).swigValue();
  }
  public static int SwigDirector_LocalChannel_getOutputType(LocalChannel jself) {
    return (jself.getOutputType()).swigValue();
  }
  public static void SwigDirector_LocalChannel_setChannelName(LocalChannel jself, String name) {
    jself.setChannelName(name);
  }
  public static String SwigDirector_LocalChannel_getChannelName(LocalChannel jself) {
    return jself.getChannelName();
  }
  public static void SwigDirector_LocalChannel_saveLastValue(LocalChannel jself, long value) {
    jself.saveLastValue(new MixedValue(value, false));
  }
  public static long SwigDirector_LocalChannel_getLastValue(LocalChannel jself) {
    return MixedValue.getCPtr(jself.getLastValue());
  }
  public static long SwigDirector_LocalChannel_getMetaData__SWIG_0(LocalChannel jself) {
    return MixedValue.getCPtr(jself.getMetaData());
  }
  public static long SwigDirector_LocalChannel_getMetaData__SWIG_1(LocalChannel jself, String key) {
    return MixedValue.getCPtr(jself.getMetaData(key));
  }
  public static void SwigDirector_JLocalDevice_parseEvents(JLocalDevice jself, int temp) {
    jself.parseEvents(temp);
  }
  public static void SwigDirector_ParsedShot_getEvents(ParsedShot jself, long ets) {
    jself.getEvents((ets == 0) ? null : new RawEventVector(ets, true));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
