/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class STIParsingMessage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected STIParsingMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(STIParsingMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_STIParsingMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId_code(long value) {
    stiJNI.STIParsingMessage_id_code_set(swigCPtr, this, value);
  }

  public long getId_code() {
    return stiJNI.STIParsingMessage_id_code_get(swigCPtr, this);
  }

  public void setName(String value) {
    stiJNI.STIParsingMessage_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return stiJNI.STIParsingMessage_name_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    stiJNI.STIParsingMessage_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return stiJNI.STIParsingMessage_message_get(swigCPtr, this);
  }

  public void setEvents(RawEventVector value) {
    stiJNI.STIParsingMessage_events_set(swigCPtr, this, RawEventVector.getCPtr(value), value);
  }

  public RawEventVector getEvents() {
    long cPtr = stiJNI.STIParsingMessage_events_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RawEventVector(cPtr, true);
  }

  public STIParsingMessage() {
    this(stiJNI.new_STIParsingMessage(), true);
  }

  public final static class ParserMessageType {
    public final static STIParsingMessage.ParserMessageType Error = new STIParsingMessage.ParserMessageType("Error");
    public final static STIParsingMessage.ParserMessageType Warning = new STIParsingMessage.ParserMessageType("Warning");
    public final static STIParsingMessage.ParserMessageType Information = new STIParsingMessage.ParserMessageType("Information");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ParserMessageType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ParserMessageType.class + " with value " + swigValue);
    }

    private ParserMessageType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ParserMessageType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ParserMessageType(String swigName, ParserMessageType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ParserMessageType[] swigValues = { Error, Warning, Information };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
