/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class TimeStamp {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TimeStamp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TimeStamp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_TimeStamp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTimestamp(double value) {
    stiJNI.TimeStamp_timestamp_set(swigCPtr, this, value);
  }

  public double getTimestamp() {
    return stiJNI.TimeStamp_timestamp_get(swigCPtr, this);
  }

  public String print() {
    return stiJNI.TimeStamp_print(swigCPtr, this);
  }

  public boolean opLess(TimeStamp rhs) {
    return stiJNI.TimeStamp_opLess(swigCPtr, this, TimeStamp.getCPtr(rhs), rhs);
  }

  public boolean opEquals(TimeStamp rhs) {
    return stiJNI.TimeStamp_opEquals(swigCPtr, this, TimeStamp.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(TimeStamp rhs) {
    return stiJNI.TimeStamp_opNotEquals(swigCPtr, this, TimeStamp.getCPtr(rhs), rhs);
  }

  public TimeStamp() {
    this(stiJNI.new_TimeStamp(), true);
  }

}
