#ifndef STI_ENGINE_DEVICEEVENTPARSER_H
#define STI_ENGINE_DEVICEEVENTPARSER_H

#include <sti/fwd/RawEvent_fwd.h>
#include <sti/fwd/SynchronousEvent_fwd.h>
#include <sti/fwd/DeviceID_fwd.h>
#include <sti/engine/EngineID.h>
#include <sti/device/DeviceID.h>


#include <set>
#include <mutex>
#include <vector>

namespace STI
{
namespace Engine
{

class EngineID;
class EngineParsingMessage;

//Mixin class that enables device parsing.  The device must implement this interface in order
//for the EventEngineParser to delegate to the parseDeviceEvents defined by the device.
//DeviceEventParser also includes an event target.  Device generated events are added by calling addEvent,
//which appends the events to the targeted partner event list for the engine.

class DeviceEventParser
{
public:

	DeviceEventParser();
	virtual ~DeviceEventParser() {}
	
	virtual bool isEventTarget(const STI::Device::DeviceID& id) = 0;
	virtual void getEventTargets(std::set<STI::Device::DeviceID>& targetIDs) = 0;

	void parseEvents(const STI::Engine::RawEventMap& events, SynchronousEventVector& synchedEvents, STI::Device::DeviceID deviceID, const STI::Engine::EngineID& engineID, DeviceEventMap* target);

	//void push_error();	//should throw instead
	EngineParsingMessage& addInfo(unsigned id, const std::string& name);
	EngineParsingMessage& addWarning(unsigned id, const std::string& name);

	//evt is the event generated by the device
	//referenceEvent is the event that prompted the creation of the device generated event.
	void addEvent(const RawEvent& evt, const RawEvent& referenceEvent);

	const EngineID& getCurrentEngineID() const { return currentEngineID; }

	std::vector<EngineParsingMessage>& getParsingMessages() { return parsingMessages; }

private:

	virtual void parseEvents(const STI::Engine::RawEventMap& events, SynchronousEventVector& synchedEvents) = 0;

	void setPartnerEventTarget(DeviceEventMap* target);
	void clearEventNumber();

	void clearWarnings();

	STI::Device::DeviceID localDeviceID;
	EngineID currentEngineID;
	DeviceEventMap* partnerEventTarget;
	unsigned eventNumber;

	std::vector<EngineParsingMessage> parsingMessages;

	bool parsing;

	mutable std::mutex parseMutex;
};


} //Engine
} //STI

#endif
