/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JDeviceEventReceiver {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected JDeviceEventReceiver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JDeviceEventReceiver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JDeviceEventReceiver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JDeviceEventReceiver(SWIGTYPE_p_std__shared_ptrT_STI__Device__DeviceEventReceiver_t receiver) {
    this(stiJNI.new_JDeviceEventReceiver(SWIGTYPE_p_std__shared_ptrT_STI__Device__DeviceEventReceiver_t.getCPtr(receiver)), true);
  }

  public void addListener(DeviceID sourceDeviceID, DeviceEventListenerID listenerID, RefreshDeviceEventListener listener) {
    stiJNI.JDeviceEventReceiver_addListener__SWIG_0(swigCPtr, this, DeviceID.getCPtr(sourceDeviceID), sourceDeviceID, DeviceEventListenerID.getCPtr(listenerID), listenerID, RefreshDeviceEventListener.getCPtr(listener), listener);
  }

  public void addListener(DeviceID sourceDeviceID, DeviceEventListenerID listenerID, ChannelUpdateDeviceEventListener listener) {
    stiJNI.JDeviceEventReceiver_addListener__SWIG_1(swigCPtr, this, DeviceID.getCPtr(sourceDeviceID), sourceDeviceID, DeviceEventListenerID.getCPtr(listenerID), listenerID, ChannelUpdateDeviceEventListener.getCPtr(listener), listener);
  }

  public void removeListener(DeviceID sourceDeviceID, DeviceEventListenerID listenerID) {
    stiJNI.JDeviceEventReceiver_removeListener(swigCPtr, this, DeviceID.getCPtr(sourceDeviceID), sourceDeviceID, DeviceEventListenerID.getCPtr(listenerID), listenerID);
  }

}
