/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class AddSequenceStatus {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AddSequenceStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AddSequenceStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_AddSequenceStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStatus(EngineJobStatus value) {
    stiJNI.AddSequenceStatus_status_set(swigCPtr, this, value.swigValue());
  }

  public EngineJobStatus getStatus() {
    return EngineJobStatus.swigToEnum(stiJNI.AddSequenceStatus_status_get(swigCPtr, this));
  }

  public void setSeqid(SequenceID value) {
    stiJNI.AddSequenceStatus_seqid_set(swigCPtr, this, SequenceID.getCPtr(value), value);
  }

  public SequenceID getSeqid() {
    long cPtr = stiJNI.AddSequenceStatus_seqid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SequenceID(cPtr, false);
  }

  public AddSequenceStatus() {
    this(stiJNI.new_AddSequenceStatus(), true);
  }

}
