/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class CompressedStackTrace {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CompressedStackTrace(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CompressedStackTrace obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_CompressedStackTrace(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CompressedStackTrace() {
    this(stiJNI.new_CompressedStackTrace(), true);
  }

  public void appendFrame(long file, long line, long func) {
    stiJNI.CompressedStackTrace_appendFrame__SWIG_0(swigCPtr, this, file, line, func);
  }

  public void appendFrame(CompressedStackFrame frame) {
    stiJNI.CompressedStackTrace_appendFrame__SWIG_1(swigCPtr, this, CompressedStackFrame.getCPtr(frame), frame);
  }

  public CompressedStackFrameVector getFrames() {
    return new CompressedStackFrameVector(stiJNI.CompressedStackTrace_getFrames(swigCPtr, this), true);
  }

}
