/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class DeviceLogRecordMap extends java.util.AbstractMap<String, DeviceLogRecord> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DeviceLogRecordMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeviceLogRecordMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_DeviceLogRecordMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public DeviceLogRecord get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public DeviceLogRecord put(String key, DeviceLogRecord value) {
    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      DeviceLogRecord oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public DeviceLogRecord remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      DeviceLogRecord oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, DeviceLogRecord>> entrySet() {
    java.util.Set<Entry<String, DeviceLogRecord>> setToReturn =
        new java.util.HashSet<Entry<String, DeviceLogRecord>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, DeviceLogRecord>() {
        private Iterator iterator;

        private Entry<String, DeviceLogRecord> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public DeviceLogRecord getValue() {
          return iterator.getValue();
        }

        public DeviceLogRecord setValue(DeviceLogRecord newValue) {
          DeviceLogRecord oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public DeviceLogRecordMap() {
    this(stiJNI.new_DeviceLogRecordMap__SWIG_0(), true);
  }

  public DeviceLogRecordMap(DeviceLogRecordMap other) {
    this(stiJNI.new_DeviceLogRecordMap__SWIG_1(DeviceLogRecordMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stiJNI.delete_DeviceLogRecordMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private DeviceLogRecordMap.Iterator getNextUnchecked() {
      return new DeviceLogRecordMap.Iterator(stiJNI.DeviceLogRecordMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(DeviceLogRecordMap.Iterator other) {
      return stiJNI.DeviceLogRecordMap_Iterator_isNot(swigCPtr, this, DeviceLogRecordMap.Iterator.getCPtr(other), other);
    }
  
    private String getKey() {
      return stiJNI.DeviceLogRecordMap_Iterator_getKey(swigCPtr, this);
    }
  
    private DeviceLogRecord getValue() {
      return new DeviceLogRecord(stiJNI.DeviceLogRecordMap_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(DeviceLogRecord newValue) {
      stiJNI.DeviceLogRecordMap_Iterator_setValue(swigCPtr, this, DeviceLogRecord.getCPtr(newValue), newValue);
    }
  
  }

  public boolean isEmpty() {
    return stiJNI.DeviceLogRecordMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.DeviceLogRecordMap_clear(swigCPtr, this);
  }

  private DeviceLogRecordMap.Iterator find(String key) {
    return new DeviceLogRecordMap.Iterator(stiJNI.DeviceLogRecordMap_find(swigCPtr, this, key), true);
  }

  private DeviceLogRecordMap.Iterator begin() {
    return new DeviceLogRecordMap.Iterator(stiJNI.DeviceLogRecordMap_begin(swigCPtr, this), true);
  }

  private DeviceLogRecordMap.Iterator end() {
    return new DeviceLogRecordMap.Iterator(stiJNI.DeviceLogRecordMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return stiJNI.DeviceLogRecordMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return stiJNI.DeviceLogRecordMap_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, DeviceLogRecord value) {
    stiJNI.DeviceLogRecordMap_putUnchecked(swigCPtr, this, key, DeviceLogRecord.getCPtr(value), value);
  }

  private void removeUnchecked(DeviceLogRecordMap.Iterator itr) {
    stiJNI.DeviceLogRecordMap_removeUnchecked(swigCPtr, this, DeviceLogRecordMap.Iterator.getCPtr(itr), itr);
  }

}
