/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class DeviceMessageListenerID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DeviceMessageListenerID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeviceMessageListenerID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_DeviceMessageListenerID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DeviceMessageListenerID() {
    this(stiJNI.new_DeviceMessageListenerID__SWIG_0(), true);
  }

  public DeviceMessageListenerID(DeviceMessageType type, String name) {
    this(stiJNI.new_DeviceMessageListenerID__SWIG_1(type.swigValue(), name), true);
  }

  public void setType(DeviceMessageType value) {
    stiJNI.DeviceMessageListenerID_type_set(swigCPtr, this, value.swigValue());
  }

  public DeviceMessageType getType() {
    return DeviceMessageType.swigToEnum(stiJNI.DeviceMessageListenerID_type_get(swigCPtr, this));
  }

  public void setName(String value) {
    stiJNI.DeviceMessageListenerID_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return stiJNI.DeviceMessageListenerID_name_get(swigCPtr, this);
  }

  public boolean opLess(DeviceMessageListenerID rhs) {
    return stiJNI.DeviceMessageListenerID_opLess(swigCPtr, this, DeviceMessageListenerID.getCPtr(rhs), rhs);
  }

  public boolean opEquals(DeviceMessageListenerID rhs) {
    return stiJNI.DeviceMessageListenerID_opEquals(swigCPtr, this, DeviceMessageListenerID.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(DeviceMessageListenerID rhs) {
    return stiJNI.DeviceMessageListenerID_opNotEquals(swigCPtr, this, DeviceMessageListenerID.getCPtr(rhs), rhs);
  }

}
