/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class DeviceID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DeviceID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeviceID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_DeviceID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DeviceID() {
    this(stiJNI.new_DeviceID__SWIG_0(), true);
  }

  public DeviceID(String deviceIDin) {
    this(stiJNI.new_DeviceID__SWIG_1(deviceIDin), true);
  }

  public DeviceID(String name, String address, int module) {
    this(stiJNI.new_DeviceID__SWIG_2(name, address, module), true);
  }

  public DeviceID(String name, String address, int module, String targetServerID) {
    this(stiJNI.new_DeviceID__SWIG_3(name, address, module, targetServerID), true);
  }

  public boolean opLess(DeviceID rhs) {
    return stiJNI.DeviceID_opLess(swigCPtr, this, DeviceID.getCPtr(rhs), rhs);
  }

  public boolean opEquals(DeviceID rhs) {
    return stiJNI.DeviceID_opEquals(swigCPtr, this, DeviceID.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(DeviceID rhs) {
    return stiJNI.DeviceID_opNotEquals(swigCPtr, this, DeviceID.getCPtr(rhs), rhs);
  }

  public String getName() {
    return stiJNI.DeviceID_getName(swigCPtr, this);
  }

  public String getAddress() {
    return stiJNI.DeviceID_getAddress(swigCPtr, this);
  }

  public int getModule() {
    return stiJNI.DeviceID_getModule(swigCPtr, this);
  }

  public String getID() {
    return stiJNI.DeviceID_getID(swigCPtr, this);
  }

  public String getTargetServerID() {
    return stiJNI.DeviceID_getTargetServerID(swigCPtr, this);
  }

  public static boolean stringToDeviceID(String deviceIDin, DeviceID deviceIDout) {
    return stiJNI.DeviceID_stringToDeviceID(deviceIDin, DeviceID.getCPtr(deviceIDout), deviceIDout);
  }

  public static String generateID(String name, String address, int module) {
    return stiJNI.DeviceID_generateID(name, address, module);
  }

  public static String generateContext(DeviceID deviceID) {
    return stiJNI.DeviceID_generateContext(DeviceID.getCPtr(deviceID), deviceID);
  }

}
