/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public final class EngineJobUpdateTarget {
  public final static EngineJobUpdateTarget Queued = new EngineJobUpdateTarget("Queued");
  public final static EngineJobUpdateTarget Running = new EngineJobUpdateTarget("Running");
  public final static EngineJobUpdateTarget Completed = new EngineJobUpdateTarget("Completed");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EngineJobUpdateTarget swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EngineJobUpdateTarget.class + " with value " + swigValue);
  }

  private EngineJobUpdateTarget(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EngineJobUpdateTarget(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EngineJobUpdateTarget(String swigName, EngineJobUpdateTarget swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EngineJobUpdateTarget[] swigValues = { Queued, Running, Completed };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

