/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public final class EngineState {
  public final static EngineState Idle = new EngineState("Idle");
  public final static EngineState Parsing = new EngineState("Parsing");
  public final static EngineState Parsed = new EngineState("Parsed");
  public final static EngineState PreparingPlay = new EngineState("PreparingPlay");
  public final static EngineState PlayReady = new EngineState("PlayReady");
  public final static EngineState WaitingForTrigger = new EngineState("WaitingForTrigger");
  public final static EngineState Playing = new EngineState("Playing");
  public final static EngineState Paused = new EngineState("Paused");
  public final static EngineState Unknown = new EngineState("Unknown");
  public final static EngineState Missing = new EngineState("Missing");
  public final static EngineState Error = new EngineState("Error");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EngineState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EngineState.class + " with value " + swigValue);
  }

  private EngineState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EngineState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EngineState(String swigName, EngineState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EngineState[] swigValues = { Idle, Parsing, Parsed, PreparingPlay, PlayReady, WaitingForTrigger, Playing, Paused, Unknown, Missing, Error };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

