/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class EngineParserMessageVector extends java.util.AbstractList<EngineParsingMessage> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EngineParserMessageVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineParserMessageVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_EngineParserMessageVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EngineParserMessageVector(EngineParsingMessage[] initialElements) {
    this();
    reserve(initialElements.length);

    for (EngineParsingMessage element : initialElements) {
      add(element);
    }
  }

  public EngineParserMessageVector(Iterable<EngineParsingMessage> initialElements) {
    this();
    for (EngineParsingMessage element : initialElements) {
      add(element);
    }
  }

  public EngineParsingMessage get(int index) {
    return doGet(index);
  }

  public EngineParsingMessage set(int index, EngineParsingMessage e) {
    return doSet(index, e);
  }

  public boolean add(EngineParsingMessage e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, EngineParsingMessage e) {
    modCount++;
    doAdd(index, e);
  }

  public EngineParsingMessage remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public EngineParserMessageVector() {
    this(stiJNI.new_EngineParserMessageVector__SWIG_0(), true);
  }

  public EngineParserMessageVector(EngineParserMessageVector other) {
    this(stiJNI.new_EngineParserMessageVector__SWIG_1(EngineParserMessageVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return stiJNI.EngineParserMessageVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    stiJNI.EngineParserMessageVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return stiJNI.EngineParserMessageVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.EngineParserMessageVector_clear(swigCPtr, this);
  }

  public EngineParserMessageVector(int count, EngineParsingMessage value) {
    this(stiJNI.new_EngineParserMessageVector__SWIG_2(count, EngineParsingMessage.getCPtr(value), value), true);
  }

  private int doSize() {
    return stiJNI.EngineParserMessageVector_doSize(swigCPtr, this);
  }

  private void doAdd(EngineParsingMessage x) {
    stiJNI.EngineParserMessageVector_doAdd__SWIG_0(swigCPtr, this, EngineParsingMessage.getCPtr(x), x);
  }

  private void doAdd(int index, EngineParsingMessage x) {
    stiJNI.EngineParserMessageVector_doAdd__SWIG_1(swigCPtr, this, index, EngineParsingMessage.getCPtr(x), x);
  }

  private EngineParsingMessage doRemove(int index) {
    return new EngineParsingMessage(stiJNI.EngineParserMessageVector_doRemove(swigCPtr, this, index), true);
  }

  private EngineParsingMessage doGet(int index) {
    return new EngineParsingMessage(stiJNI.EngineParserMessageVector_doGet(swigCPtr, this, index), false);
  }

  private EngineParsingMessage doSet(int index, EngineParsingMessage val) {
    return new EngineParsingMessage(stiJNI.EngineParserMessageVector_doSet(swigCPtr, this, index, EngineParsingMessage.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    stiJNI.EngineParserMessageVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
