/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class EngineIDtoStateMap extends java.util.AbstractMap<EngineID, EngineState> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EngineIDtoStateMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineIDtoStateMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_EngineIDtoStateMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof EngineID)) {
      return false;
    }

    return containsImpl((EngineID)key);
  }

  public EngineState get(java.lang.Object key) {
    if (!(key instanceof EngineID)) {
      return null;
    }

    Iterator itr = find((EngineID) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public EngineState put(EngineID key, EngineState value) {
    Iterator itr = find((EngineID) key);
    if (itr.isNot(end())) {
      EngineState oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public EngineState remove(java.lang.Object key) {
    if (!(key instanceof EngineID)) {
      return null;
    }

    Iterator itr = find((EngineID) key);
    if (itr.isNot(end())) {
      EngineState oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<EngineID, EngineState>> entrySet() {
    java.util.Set<Entry<EngineID, EngineState>> setToReturn =
        new java.util.HashSet<Entry<EngineID, EngineState>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<EngineID, EngineState>() {
        private Iterator iterator;

        private Entry<EngineID, EngineState> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public EngineID getKey() {
          return iterator.getKey();
        }

        public EngineState getValue() {
          return iterator.getValue();
        }

        public EngineState setValue(EngineState newValue) {
          EngineState oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public EngineIDtoStateMap() {
    this(stiJNI.new_EngineIDtoStateMap__SWIG_0(), true);
  }

  public EngineIDtoStateMap(EngineIDtoStateMap other) {
    this(stiJNI.new_EngineIDtoStateMap__SWIG_1(EngineIDtoStateMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stiJNI.delete_EngineIDtoStateMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private EngineIDtoStateMap.Iterator getNextUnchecked() {
      return new EngineIDtoStateMap.Iterator(stiJNI.EngineIDtoStateMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(EngineIDtoStateMap.Iterator other) {
      return stiJNI.EngineIDtoStateMap_Iterator_isNot(swigCPtr, this, EngineIDtoStateMap.Iterator.getCPtr(other), other);
    }
  
    private EngineID getKey() {
      return new EngineID(stiJNI.EngineIDtoStateMap_Iterator_getKey(swigCPtr, this), true);
    }
  
    private EngineState getValue() {
      return EngineState.swigToEnum(stiJNI.EngineIDtoStateMap_Iterator_getValue(swigCPtr, this));
    }
  
    private void setValue(EngineState newValue) {
      stiJNI.EngineIDtoStateMap_Iterator_setValue(swigCPtr, this, newValue.swigValue());
    }
  
  }

  public boolean isEmpty() {
    return stiJNI.EngineIDtoStateMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.EngineIDtoStateMap_clear(swigCPtr, this);
  }

  private EngineIDtoStateMap.Iterator find(EngineID key) {
    return new EngineIDtoStateMap.Iterator(stiJNI.EngineIDtoStateMap_find(swigCPtr, this, EngineID.getCPtr(key), key), true);
  }

  private EngineIDtoStateMap.Iterator begin() {
    return new EngineIDtoStateMap.Iterator(stiJNI.EngineIDtoStateMap_begin(swigCPtr, this), true);
  }

  private EngineIDtoStateMap.Iterator end() {
    return new EngineIDtoStateMap.Iterator(stiJNI.EngineIDtoStateMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return stiJNI.EngineIDtoStateMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(EngineID key) {
    return stiJNI.EngineIDtoStateMap_containsImpl(swigCPtr, this, EngineID.getCPtr(key), key);
  }

  private void putUnchecked(EngineID key, EngineState value) {
    stiJNI.EngineIDtoStateMap_putUnchecked(swigCPtr, this, EngineID.getCPtr(key), key, value.swigValue());
  }

  private void removeUnchecked(EngineIDtoStateMap.Iterator itr) {
    stiJNI.EngineIDtoStateMap_removeUnchecked(swigCPtr, this, EngineIDtoStateMap.Iterator.getCPtr(itr), itr);
  }

}
