/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class EventStackTrace {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventStackTrace(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventStackTrace obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_EventStackTrace(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String file() {
    return stiJNI.EventStackTrace_file(swigCPtr, this);
  }

  public int line() {
    return stiJNI.EventStackTrace_line(swigCPtr, this);
  }

  public String print(String indent) {
    return stiJNI.EventStackTrace_print__SWIG_0(swigCPtr, this, indent);
  }

  public String print() {
    return stiJNI.EventStackTrace_print__SWIG_1(swigCPtr, this);
  }

  public EventStackTrace() {
    this(stiJNI.new_EventStackTrace(), true);
  }

}
