/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class FileHolderVector extends java.util.AbstractList<FileHolder> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FileHolderVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileHolderVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_FileHolderVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FileHolderVector(FileHolder[] initialElements) {
    this();
    reserve(initialElements.length);

    for (FileHolder element : initialElements) {
      add(element);
    }
  }

  public FileHolderVector(Iterable<FileHolder> initialElements) {
    this();
    for (FileHolder element : initialElements) {
      add(element);
    }
  }

  public FileHolder get(int index) {
    return doGet(index);
  }

  public FileHolder set(int index, FileHolder e) {
    return doSet(index, e);
  }

  public boolean add(FileHolder e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, FileHolder e) {
    modCount++;
    doAdd(index, e);
  }

  public FileHolder remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public FileHolderVector() {
    this(stiJNI.new_FileHolderVector__SWIG_0(), true);
  }

  public FileHolderVector(FileHolderVector other) {
    this(stiJNI.new_FileHolderVector__SWIG_1(FileHolderVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return stiJNI.FileHolderVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    stiJNI.FileHolderVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return stiJNI.FileHolderVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.FileHolderVector_clear(swigCPtr, this);
  }

  public FileHolderVector(int count, FileHolder value) {
    this(stiJNI.new_FileHolderVector__SWIG_2(count, FileHolder.getCPtr(value), value), true);
  }

  private int doSize() {
    return stiJNI.FileHolderVector_doSize(swigCPtr, this);
  }

  private void doAdd(FileHolder x) {
    stiJNI.FileHolderVector_doAdd__SWIG_0(swigCPtr, this, FileHolder.getCPtr(x), x);
  }

  private void doAdd(int index, FileHolder x) {
    stiJNI.FileHolderVector_doAdd__SWIG_1(swigCPtr, this, index, FileHolder.getCPtr(x), x);
  }

  private FileHolder doRemove(int index) {
    long cPtr = stiJNI.FileHolderVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new FileHolder(cPtr, true);
  }

  private FileHolder doGet(int index) {
    long cPtr = stiJNI.FileHolderVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new FileHolder(cPtr, true);
  }

  private FileHolder doSet(int index, FileHolder val) {
    long cPtr = stiJNI.FileHolderVector_doSet(swigCPtr, this, index, FileHolder.getCPtr(val), val);
    return (cPtr == 0) ? null : new FileHolder(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    stiJNI.FileHolderVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
