/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class FileIDVector extends java.util.AbstractList<FileID> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FileIDVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileIDVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_FileIDVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FileIDVector(FileID[] initialElements) {
    this();
    reserve(initialElements.length);

    for (FileID element : initialElements) {
      add(element);
    }
  }

  public FileIDVector(Iterable<FileID> initialElements) {
    this();
    for (FileID element : initialElements) {
      add(element);
    }
  }

  public FileID get(int index) {
    return doGet(index);
  }

  public FileID set(int index, FileID e) {
    return doSet(index, e);
  }

  public boolean add(FileID e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, FileID e) {
    modCount++;
    doAdd(index, e);
  }

  public FileID remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public FileIDVector() {
    this(stiJNI.new_FileIDVector__SWIG_0(), true);
  }

  public FileIDVector(FileIDVector other) {
    this(stiJNI.new_FileIDVector__SWIG_1(FileIDVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return stiJNI.FileIDVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    stiJNI.FileIDVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return stiJNI.FileIDVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.FileIDVector_clear(swigCPtr, this);
  }

  public FileIDVector(int count, FileID value) {
    this(stiJNI.new_FileIDVector__SWIG_2(count, FileID.getCPtr(value), value), true);
  }

  private int doSize() {
    return stiJNI.FileIDVector_doSize(swigCPtr, this);
  }

  private void doAdd(FileID x) {
    stiJNI.FileIDVector_doAdd__SWIG_0(swigCPtr, this, FileID.getCPtr(x), x);
  }

  private void doAdd(int index, FileID x) {
    stiJNI.FileIDVector_doAdd__SWIG_1(swigCPtr, this, index, FileID.getCPtr(x), x);
  }

  private FileID doRemove(int index) {
    return new FileID(stiJNI.FileIDVector_doRemove(swigCPtr, this, index), true);
  }

  private FileID doGet(int index) {
    return new FileID(stiJNI.FileIDVector_doGet(swigCPtr, this, index), false);
  }

  private FileID doSet(int index, FileID val) {
    return new FileID(stiJNI.FileIDVector_doSet(swigCPtr, this, index, FileID.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    stiJNI.FileIDVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
