/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class FileServer {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected FileServer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileServer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_FileServer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.FileServer_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.FileServer_change_ownership(this, swigCPtr, true);
  }

  public boolean findFile(FileID fileID) {
    return stiJNI.FileServer_findFile(swigCPtr, this, FileID.getCPtr(fileID), fileID);
  }

  public int getFileSize(FileID fileID) {
    return stiJNI.FileServer_getFileSize(swigCPtr, this, FileID.getCPtr(fileID), fileID);
  }

  public boolean transferFile(FileID source, FileHolder destination, FileTransferType type) {
    return stiJNI.FileServer_transferFile(swigCPtr, this, FileID.getCPtr(source), source, FileHolder.getCPtr(destination), destination, type.swigValue());
  }

  public boolean transferFilePartial(FileID source, FileHolder destination, int offset, int lines) {
    return stiJNI.FileServer_transferFilePartial(swigCPtr, this, FileID.getCPtr(source), source, FileHolder.getCPtr(destination), destination, offset, lines);
  }

  public boolean deleteFile(FileID fileID) {
    return stiJNI.FileServer_deleteFile(swigCPtr, this, FileID.getCPtr(fileID), fileID);
  }

  public FileServer() {
    this(stiJNI.new_FileServer(), true);
    stiJNI.FileServer_director_connect(this, swigCPtr, true, true);
  }

}
