/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class Image {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Image(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Image obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_Image(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Image() {
    this(stiJNI.new_Image__SWIG_0(), true);
  }

  public Image(String filename) {
    this(stiJNI.new_Image__SWIG_1(filename), true);
  }

  public Image(String filename, ImageWriter writter) {
    this(stiJNI.new_Image__SWIG_2(filename, ImageWriter.getCPtr(writter), writter), true);
  }

  public Image makeChildImage() {
    long cPtr = stiJNI.Image_makeChildImage(swigCPtr, this);
    return (cPtr == 0) ? null : new Image(cPtr, true);
  }

  public Image setFilename(String filename) {
    return new Image(stiJNI.Image_setFilename(swigCPtr, this, filename), true);
  }

  public Image setHeight(long height) {
    return new Image(stiJNI.Image_setHeight(swigCPtr, this, height), true);
  }

  public Image setWidth(long width) {
    return new Image(stiJNI.Image_setWidth(swigCPtr, this, width), true);
  }

  public Image setMetaData(String key, MixedValue value) {
    return new Image(stiJNI.Image_setMetaData(swigCPtr, this, key, MixedValue.getCPtr(value), value), true);
  }

  public void setWriter(ImageWriter writer) {
    stiJNI.Image_setWriter(swigCPtr, this, ImageWriter.getCPtr(writer), writer);
  }

  public void setImageData(FileHolder file) {
    stiJNI.Image_setImageData__SWIG_0(swigCPtr, this, FileHolder.getCPtr(file), file);
  }

  public void setImageData(BinaryData data) {
    stiJNI.Image_setImageData__SWIG_1(swigCPtr, this, BinaryData.getCPtr(data), data);
  }

  public void setMetaData(MetaData value) {
    stiJNI.Image_metaData_set(swigCPtr, this, MetaData.getCPtr(value), value);
  }

  public MetaData getMetaData() {
    long cPtr = stiJNI.Image_metaData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MetaData(cPtr, false);
  }

  public void writeToFile(ImageWriter writer, String targetDirectory) {
    stiJNI.Image_writeToFile(swigCPtr, this, ImageWriter.getCPtr(writer), writer, targetDirectory);
  }

  public boolean getData(BinaryData data) {
    return stiJNI.Image_getData(swigCPtr, this, BinaryData.getCPtr(data), data);
  }

  public boolean getFile(FileHolder file) {
    return stiJNI.Image_getFile(swigCPtr, this, FileHolder.getCPtr(file), file);
  }

  public String getFilename() {
    return stiJNI.Image_getFilename(swigCPtr, this);
  }

  public String getExtension() {
    return stiJNI.Image_getExtension(swigCPtr, this);
  }

  public long getHeight() {
    return stiJNI.Image_getHeight(swigCPtr, this);
  }

  public long getWidth() {
    return stiJNI.Image_getWidth(swigCPtr, this);
  }

  public boolean isChild() {
    return stiJNI.Image_isChild(swigCPtr, this);
  }

  public ImageVector getChildren() {
    return new ImageVector(stiJNI.Image_getChildren(swigCPtr, this), false);
  }

  public boolean opEquals(Image other) {
    return stiJNI.Image_opEquals(swigCPtr, this, Image.getCPtr(other), other);
  }

  public boolean opNotEquals(Image other) {
    return stiJNI.Image_opNotEquals(swigCPtr, this, Image.getCPtr(other), other);
  }

}
