/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JAttributeManager {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected JAttributeManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JAttributeManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JAttributeManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getValue(String key) {
    return stiJNI.JAttributeManager_getValue(swigCPtr, this, key);
  }

  public boolean setValue(String key, String value) {
    return stiJNI.JAttributeManager_setValue(swigCPtr, this, key, value);
  }

  public Attribute getAttribute(String key) {
    long cPtr = stiJNI.JAttributeManager_getAttribute(swigCPtr, this, key);
    return (cPtr == 0) ? null : new Attribute(cPtr, true);
  }

  public AttributeVector getAttributes() {
    return new AttributeVector(stiJNI.JAttributeManager_getAttributes(swigCPtr, this), true);
  }

  public StringMap getAttributeMap() {
    return new StringMap(stiJNI.JAttributeManager_getAttributeMap(swigCPtr, this), true);
  }

}
