/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JDevice {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected JDevice(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JDevice(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.JDevice_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.JDevice_change_ownership(this, swigCPtr, true);
  }

  public JDevice(String name, String address, int module, String targetServer) {
    this(stiJNI.new_JDevice(name, address, module, targetServer), true);
    stiJNI.JDevice_director_connect(this, swigCPtr, true, true);
  }

  public DeviceID getID() {
    return new DeviceID(stiJNI.JDevice_getID(swigCPtr, this), true);
  }

  public void kill() {
    stiJNI.JDevice_kill(swigCPtr, this);
  }

  public void activate() {
    stiJNI.JDevice_activate(swigCPtr, this);
  }

  public void disable() {
    stiJNI.JDevice_disable(swigCPtr, this);
  }

  public boolean refresh() {
    return stiJNI.JDevice_refresh(swigCPtr, this);
  }

  public String getAttribute(String key) {
    return stiJNI.JDevice_getAttribute(swigCPtr, this, key);
  }

  public boolean setAttribute(String key, String value) {
    return stiJNI.JDevice_setAttribute(swigCPtr, this, key, value);
  }

  public JDeviceCollection getCollection() {
    long cPtr = stiJNI.JDevice_getCollection(swigCPtr, this);
    return (cPtr == 0) ? null : new JDeviceCollection(cPtr, true);
  }

  public JDeviceMessageDispatcher getMessageDispatcher() {
    long cPtr = stiJNI.JDevice_getMessageDispatcher(swigCPtr, this);
    return (cPtr == 0) ? null : new JDeviceMessageDispatcher(cPtr, true);
  }

  public JEventEngineScheduler getEngineScheduler() {
    long cPtr = stiJNI.JDevice_getEngineScheduler(swigCPtr, this);
    return (cPtr == 0) ? null : new JEventEngineScheduler(cPtr, true);
  }

  public JChannelManager getChannelManager() {
    long cPtr = stiJNI.JDevice_getChannelManager(swigCPtr, this);
    return (cPtr == 0) ? null : new JChannelManager(cPtr, true);
  }

  public JAttributeManager getAttributeManager() {
    long cPtr = stiJNI.JDevice_getAttributeManager(swigCPtr, this);
    return (cPtr == 0) ? null : new JAttributeManager(cPtr, true);
  }

  public JPersistenceManager getPersistenceManager() {
    long cPtr = stiJNI.JDevice_getPersistenceManager(swigCPtr, this);
    return (cPtr == 0) ? null : new JPersistenceManager(cPtr, true);
  }

  public JProfileManager getProfileManager() {
    long cPtr = stiJNI.JDevice_getProfileManager(swigCPtr, this);
    return (cPtr == 0) ? null : new JProfileManager(cPtr, true);
  }

  public JTaskManager getTaskManager() {
    long cPtr = stiJNI.JDevice_getTaskManager(swigCPtr, this);
    return (cPtr == 0) ? null : new JTaskManager(cPtr, true);
  }

  public JLogManager getLogManager() {
    long cPtr = stiJNI.JDevice_getLogManager(swigCPtr, this);
    return (cPtr == 0) ? null : new JLogManager(cPtr, true);
  }

}
