/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JNodeWalkerVector extends java.util.AbstractList<JNodeWalker> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JNodeWalkerVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JNodeWalkerVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JNodeWalkerVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JNodeWalkerVector(JNodeWalker[] initialElements) {
    this();
    reserve(initialElements.length);

    for (JNodeWalker element : initialElements) {
      add(element);
    }
  }

  public JNodeWalkerVector(Iterable<JNodeWalker> initialElements) {
    this();
    for (JNodeWalker element : initialElements) {
      add(element);
    }
  }

  public JNodeWalker get(int index) {
    return doGet(index);
  }

  public JNodeWalker set(int index, JNodeWalker e) {
    return doSet(index, e);
  }

  public boolean add(JNodeWalker e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, JNodeWalker e) {
    modCount++;
    doAdd(index, e);
  }

  public JNodeWalker remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public JNodeWalkerVector() {
    this(stiJNI.new_JNodeWalkerVector__SWIG_0(), true);
  }

  public JNodeWalkerVector(JNodeWalkerVector other) {
    this(stiJNI.new_JNodeWalkerVector__SWIG_1(JNodeWalkerVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return stiJNI.JNodeWalkerVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    stiJNI.JNodeWalkerVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return stiJNI.JNodeWalkerVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.JNodeWalkerVector_clear(swigCPtr, this);
  }

  public JNodeWalkerVector(int count, JNodeWalker value) {
    this(stiJNI.new_JNodeWalkerVector__SWIG_2(count, JNodeWalker.getCPtr(value), value), true);
  }

  private int doSize() {
    return stiJNI.JNodeWalkerVector_doSize(swigCPtr, this);
  }

  private void doAdd(JNodeWalker x) {
    stiJNI.JNodeWalkerVector_doAdd__SWIG_0(swigCPtr, this, JNodeWalker.getCPtr(x), x);
  }

  private void doAdd(int index, JNodeWalker x) {
    stiJNI.JNodeWalkerVector_doAdd__SWIG_1(swigCPtr, this, index, JNodeWalker.getCPtr(x), x);
  }

  private JNodeWalker doRemove(int index) {
    return new JNodeWalker(stiJNI.JNodeWalkerVector_doRemove(swigCPtr, this, index), true);
  }

  private JNodeWalker doGet(int index) {
    return new JNodeWalker(stiJNI.JNodeWalkerVector_doGet(swigCPtr, this, index), false);
  }

  private JNodeWalker doSet(int index, JNodeWalker val) {
    return new JNodeWalker(stiJNI.JNodeWalkerVector_doSet(swigCPtr, this, index, JNodeWalker.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    stiJNI.JNodeWalkerVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
