/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JPersistenceManager {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected JPersistenceManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JPersistenceManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JPersistenceManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ShotResult getShot(ShotID sid) {
    long cPtr = stiJNI.JPersistenceManager_getShot(swigCPtr, this, ShotID.getCPtr(sid), sid);
    return (cPtr == 0) ? null : new ShotResult(cPtr, true);
  }

  public MeasurementVector getMeasurements(ShotID sid) {
    long cPtr = stiJNI.JPersistenceManager_getMeasurements(swigCPtr, this, ShotID.getCPtr(sid), sid);
    return (cPtr == 0) ? null : new MeasurementVector(cPtr, true);
  }

}
