/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class LogFile {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LogFile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_LogFile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(LogID value) {
    stiJNI.LogFile_id_set(swigCPtr, this, LogID.getCPtr(value), value);
  }

  public LogID getId() {
    long cPtr = stiJNI.LogFile_id_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LogID(cPtr, false);
  }

  public void setType(LogFile.LogFileType value) {
    stiJNI.LogFile_type_set(swigCPtr, this, value.swigValue());
  }

  public LogFile.LogFileType getType() {
    return LogFile.LogFileType.swigToEnum(stiJNI.LogFile_type_get(swigCPtr, this));
  }

  public void setUrl(String value) {
    stiJNI.LogFile_url_set(swigCPtr, this, value);
  }

  public String getUrl() {
    return stiJNI.LogFile_url_get(swigCPtr, this);
  }

  public void setFileHolder(FileHolder value) {
    stiJNI.LogFile_fileHolder_set(swigCPtr, this, FileHolder.getCPtr(value), value);
  }

  public FileHolder getFileHolder() {
    long cPtr = stiJNI.LogFile_fileHolder_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FileHolder(cPtr, true);
  }

  public void setLogString(String value) {
    stiJNI.LogFile_logString_set(swigCPtr, this, value);
  }

  public String getLogString() {
    return stiJNI.LogFile_logString_get(swigCPtr, this);
  }

  public LogFile() {
    this(stiJNI.new_LogFile(), true);
  }

  public final static class LogFileType {
    public final static LogFile.LogFileType URL = new LogFile.LogFileType("URL");
    public final static LogFile.LogFileType FileHolder = new LogFile.LogFileType("FileHolder");
    public final static LogFile.LogFileType String = new LogFile.LogFileType("String");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static LogFileType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + LogFileType.class + " with value " + swigValue);
    }

    private LogFileType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private LogFileType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private LogFileType(String swigName, LogFileType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static LogFileType[] swigValues = { URL, FileHolder, String };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
