/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class Measurement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Measurement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Measurement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_Measurement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Measurement() {
    this(stiJNI.new_Measurement__SWIG_0(), true);
  }

  public Measurement(double time, int channel, DeviceID device, UIntVector measurementGraphPath) {
    this(stiJNI.new_Measurement__SWIG_1(time, channel, DeviceID.getCPtr(device), device, UIntVector.getCPtr(measurementGraphPath), measurementGraphPath), true);
  }

  public Measurement(RawEvent sourceEvent) {
    this(stiJNI.new_Measurement__SWIG_2(RawEvent.getCPtr(sourceEvent), sourceEvent), true);
  }

  public Measurement(Measurement measurement) {
    this(stiJNI.new_Measurement__SWIG_3(Measurement.getCPtr(measurement), measurement), true);
  }

  public void setMeasurementResult(MixedValue result) {
    stiJNI.Measurement_setMeasurementResult(swigCPtr, this, MixedValue.getCPtr(result), result);
  }

  public void extractMeasurementResult(MixedValue data) {
    stiJNI.Measurement_extractMeasurementResult(swigCPtr, this, MixedValue.getCPtr(data), data);
  }

  public boolean dataReady() {
    return stiJNI.Measurement_dataReady(swigCPtr, this);
  }

  public double time() {
    return stiJNI.Measurement_time(swigCPtr, this);
  }

  public int channel() {
    return stiJNI.Measurement_channel(swigCPtr, this);
  }

  public MixedValue data() {
    return new MixedValue(stiJNI.Measurement_data(swigCPtr, this), false);
  }

  public DeviceID device() {
    return new DeviceID(stiJNI.Measurement_device(swigCPtr, this), false);
  }

  public UIntVector getMeasurementGraphPath() {
    return new UIntVector(stiJNI.Measurement_getMeasurementGraphPath(swigCPtr, this), false);
  }

  public String print() {
    return stiJNI.Measurement_print(swigCPtr, this);
  }

  public boolean opLess(Measurement rhs) {
    return stiJNI.Measurement_opLess(swigCPtr, this, Measurement.getCPtr(rhs), rhs);
  }

  public boolean opEquals(Measurement rhs) {
    return stiJNI.Measurement_opEquals(swigCPtr, this, Measurement.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(Measurement rhs) {
    return stiJNI.Measurement_opNotEquals(swigCPtr, this, Measurement.getCPtr(rhs), rhs);
  }

}
