/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class MetaData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MetaData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MetaData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_MetaData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MetaData() {
    this(stiJNI.new_MetaData__SWIG_0(), true);
  }

  public MetaData(MixedValue data) {
    this(stiJNI.new_MetaData__SWIG_1(MixedValue.getCPtr(data), data), true);
  }

  public boolean contains(String key) {
    return stiJNI.MetaData_contains(swigCPtr, this, key);
  }

  public void addMetaData(String key, MixedValue value) {
    stiJNI.MetaData_addMetaData(swigCPtr, this, key, MixedValue.getCPtr(value), value);
  }

  public boolean resetMetaDataEntry(String key, MixedValue newValue) {
    return stiJNI.MetaData_resetMetaDataEntry(swigCPtr, this, key, MixedValue.getCPtr(newValue), newValue);
  }

  public void removeMetaData(String key) {
    stiJNI.MetaData_removeMetaData(swigCPtr, this, key);
  }

  public void clear() {
    stiJNI.MetaData_clear(swigCPtr, this);
  }

  public MixedValue getMetaData() {
    return new MixedValue(stiJNI.MetaData_getMetaData__SWIG_0(swigCPtr, this), false);
  }

  public MixedValue getMetaData(String key) {
    return new MixedValue(stiJNI.MetaData_getMetaData__SWIG_1(swigCPtr, this, key), true);
  }

  public StringVector keys() {
    return new StringVector(stiJNI.MetaData_keys(swigCPtr, this), true);
  }

  public void merge(MetaData data) {
    stiJNI.MetaData_merge(swigCPtr, this, MetaData.getCPtr(data), data);
  }

}
