/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class MixedValueTypeVector extends java.util.AbstractList<MixedValueType> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MixedValueTypeVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MixedValueTypeVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_MixedValueTypeVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MixedValueTypeVector(MixedValueType[] initialElements) {
    this();
    reserve(initialElements.length);

    for (MixedValueType element : initialElements) {
      add(element);
    }
  }

  public MixedValueTypeVector(Iterable<MixedValueType> initialElements) {
    this();
    for (MixedValueType element : initialElements) {
      add(element);
    }
  }

  public MixedValueType get(int index) {
    return doGet(index);
  }

  public MixedValueType set(int index, MixedValueType e) {
    return doSet(index, e);
  }

  public boolean add(MixedValueType e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, MixedValueType e) {
    modCount++;
    doAdd(index, e);
  }

  public MixedValueType remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public MixedValueTypeVector() {
    this(stiJNI.new_MixedValueTypeVector__SWIG_0(), true);
  }

  public MixedValueTypeVector(MixedValueTypeVector other) {
    this(stiJNI.new_MixedValueTypeVector__SWIG_1(MixedValueTypeVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return stiJNI.MixedValueTypeVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    stiJNI.MixedValueTypeVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return stiJNI.MixedValueTypeVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.MixedValueTypeVector_clear(swigCPtr, this);
  }

  public MixedValueTypeVector(int count, MixedValueType value) {
    this(stiJNI.new_MixedValueTypeVector__SWIG_2(count, value.swigValue()), true);
  }

  private int doSize() {
    return stiJNI.MixedValueTypeVector_doSize(swigCPtr, this);
  }

  private void doAdd(MixedValueType x) {
    stiJNI.MixedValueTypeVector_doAdd__SWIG_0(swigCPtr, this, x.swigValue());
  }

  private void doAdd(int index, MixedValueType x) {
    stiJNI.MixedValueTypeVector_doAdd__SWIG_1(swigCPtr, this, index, x.swigValue());
  }

  private MixedValueType doRemove(int index) {
    return MixedValueType.swigToEnum(stiJNI.MixedValueTypeVector_doRemove(swigCPtr, this, index));
  }

  private MixedValueType doGet(int index) {
    return MixedValueType.swigToEnum(stiJNI.MixedValueTypeVector_doGet(swigCPtr, this, index));
  }

  private MixedValueType doSet(int index, MixedValueType val) {
    return MixedValueType.swigToEnum(stiJNI.MixedValueTypeVector_doSet(swigCPtr, this, index, val.swigValue()));
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    stiJNI.MixedValueTypeVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
