/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class ParsedTag {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParsedTag(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParsedTag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_ParsedTag(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    stiJNI.ParsedTag_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return stiJNI.ParsedTag_name_get(swigCPtr, this);
  }

  public void setTrace(StackTrace value) {
    stiJNI.ParsedTag_trace_set(swigCPtr, this, StackTrace.getCPtr(value), value);
  }

  public StackTrace getTrace() {
    long cPtr = stiJNI.ParsedTag_trace_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StackTrace(cPtr, false);
  }

  public boolean opLess(ParsedTag rhs) {
    return stiJNI.ParsedTag_opLess(swigCPtr, this, ParsedTag.getCPtr(rhs), rhs);
  }

  public boolean opEquals(ParsedTag rhs) {
    return stiJNI.ParsedTag_opEquals(swigCPtr, this, ParsedTag.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(ParsedTag rhs) {
    return stiJNI.ParsedTag_opNotEquals(swigCPtr, this, ParsedTag.getCPtr(rhs), rhs);
  }

  public ParsedTag() {
    this(stiJNI.new_ParsedTag(), true);
  }

}
