/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class ParsedVar {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParsedVar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParsedVar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_ParsedVar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ParsedVar() {
    this(stiJNI.new_ParsedVar__SWIG_0(), true);
  }

  public ParsedVar(String name, RawEventGroup group, StackTrace trace, StackTraceData stackTraceData) {
    this(stiJNI.new_ParsedVar__SWIG_1(name, RawEventGroup.getCPtr(group), group, StackTrace.getCPtr(trace), trace, StackTraceData.getCPtr(stackTraceData), stackTraceData), true);
  }

  public ParsedVar(String name, RawEventGroup group, MixedValue value, StackTrace trace, StackTraceData stackTraceData) {
    this(stiJNI.new_ParsedVar__SWIG_2(name, RawEventGroup.getCPtr(group), group, MixedValue.getCPtr(value), value, StackTrace.getCPtr(trace), trace, StackTraceData.getCPtr(stackTraceData), stackTraceData), true);
  }

  public void setName(String value) {
    stiJNI.ParsedVar_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return stiJNI.ParsedVar_name_get(swigCPtr, this);
  }

  public void setValue(MixedValue value) {
    stiJNI.ParsedVar_value_set(swigCPtr, this, MixedValue.getCPtr(value), value);
  }

  public MixedValue getValue() {
    long cPtr = stiJNI.ParsedVar_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MixedValue(cPtr, false);
  }

  public void setTrace(StackTrace value) {
    stiJNI.ParsedVar_trace_set(swigCPtr, this, StackTrace.getCPtr(value), value);
  }

  public StackTrace getTrace() {
    long cPtr = stiJNI.ParsedVar_trace_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StackTrace(cPtr, false);
  }

  public void setStackTraceData(StackTraceData value) {
    stiJNI.ParsedVar_stackTraceData_set(swigCPtr, this, StackTraceData.getCPtr(value), value);
  }

  public StackTraceData getStackTraceData() {
    long cPtr = stiJNI.ParsedVar_stackTraceData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StackTraceData(cPtr, true);
  }

  public void setParentGroup(RawEventGroup value) {
    stiJNI.ParsedVar_parentGroup_set(swigCPtr, this, RawEventGroup.getCPtr(value), value);
  }

  public RawEventGroup getParentGroup() {
    long cPtr = stiJNI.ParsedVar_parentGroup_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RawEventGroup(cPtr, true);
  }

  public String getGroupName() {
    return stiJNI.ParsedVar_getGroupName(swigCPtr, this);
  }

  public boolean isBound() {
    return stiJNI.ParsedVar_isBound(swigCPtr, this);
  }

  public boolean opLess(ParsedVar rhs) {
    return stiJNI.ParsedVar_opLess(swigCPtr, this, ParsedVar.getCPtr(rhs), rhs);
  }

  public boolean opEquals(ParsedVar rhs) {
    return stiJNI.ParsedVar_opEquals(swigCPtr, this, ParsedVar.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(ParsedVar rhs) {
    return stiJNI.ParsedVar_opNotEquals(swigCPtr, this, ParsedVar.getCPtr(rhs), rhs);
  }

}
