/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class RawEventTarget {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RawEventTarget(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RawEventTarget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_RawEventTarget(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RawEventTarget() {
    this(stiJNI.new_RawEventTarget__SWIG_0(), true);
  }

  public RawEventTarget(RawEventTargetDevice dev, RawEventTargetChannel ch) {
    this(stiJNI.new_RawEventTarget__SWIG_1(RawEventTargetDevice.getCPtr(dev), dev, RawEventTargetChannel.getCPtr(ch), ch), true);
  }

  public RawEventTarget(DeviceID targetDevice, int channel) {
    this(stiJNI.new_RawEventTarget__SWIG_2(DeviceID.getCPtr(targetDevice), targetDevice, channel), true);
  }

  public RawEventTarget(DeviceID targetDevice, String channelName) {
    this(stiJNI.new_RawEventTarget__SWIG_3(DeviceID.getCPtr(targetDevice), targetDevice, channelName), true);
  }

  public RawEventTarget(String deviceName, int channel) {
    this(stiJNI.new_RawEventTarget__SWIG_4(deviceName, channel), true);
  }

  public RawEventTarget(String deviceName, String channelName) {
    this(stiJNI.new_RawEventTarget__SWIG_5(deviceName, channelName), true);
  }

  public RawEventTarget(String channelName) {
    this(stiJNI.new_RawEventTarget__SWIG_6(channelName), true);
  }

  public boolean isAbstract() {
    return stiJNI.RawEventTarget_isAbstract(swigCPtr, this);
  }

  public RawEventTargetDevice getDevice() {
    return new RawEventTargetDevice(stiJNI.RawEventTarget_getDevice(swigCPtr, this), false);
  }

  public RawEventTargetDevice device() {
    return new RawEventTargetDevice(stiJNI.RawEventTarget_device(swigCPtr, this), false);
  }

  public RawEventTargetChannel getChannel() {
    return new RawEventTargetChannel(stiJNI.RawEventTarget_getChannel(swigCPtr, this), false);
  }

  public RawEventTargetChannel channel() {
    return new RawEventTargetChannel(stiJNI.RawEventTarget_channel(swigCPtr, this), false);
  }

  public boolean opLess(RawEventTarget rhs) {
    return stiJNI.RawEventTarget_opLess(swigCPtr, this, RawEventTarget.getCPtr(rhs), rhs);
  }

  public boolean opEquals(RawEventTarget rhs) {
    return stiJNI.RawEventTarget_opEquals(swigCPtr, this, RawEventTarget.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(RawEventTarget rhs) {
    return stiJNI.RawEventTarget_opNotEquals(swigCPtr, this, RawEventTarget.getCPtr(rhs), rhs);
  }

}
