/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class RawEventGroup {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected RawEventGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RawEventGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_RawEventGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RawEventGroup() {
    this(stiJNI.new_RawEventGroup__SWIG_0(), true);
  }

  public RawEventGroup(String name, String parentName) {
    this(stiJNI.new_RawEventGroup__SWIG_1(name, parentName), true);
  }

  public RawEventGroup(String name, String parentName, StackTraceData traceData) {
    this(stiJNI.new_RawEventGroup__SWIG_2(name, parentName, StackTraceData.getCPtr(traceData), traceData), true);
  }

  public String getName() {
    return stiJNI.RawEventGroup_getName(swigCPtr, this);
  }

  public String getFullName() {
    return stiJNI.RawEventGroup_getFullName(swigCPtr, this);
  }

  public String getParentGroupName() {
    return stiJNI.RawEventGroup_getParentGroupName(swigCPtr, this);
  }

  public double startTime() {
    return stiJNI.RawEventGroup_startTime(swigCPtr, this);
  }

  public double endTime() {
    return stiJNI.RawEventGroup_endTime(swigCPtr, this);
  }

  public RawEventGroupStats getStats() {
    return new RawEventGroupStats(stiJNI.RawEventGroup_getStats(swigCPtr, this), true);
  }

  public RawEventGroupStats getTotalStats() {
    return new RawEventGroupStats(stiJNI.RawEventGroup_getTotalStats(swigCPtr, this), true);
  }

  public void setName(String newName) {
    stiJNI.RawEventGroup_setName(swigCPtr, this, newName);
  }

  public boolean opEquals(RawEventGroup other) {
    return stiJNI.RawEventGroup_opEquals(swigCPtr, this, RawEventGroup.getCPtr(other), other);
  }

  public boolean opLess(RawEventGroup other) {
    return stiJNI.RawEventGroup_opLess(swigCPtr, this, RawEventGroup.getCPtr(other), other);
  }

  static public class Result {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Result(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Result obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stiJNI.delete_RawEventGroup_Result(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setSuccess(boolean value) {
      stiJNI.RawEventGroup_Result_success_set(swigCPtr, this, value);
    }
  
    public boolean getSuccess() {
      return stiJNI.RawEventGroup_Result_success_get(swigCPtr, this);
    }
  
    public void setErrorMessage(String value) {
      stiJNI.RawEventGroup_Result_errorMessage_set(swigCPtr, this, value);
    }
  
    public String getErrorMessage() {
      return stiJNI.RawEventGroup_Result_errorMessage_get(swigCPtr, this);
    }
  
    public Result() {
      this(stiJNI.new_RawEventGroup_Result(), true);
    }
  
  }

  public RawEventGroup.Result addvar(String fullVarName, MixedValue value, StackTrace stackTrace) {
    return new RawEventGroup.Result(stiJNI.RawEventGroup_addvar(swigCPtr, this, fullVarName, MixedValue.getCPtr(value), value, StackTrace.getCPtr(stackTrace), stackTrace), true);
  }

  public RawEventGroup.Result addtag(String fullTagName, StackTrace stackTrace) {
    return new RawEventGroup.Result(stiJNI.RawEventGroup_addtag(swigCPtr, this, fullTagName, StackTrace.getCPtr(stackTrace), stackTrace), true);
  }

  public void addEvent(RawEvent evt) {
    stiJNI.RawEventGroup_addEvent__SWIG_0(swigCPtr, this, RawEvent.getCPtr(evt), evt);
  }

  public void addEvent(RawEvent evt, String subgroupName) {
    stiJNI.RawEventGroup_addEvent__SWIG_1(swigCPtr, this, RawEvent.getCPtr(evt), evt, subgroupName);
  }

  public void addEvent(RawEventTarget target, double time, MixedValue value, RawEventType type, StackTrace stackTrace) {
    stiJNI.RawEventGroup_addEvent__SWIG_2(swigCPtr, this, RawEventTarget.getCPtr(target), target, time, MixedValue.getCPtr(value), value, type.swigValue(), StackTrace.getCPtr(stackTrace), stackTrace);
  }

  public void addEvent(RawEventTarget target, double time, ParsedVar var, RawEventType type, StackTrace stackTrace) {
    stiJNI.RawEventGroup_addEvent__SWIG_3(swigCPtr, this, RawEventTarget.getCPtr(target), target, time, ParsedVar.getCPtr(var), var, type.swigValue(), StackTrace.getCPtr(stackTrace), stackTrace);
  }

  public void addEvent(RawEventTarget target, double time, MixedValue value, RawEventType type) {
    stiJNI.RawEventGroup_addEvent__SWIG_4(swigCPtr, this, RawEventTarget.getCPtr(target), target, time, MixedValue.getCPtr(value), value, type.swigValue());
  }

  public void addEvents(RawEventVector newEvents) {
    stiJNI.RawEventGroup_addEvents(swigCPtr, this, RawEventVector.getCPtr(newEvents), newEvents);
  }

  public ParsedVar var(String fullVarName, StackTrace stackTrace) {
    return new ParsedVar(stiJNI.RawEventGroup_var(swigCPtr, this, fullVarName, StackTrace.getCPtr(stackTrace), stackTrace), true);
  }

  public RawEventGroup.Result bindVar(String fullVarName, MixedValue value) {
    return new RawEventGroup.Result(stiJNI.RawEventGroup_bindVar__SWIG_0(swigCPtr, this, fullVarName, MixedValue.getCPtr(value), value), true);
  }

  public RawEventGroup.Result bindVar(ParsedVar overwrittenVar) {
    return new RawEventGroup.Result(stiJNI.RawEventGroup_bindVar__SWIG_1(swigCPtr, this, ParsedVar.getCPtr(overwrittenVar), overwrittenVar), true);
  }

  public RawEventGroup.Result bindVars(ParsedVarSet overwritten) {
    return new RawEventGroup.Result(stiJNI.RawEventGroup_bindVars(swigCPtr, this, ParsedVarSet.getCPtr(overwritten), overwritten), true);
  }

  public void bindTargets(RawEventTargetMap targetReplacements) {
    stiJNI.RawEventGroup_bindTargets(swigCPtr, this, RawEventTargetMap.getCPtr(targetReplacements), targetReplacements);
  }

  public void bindDeviceTargets(RawEventTargetDeviceMap targetDeviceReplacements) {
    stiJNI.RawEventGroup_bindDeviceTargets(swigCPtr, this, RawEventTargetDeviceMap.getCPtr(targetDeviceReplacements), targetDeviceReplacements);
  }

  public double getTimeOffset() {
    return stiJNI.RawEventGroup_getTimeOffset(swigCPtr, this);
  }

  public void shiftStartTimeTo(double time) {
    stiJNI.RawEventGroup_shiftStartTimeTo(swigCPtr, this, time);
  }

  public void shiftEndTimeTo(double time) {
    stiJNI.RawEventGroup_shiftEndTimeTo(swigCPtr, this, time);
  }

  public void shiftReferenceTimeTo(String refName, double time) {
    stiJNI.RawEventGroup_shiftReferenceTimeTo(swigCPtr, this, refName, time);
  }

  public void addReferencePoint(String refName, double time) {
    stiJNI.RawEventGroup_addReferencePoint(swigCPtr, this, refName, time);
  }

  public StringDoubleMap getReferencePoints() {
    return new StringDoubleMap(stiJNI.RawEventGroup_getReferencePoints(swigCPtr, this), true);
  }

  public RawEventGroup group(String groupName) {
    long cPtr = stiJNI.RawEventGroup_group(swigCPtr, this, groupName);
    return (cPtr == 0) ? null : new RawEventGroup(cPtr, true);
  }

  public RawEventGroupVector getSubgroups() {
    return new RawEventGroupVector(stiJNI.RawEventGroup_getSubgroups(swigCPtr, this), true);
  }

  public void addSubgroup(RawEventGroup subgroup) {
    stiJNI.RawEventGroup_addSubgroup(swigCPtr, this, RawEventGroup.getCPtr(subgroup), subgroup);
  }

  public void merge(RawEventGroup other) {
    stiJNI.RawEventGroup_merge(swigCPtr, this, RawEventGroup.getCPtr(other), other);
  }

  public void swapEvents(RawEventGroup other) {
    stiJNI.RawEventGroup_swapEvents(swigCPtr, this, RawEventGroup.getCPtr(other), other);
  }

  public void copyEvents(RawEventGroup other) {
    stiJNI.RawEventGroup_copyEvents(swigCPtr, this, RawEventGroup.getCPtr(other), other);
  }

  public void sortEvents() {
    stiJNI.RawEventGroup_sortEvents(swigCPtr, this);
  }

  public void clear() {
    stiJNI.RawEventGroup_clear(swigCPtr, this);
  }

  public boolean eventsEmpty() {
    return stiJNI.RawEventGroup_eventsEmpty(swigCPtr, this);
  }

  public StackTraceData getStackTraceData() {
    long cPtr = stiJNI.RawEventGroup_getStackTraceData(swigCPtr, this);
    return (cPtr == 0) ? null : new StackTraceData(cPtr, true);
  }

  public ParsedVarVector getVars() {
    return new ParsedVarVector(stiJNI.RawEventGroup_getVars(swigCPtr, this), true);
  }

  public ParsedTagVector getTags() {
    return new ParsedTagVector(stiJNI.RawEventGroup_getTags(swigCPtr, this), true);
  }

  public ParsedVarSet getOverwrittenVars() {
    return new ParsedVarSet(stiJNI.RawEventGroup_getOverwrittenVars(swigCPtr, this), true);
  }

  public void setVars(ParsedVarVector vars) {
    stiJNI.RawEventGroup_setVars(swigCPtr, this, ParsedVarVector.getCPtr(vars), vars);
  }

  public void setTags(ParsedTagVector tags) {
    stiJNI.RawEventGroup_setTags(swigCPtr, this, ParsedTagVector.getCPtr(tags), tags);
  }

  public boolean getConcreteTarget(RawEventTarget abstractTarget, RawEventTarget concreteTarget) {
    return stiJNI.RawEventGroup_getConcreteTarget(swigCPtr, this, RawEventTarget.getCPtr(abstractTarget), abstractTarget, RawEventTarget.getCPtr(concreteTarget), concreteTarget);
  }

  public RawEventGroup addMetaData(String key, MixedValue data) {
    return new RawEventGroup(stiJNI.RawEventGroup_addMetaData__SWIG_0(swigCPtr, this, key, MixedValue.getCPtr(data), data), true);
  }

  public RawEventGroup addMetaData(MetaData data) {
    return new RawEventGroup(stiJNI.RawEventGroup_addMetaData__SWIG_1(swigCPtr, this, MetaData.getCPtr(data), data), true);
  }

  public MixedValue getMetaData() {
    return new MixedValue(stiJNI.RawEventGroup_getMetaData__SWIG_0(swigCPtr, this), false);
  }

  public MixedValue getMetaData(String key) {
    return new MixedValue(stiJNI.RawEventGroup_getMetaData__SWIG_1(swigCPtr, this, key), true);
  }

  public double getReferencePoint(String refName) {
    return stiJNI.RawEventGroup_getReferencePoint(swigCPtr, this, refName);
  }

  public RawEventVector getEvents() {
    return new RawEventVector(stiJNI.RawEventGroup_getEvents(swigCPtr, this), true);
  }

}
