/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class RawEventTargetDeviceMap extends java.util.AbstractMap<String, RawEventTargetDevice> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RawEventTargetDeviceMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RawEventTargetDeviceMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_RawEventTargetDeviceMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public RawEventTargetDevice get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public RawEventTargetDevice put(String key, RawEventTargetDevice value) {
    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      RawEventTargetDevice oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public RawEventTargetDevice remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      RawEventTargetDevice oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, RawEventTargetDevice>> entrySet() {
    java.util.Set<Entry<String, RawEventTargetDevice>> setToReturn =
        new java.util.HashSet<Entry<String, RawEventTargetDevice>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, RawEventTargetDevice>() {
        private Iterator iterator;

        private Entry<String, RawEventTargetDevice> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public RawEventTargetDevice getValue() {
          return iterator.getValue();
        }

        public RawEventTargetDevice setValue(RawEventTargetDevice newValue) {
          RawEventTargetDevice oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public RawEventTargetDeviceMap() {
    this(stiJNI.new_RawEventTargetDeviceMap__SWIG_0(), true);
  }

  public RawEventTargetDeviceMap(RawEventTargetDeviceMap other) {
    this(stiJNI.new_RawEventTargetDeviceMap__SWIG_1(RawEventTargetDeviceMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stiJNI.delete_RawEventTargetDeviceMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private RawEventTargetDeviceMap.Iterator getNextUnchecked() {
      return new RawEventTargetDeviceMap.Iterator(stiJNI.RawEventTargetDeviceMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(RawEventTargetDeviceMap.Iterator other) {
      return stiJNI.RawEventTargetDeviceMap_Iterator_isNot(swigCPtr, this, RawEventTargetDeviceMap.Iterator.getCPtr(other), other);
    }
  
    private String getKey() {
      return stiJNI.RawEventTargetDeviceMap_Iterator_getKey(swigCPtr, this);
    }
  
    private RawEventTargetDevice getValue() {
      return new RawEventTargetDevice(stiJNI.RawEventTargetDeviceMap_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(RawEventTargetDevice newValue) {
      stiJNI.RawEventTargetDeviceMap_Iterator_setValue(swigCPtr, this, RawEventTargetDevice.getCPtr(newValue), newValue);
    }
  
  }

  public boolean isEmpty() {
    return stiJNI.RawEventTargetDeviceMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.RawEventTargetDeviceMap_clear(swigCPtr, this);
  }

  private RawEventTargetDeviceMap.Iterator find(String key) {
    return new RawEventTargetDeviceMap.Iterator(stiJNI.RawEventTargetDeviceMap_find(swigCPtr, this, key), true);
  }

  private RawEventTargetDeviceMap.Iterator begin() {
    return new RawEventTargetDeviceMap.Iterator(stiJNI.RawEventTargetDeviceMap_begin(swigCPtr, this), true);
  }

  private RawEventTargetDeviceMap.Iterator end() {
    return new RawEventTargetDeviceMap.Iterator(stiJNI.RawEventTargetDeviceMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return stiJNI.RawEventTargetDeviceMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return stiJNI.RawEventTargetDeviceMap_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, RawEventTargetDevice value) {
    stiJNI.RawEventTargetDeviceMap_putUnchecked(swigCPtr, this, key, RawEventTargetDevice.getCPtr(value), value);
  }

  private void removeUnchecked(RawEventTargetDeviceMap.Iterator itr) {
    stiJNI.RawEventTargetDeviceMap_removeUnchecked(swigCPtr, this, RawEventTargetDeviceMap.Iterator.getCPtr(itr), itr);
  }

}
