/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class RawEventTargetChannel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RawEventTargetChannel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RawEventTargetChannel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_RawEventTargetChannel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RawEventTargetChannel(String name) {
    this(stiJNI.new_RawEventTargetChannel__SWIG_0(name), true);
  }

  public RawEventTargetChannel(int channel) {
    this(stiJNI.new_RawEventTargetChannel__SWIG_1(channel), true);
  }

  public boolean isAbstract() {
    return stiJNI.RawEventTargetChannel_isAbstract(swigCPtr, this);
  }

  public String name() {
    return stiJNI.RawEventTargetChannel_name(swigCPtr, this);
  }

  public int channel() {
    return stiJNI.RawEventTargetChannel_channel(swigCPtr, this);
  }

  public void setChannel(int channel) {
    stiJNI.RawEventTargetChannel_setChannel(swigCPtr, this, channel);
  }

  public boolean opLess(RawEventTargetChannel rhs) {
    return stiJNI.RawEventTargetChannel_opLess(swigCPtr, this, RawEventTargetChannel.getCPtr(rhs), rhs);
  }

  public boolean opEquals(RawEventTargetChannel rhs) {
    return stiJNI.RawEventTargetChannel_opEquals(swigCPtr, this, RawEventTargetChannel.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(RawEventTargetChannel rhs) {
    return stiJNI.RawEventTargetChannel_opNotEquals(swigCPtr, this, RawEventTargetChannel.getCPtr(rhs), rhs);
  }

}
