/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class RawEventTargetMap extends java.util.AbstractMap<String, RawEventTarget> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RawEventTargetMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RawEventTargetMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_RawEventTargetMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public RawEventTarget get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public RawEventTarget put(String key, RawEventTarget value) {
    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      RawEventTarget oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public RawEventTarget remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      RawEventTarget oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, RawEventTarget>> entrySet() {
    java.util.Set<Entry<String, RawEventTarget>> setToReturn =
        new java.util.HashSet<Entry<String, RawEventTarget>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, RawEventTarget>() {
        private Iterator iterator;

        private Entry<String, RawEventTarget> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public RawEventTarget getValue() {
          return iterator.getValue();
        }

        public RawEventTarget setValue(RawEventTarget newValue) {
          RawEventTarget oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public RawEventTargetMap() {
    this(stiJNI.new_RawEventTargetMap__SWIG_0(), true);
  }

  public RawEventTargetMap(RawEventTargetMap other) {
    this(stiJNI.new_RawEventTargetMap__SWIG_1(RawEventTargetMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stiJNI.delete_RawEventTargetMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private RawEventTargetMap.Iterator getNextUnchecked() {
      return new RawEventTargetMap.Iterator(stiJNI.RawEventTargetMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(RawEventTargetMap.Iterator other) {
      return stiJNI.RawEventTargetMap_Iterator_isNot(swigCPtr, this, RawEventTargetMap.Iterator.getCPtr(other), other);
    }
  
    private String getKey() {
      return stiJNI.RawEventTargetMap_Iterator_getKey(swigCPtr, this);
    }
  
    private RawEventTarget getValue() {
      return new RawEventTarget(stiJNI.RawEventTargetMap_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(RawEventTarget newValue) {
      stiJNI.RawEventTargetMap_Iterator_setValue(swigCPtr, this, RawEventTarget.getCPtr(newValue), newValue);
    }
  
  }

  public boolean isEmpty() {
    return stiJNI.RawEventTargetMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.RawEventTargetMap_clear(swigCPtr, this);
  }

  private RawEventTargetMap.Iterator find(String key) {
    return new RawEventTargetMap.Iterator(stiJNI.RawEventTargetMap_find(swigCPtr, this, key), true);
  }

  private RawEventTargetMap.Iterator begin() {
    return new RawEventTargetMap.Iterator(stiJNI.RawEventTargetMap_begin(swigCPtr, this), true);
  }

  private RawEventTargetMap.Iterator end() {
    return new RawEventTargetMap.Iterator(stiJNI.RawEventTargetMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return stiJNI.RawEventTargetMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return stiJNI.RawEventTargetMap_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, RawEventTarget value) {
    stiJNI.RawEventTargetMap_putUnchecked(swigCPtr, this, key, RawEventTarget.getCPtr(value), value);
  }

  private void removeUnchecked(RawEventTargetMap.Iterator itr) {
    stiJNI.RawEventTargetMap_removeUnchecked(swigCPtr, this, RawEventTargetMap.Iterator.getCPtr(itr), itr);
  }

}
