/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class RawEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RawEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RawEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_RawEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RawEvent() {
    this(stiJNI.new_RawEvent__SWIG_0(), true);
  }

  public RawEvent(RawEventTarget eventTarget, double time, MixedValue value, long eventNumber, RawEventType eventType) {
    this(stiJNI.new_RawEvent__SWIG_1(RawEventTarget.getCPtr(eventTarget), eventTarget, time, MixedValue.getCPtr(value), value, eventNumber, eventType.swigValue()), true);
  }

  public RawEvent(RawEventTarget eventTarget, double time, MixedValue value, long eventNumber, RawEventType eventType, CompressedStackTrace eventStackTrace, StackTraceData stackTraceData) {
    this(stiJNI.new_RawEvent__SWIG_2(RawEventTarget.getCPtr(eventTarget), eventTarget, time, MixedValue.getCPtr(value), value, eventNumber, eventType.swigValue(), CompressedStackTrace.getCPtr(eventStackTrace), eventStackTrace, StackTraceData.getCPtr(stackTraceData), stackTraceData), true);
  }

  public RawEvent(RawEvent newEvent, RawEvent referenceEvent, long eventNumber) {
    this(stiJNI.new_RawEvent__SWIG_3(RawEvent.getCPtr(newEvent), newEvent, RawEvent.getCPtr(referenceEvent), referenceEvent, eventNumber), true);
  }

  public double time() {
    return stiJNI.RawEvent_time(swigCPtr, this);
  }

  public int channel() {
    return stiJNI.RawEvent_channel(swigCPtr, this);
  }

  public MixedValue value() {
    return new MixedValue(stiJNI.RawEvent_value(swigCPtr, this), false);
  }

  public String description() {
    return stiJNI.RawEvent_description(swigCPtr, this);
  }

  public RawEventTarget target() {
    return new RawEventTarget(stiJNI.RawEvent_target(swigCPtr, this), false);
  }

  public RawEventTarget getTarget() {
    return new RawEventTarget(stiJNI.RawEvent_getTarget(swigCPtr, this), false);
  }

  public String getGroupName() {
    return stiJNI.RawEvent_getGroupName(swigCPtr, this);
  }

  public void setParentGroup(RawEventGroup group) {
    stiJNI.RawEvent_setParentGroup(swigCPtr, this, RawEventGroup.getCPtr(group), group);
  }

  public RawEventID getEventID() {
    return new RawEventID(stiJNI.RawEvent_getEventID(swigCPtr, this), true);
  }

  public RawEventType type() {
    return RawEventType.swigToEnum(stiJNI.RawEvent_type(swigCPtr, this));
  }

  public CompressedStackTrace getCompressedStackTrace() {
    return new CompressedStackTrace(stiJNI.RawEvent_getCompressedStackTrace__SWIG_0(swigCPtr, this), false);
  }

  public void setStackTrace(CompressedStackTrace eventStackTrace) {
    stiJNI.RawEvent_setStackTrace(swigCPtr, this, CompressedStackTrace.getCPtr(eventStackTrace), eventStackTrace);
  }

  public void setStackTraceData(StackTraceData traceData) {
    stiJNI.RawEvent_setStackTraceData(swigCPtr, this, StackTraceData.getCPtr(traceData), traceData);
  }

  public StackTrace getStackTrace() {
    return new StackTrace(stiJNI.RawEvent_getStackTrace(swigCPtr, this), true);
  }

  public UIntVector getEventGraphPath() {
    return new UIntVector(stiJNI.RawEvent_getEventGraphPath(swigCPtr, this), false);
  }

  public boolean isMeasurementEvent() {
    return stiJNI.RawEvent_isMeasurementEvent(swigCPtr, this);
  }

  public boolean opLess(RawEvent rhs) {
    return stiJNI.RawEvent_opLess(swigCPtr, this, RawEvent.getCPtr(rhs), rhs);
  }

  public boolean opEquals(RawEvent rhs) {
    return stiJNI.RawEvent_opEquals(swigCPtr, this, RawEvent.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(RawEvent rhs) {
    return stiJNI.RawEvent_opNotEquals(swigCPtr, this, RawEvent.getCPtr(rhs), rhs);
  }

  public void setTime(double time) {
    stiJNI.RawEvent_setTime(swigCPtr, this, time);
  }

  public void setTarget(RawEventTarget target) {
    stiJNI.RawEvent_setTarget(swigCPtr, this, RawEventTarget.getCPtr(target), target);
  }

  public void setValue(MixedValue value) {
    stiJNI.RawEvent_setValue(swigCPtr, this, MixedValue.getCPtr(value), value);
  }

  public void setDescription(String description) {
    stiJNI.RawEvent_setDescription(swigCPtr, this, description);
  }

  public void setEventGraphPath(UIntVector pathLabel) {
    stiJNI.RawEvent_setEventGraphPath(swigCPtr, this, UIntVector.getCPtr(pathLabel), pathLabel);
  }

  public void setEventType(RawEventType eventType) {
    stiJNI.RawEvent_setEventType(swigCPtr, this, eventType.swigValue());
  }

  public String print() {
    return stiJNI.RawEvent_print(swigCPtr, this);
  }

}
