/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class RawStackFrame {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RawStackFrame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RawStackFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_RawStackFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RawStackFrame() {
    this(stiJNI.new_RawStackFrame__SWIG_0(), true);
  }

  public RawStackFrame(String file, long line, String func) {
    this(stiJNI.new_RawStackFrame__SWIG_1(file, line, func), true);
  }

  public void setFile(String value) {
    stiJNI.RawStackFrame_file_set(swigCPtr, this, value);
  }

  public String getFile() {
    return stiJNI.RawStackFrame_file_get(swigCPtr, this);
  }

  public void setLine(long value) {
    stiJNI.RawStackFrame_line_set(swigCPtr, this, value);
  }

  public long getLine() {
    return stiJNI.RawStackFrame_line_get(swigCPtr, this);
  }

  public void setFunc(String value) {
    stiJNI.RawStackFrame_func_set(swigCPtr, this, value);
  }

  public String getFunc() {
    return stiJNI.RawStackFrame_func_get(swigCPtr, this);
  }

}
