/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class RefreshDeviceMessage extends DeviceMessage {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected RefreshDeviceMessage(long cPtr, boolean cMemoryOwn) {
    super(stiJNI.RefreshDeviceMessage_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RefreshDeviceMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        stiJNI.delete_RefreshDeviceMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.RefreshDeviceMessage_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.RefreshDeviceMessage_change_ownership(this, swigCPtr, true);
  }

  public RefreshDeviceMessage(DeviceTrace trace) {
    this(stiJNI.new_RefreshDeviceMessage(DeviceTrace.getCPtr(trace), trace), true);
    stiJNI.RefreshDeviceMessage_director_connect(this, swigCPtr, true, true);
  }

  public static DeviceMessageType getMessageClassType() {
    return DeviceMessageType.swigToEnum(stiJNI.RefreshDeviceMessage_getMessageClassType());
  }

}
