/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class SequenceEntryMap extends java.util.AbstractMap<Long, SequenceEntry> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SequenceEntryMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SequenceEntryMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_SequenceEntryMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof Long)) {
      return false;
    }

    return containsImpl((Long)key);
  }

  public SequenceEntry get(java.lang.Object key) {
    if (!(key instanceof Long)) {
      return null;
    }

    Iterator itr = find((Long) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public SequenceEntry put(Long key, SequenceEntry value) {
    Iterator itr = find((Long) key);
    if (itr.isNot(end())) {
      SequenceEntry oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public SequenceEntry remove(java.lang.Object key) {
    if (!(key instanceof Long)) {
      return null;
    }

    Iterator itr = find((Long) key);
    if (itr.isNot(end())) {
      SequenceEntry oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<Long, SequenceEntry>> entrySet() {
    java.util.Set<Entry<Long, SequenceEntry>> setToReturn =
        new java.util.HashSet<Entry<Long, SequenceEntry>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<Long, SequenceEntry>() {
        private Iterator iterator;

        private Entry<Long, SequenceEntry> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public Long getKey() {
          return iterator.getKey();
        }

        public SequenceEntry getValue() {
          return iterator.getValue();
        }

        public SequenceEntry setValue(SequenceEntry newValue) {
          SequenceEntry oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public SequenceEntryMap() {
    this(stiJNI.new_SequenceEntryMap__SWIG_0(), true);
  }

  public SequenceEntryMap(SequenceEntryMap other) {
    this(stiJNI.new_SequenceEntryMap__SWIG_1(SequenceEntryMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stiJNI.delete_SequenceEntryMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private SequenceEntryMap.Iterator getNextUnchecked() {
      return new SequenceEntryMap.Iterator(stiJNI.SequenceEntryMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(SequenceEntryMap.Iterator other) {
      return stiJNI.SequenceEntryMap_Iterator_isNot(swigCPtr, this, SequenceEntryMap.Iterator.getCPtr(other), other);
    }
  
    private long getKey() {
      return stiJNI.SequenceEntryMap_Iterator_getKey(swigCPtr, this);
    }
  
    private SequenceEntry getValue() {
      return new SequenceEntry(stiJNI.SequenceEntryMap_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(SequenceEntry newValue) {
      stiJNI.SequenceEntryMap_Iterator_setValue(swigCPtr, this, SequenceEntry.getCPtr(newValue), newValue);
    }
  
  }

  public boolean isEmpty() {
    return stiJNI.SequenceEntryMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.SequenceEntryMap_clear(swigCPtr, this);
  }

  private SequenceEntryMap.Iterator find(long key) {
    return new SequenceEntryMap.Iterator(stiJNI.SequenceEntryMap_find(swigCPtr, this, key), true);
  }

  private SequenceEntryMap.Iterator begin() {
    return new SequenceEntryMap.Iterator(stiJNI.SequenceEntryMap_begin(swigCPtr, this), true);
  }

  private SequenceEntryMap.Iterator end() {
    return new SequenceEntryMap.Iterator(stiJNI.SequenceEntryMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return stiJNI.SequenceEntryMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(long key) {
    return stiJNI.SequenceEntryMap_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(long key, SequenceEntry value) {
    stiJNI.SequenceEntryMap_putUnchecked(swigCPtr, this, key, SequenceEntry.getCPtr(value), value);
  }

  private void removeUnchecked(SequenceEntryMap.Iterator itr) {
    stiJNI.SequenceEntryMap_removeUnchecked(swigCPtr, this, SequenceEntryMap.Iterator.getCPtr(itr), itr);
  }

}
