/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class SequenceEntryID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SequenceEntryID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SequenceEntryID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_SequenceEntryID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SequenceEntryID() {
    this(stiJNI.new_SequenceEntryID(), true);
  }

  public void setSeqID(SequenceID value) {
    stiJNI.SequenceEntryID_seqID_set(swigCPtr, this, SequenceID.getCPtr(value), value);
  }

  public SequenceID getSeqID() {
    long cPtr = stiJNI.SequenceEntryID_seqID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SequenceID(cPtr, false);
  }

  public void setSeqIndex(SequenceIndex value) {
    stiJNI.SequenceEntryID_seqIndex_set(swigCPtr, this, SequenceIndex.getCPtr(value), value);
  }

  public SequenceIndex getSeqIndex() {
    long cPtr = stiJNI.SequenceEntryID_seqIndex_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SequenceIndex(cPtr, false);
  }

  public boolean opLess(SequenceEntryID rhs) {
    return stiJNI.SequenceEntryID_opLess(swigCPtr, this, SequenceEntryID.getCPtr(rhs), rhs);
  }

  public boolean opEquals(SequenceEntryID rhs) {
    return stiJNI.SequenceEntryID_opEquals(swigCPtr, this, SequenceEntryID.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(SequenceEntryID rhs) {
    return stiJNI.SequenceEntryID_opNotEquals(swigCPtr, this, SequenceEntryID.getCPtr(rhs), rhs);
  }

}
