/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class SequenceEntry {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SequenceEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SequenceEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_SequenceEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SequenceEntry() {
    this(stiJNI.new_SequenceEntry(), true);
  }

  public void setIndex(int value) {
    stiJNI.SequenceEntry_index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return stiJNI.SequenceEntry_index_get(swigCPtr, this);
  }

  public void setOverwritten(ParsedVarSet value) {
    stiJNI.SequenceEntry_overwritten_set(swigCPtr, this, ParsedVarSet.getCPtr(value), value);
  }

  public ParsedVarSet getOverwritten() {
    long cPtr = stiJNI.SequenceEntry_overwritten_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ParsedVarSet(cPtr, false);
  }

}
