/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class SequenceIndex {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SequenceIndex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SequenceIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_SequenceIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SequenceIndex() {
    this(stiJNI.new_SequenceIndex(), true);
  }

  public void setIndex(int value) {
    stiJNI.SequenceIndex_index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return stiJNI.SequenceIndex_index_get(swigCPtr, this);
  }

  public void setRepeat(int value) {
    stiJNI.SequenceIndex_repeat_set(swigCPtr, this, value);
  }

  public int getRepeat() {
    return stiJNI.SequenceIndex_repeat_get(swigCPtr, this);
  }

  public boolean opLess(SequenceIndex rhs) {
    return stiJNI.SequenceIndex_opLess(swigCPtr, this, SequenceIndex.getCPtr(rhs), rhs);
  }

  public boolean opEquals(SequenceIndex rhs) {
    return stiJNI.SequenceIndex_opEquals(swigCPtr, this, SequenceIndex.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(SequenceIndex rhs) {
    return stiJNI.SequenceIndex_opNotEquals(swigCPtr, this, SequenceIndex.getCPtr(rhs), rhs);
  }

}
