/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class ShotID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ShotID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ShotID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_ShotID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ShotID() {
    this(stiJNI.new_ShotID__SWIG_0(), true);
  }

  public ShotID(ParseID pid, EngineJobSourceID jobSourceID) {
    this(stiJNI.new_ShotID__SWIG_1(ParseID.getCPtr(pid), pid, EngineJobSourceID.getCPtr(jobSourceID), jobSourceID), true);
  }

  public void setParseID(ParseID value) {
    stiJNI.ShotID_parseID_set(swigCPtr, this, ParseID.getCPtr(value), value);
  }

  public ParseID getParseID() {
    long cPtr = stiJNI.ShotID_parseID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ParseID(cPtr, false);
  }

  public void setJobSourceID(EngineJobSourceID value) {
    stiJNI.ShotID_jobSourceID_set(swigCPtr, this, EngineJobSourceID.getCPtr(value), value);
  }

  public EngineJobSourceID getJobSourceID() {
    long cPtr = stiJNI.ShotID_jobSourceID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineJobSourceID(cPtr, false);
  }

  public void setSubmissionTime(TimeStamp value) {
    stiJNI.ShotID_submissionTime_set(swigCPtr, this, TimeStamp.getCPtr(value), value);
  }

  public TimeStamp getSubmissionTime() {
    long cPtr = stiJNI.ShotID_submissionTime_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TimeStamp(cPtr, false);
  }

  public boolean opLess(ShotID rhs) {
    return stiJNI.ShotID_opLess(swigCPtr, this, ShotID.getCPtr(rhs), rhs);
  }

  public boolean opEquals(ShotID rhs) {
    return stiJNI.ShotID_opEquals(swigCPtr, this, ShotID.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(ShotID rhs) {
    return stiJNI.ShotID_opNotEquals(swigCPtr, this, ShotID.getCPtr(rhs), rhs);
  }

  public static ShotID generateUniqueID(ParseID pid, EngineJobSourceID jobSourceID) {
    return new ShotID(stiJNI.ShotID_generateUniqueID(ParseID.getCPtr(pid), pid, EngineJobSourceID.getCPtr(jobSourceID), jobSourceID), true);
  }

  public String print() {
    return stiJNI.ShotID_print(swigCPtr, this);
  }

}
