/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class ShotResultRecord {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ShotResultRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ShotResultRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_ShotResultRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ShotResultRecord() {
    this(stiJNI.new_ShotResultRecord__SWIG_0(), true);
  }

  public ShotResultRecord(DeviceID deviceID) {
    this(stiJNI.new_ShotResultRecord__SWIG_1(DeviceID.getCPtr(deviceID), deviceID), true);
  }

  public boolean isPartialRecord() {
    return stiJNI.ShotResultRecord_isPartialRecord(swigCPtr, this);
  }

  public void setDeviceID(DeviceID value) {
    stiJNI.ShotResultRecord_deviceID_set(swigCPtr, this, DeviceID.getCPtr(value), value);
  }

  public DeviceID getDeviceID() {
    long cPtr = stiJNI.ShotResultRecord_deviceID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DeviceID(cPtr, false);
  }

  public void setRecordStatus(RecordStatus value) {
    stiJNI.ShotResultRecord_recordStatus_set(swigCPtr, this, value.swigValue());
  }

  public RecordStatus getRecordStatus() {
    return RecordStatus.swigToEnum(stiJNI.ShotResultRecord_recordStatus_get(swigCPtr, this));
  }

  public void setDependencies(ShotResultRecordVector value) {
    stiJNI.ShotResultRecord_dependencies_set(swigCPtr, this, ShotResultRecordVector.getCPtr(value), value);
  }

  public ShotResultRecordVector getDependencies() {
    long cPtr = stiJNI.ShotResultRecord_dependencies_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ShotResultRecordVector(cPtr, false);
  }

  public static String statusToString(RecordStatus status) {
    return stiJNI.ShotResultRecord_statusToString(status.swigValue());
  }

}
