/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public final class ShotType {
  public final static ShotType Single = new ShotType("Single");
  public final static ShotType Sequence = new ShotType("Sequence");
  public final static ShotType SingleUndocumented = new ShotType("SingleUndocumented");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ShotType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ShotType.class + " with value " + swigValue);
  }

  private ShotType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ShotType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ShotType(String swigName, ShotType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ShotType[] swigValues = { Single, Sequence, SingleUndocumented };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

