/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class StackTrace {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StackTrace(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StackTrace obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_StackTrace(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StackTrace() {
    this(stiJNI.new_StackTrace(), true);
  }

  public void appendFrame(StackFrame frame) {
    stiJNI.StackTrace_appendFrame__SWIG_0(swigCPtr, this, StackFrame.getCPtr(frame), frame);
  }

  public void appendFrame(String file, long line, String func) {
    stiJNI.StackTrace_appendFrame__SWIG_1(swigCPtr, this, file, line, func);
  }

  public StackFrameVector getFrames() {
    return new StackFrameVector(stiJNI.StackTrace_getFrames(swigCPtr, this), true);
  }

}
