/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class StackTraceData {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected StackTraceData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StackTraceData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_StackTraceData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StackTraceData() {
    this(stiJNI.new_StackTraceData__SWIG_0(), true);
  }

  public StackTraceData(DeviceID localID, FileServer fileServer) {
    this(stiJNI.new_StackTraceData__SWIG_1(DeviceID.getCPtr(localID), localID, FileServer.getCPtr(fileServer), fileServer), true);
  }

  public StackTraceData(FileIDVector timingFiles, StringVector functionNames) {
    this(stiJNI.new_StackTraceData__SWIG_2(FileIDVector.getCPtr(timingFiles), timingFiles, StringVector.getCPtr(functionNames), functionNames), true);
  }

  public CompressedStackTrace addStackTrace(StackTrace stackTrace) {
    return new CompressedStackTrace(stiJNI.StackTraceData_addStackTrace(swigCPtr, this, StackTrace.getCPtr(stackTrace), stackTrace), true);
  }

  public StackTrace getStackTrace(CompressedStackTrace stackTrace) {
    return new StackTrace(stiJNI.StackTraceData_getStackTrace(swigCPtr, this, CompressedStackTrace.getCPtr(stackTrace), stackTrace), true);
  }

  public FileIDVector getTimingFiles() {
    return new FileIDVector(stiJNI.StackTraceData_getTimingFiles(swigCPtr, this), false);
  }

  public StringVector getFunctionNames() {
    return new StringVector(stiJNI.StackTraceData_getFunctionNames(swigCPtr, this), false);
  }

  public void setFileServer(FileServer server) {
    stiJNI.StackTraceData_setFileServer(swigCPtr, this, FileServer.getCPtr(server), server);
  }

  public boolean getFileServer(FileServer server) {
    return stiJNI.StackTraceData_getFileServer(swigCPtr, this, FileServer.getCPtr(server), server);
  }

  public void replaceFile(String oldFilename, FileID newFile) {
    stiJNI.StackTraceData_replaceFile(swigCPtr, this, oldFilename, FileID.getCPtr(newFile), newFile);
  }

}
