/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

import java.io.FileNotFoundException;
import java.io.IOException;

public class STIJava {


    static {
        Reload();
    }

    private STIJava() {
    }

    public static void LoadLibrary() {
        STIJava sti = new STIJava();    //creating instance runs static block
    }

    public static void Reload() {
        try {
            System.out.print("Loading stijava...");
            // System.loadLibrary("stijava");

            try {
                NativeUtils.loadLibraryFromJar("/lib/libstidevice.so.3.0.0", true);
                NativeUtils.loadLibraryFromJar("/lib/libstinetwork.so.3.0.0", true);
                NativeUtils.loadLibraryFromJar("/lib/libstijava.so");
            } catch (FileNotFoundException e) {
                System.out.println("");
                System.out.println("NativeUtils loadLibraryFromJar failed:");
                e.printStackTrace();
            } catch (IOException e) {
                System.out.println("");
                System.out.println("NativeUtils loadLibraryFromJar failed:");
                e.printStackTrace();
            } 

            System.out.println("success.");

        } catch (UnsatisfiedLinkError e) {
            System.out.println("failed.");
            //External library for loading an so the is stored inside the jar (cz.adamh.utils.NativeUtils)
            // try {
            //     NativeUtils.loadLibraryFromJar("/natives/libsti.so"); // during runtime. .DLL within .JAR
            // } catch (java.io.IOException e1) {
            //     throw new RuntimeException(e1);
            // }
            e.printStackTrace();
        }
    }
}
