/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class SynchronousEventAdapter extends SynchronousEvent {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected SynchronousEventAdapter(long cPtr, boolean cMemoryOwn) {
    super(stiJNI.SynchronousEventAdapter_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SynchronousEventAdapter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        stiJNI.delete_SynchronousEventAdapter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    stiJNI.SynchronousEventAdapter_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    stiJNI.SynchronousEventAdapter_change_ownership(this, swigCPtr, true);
  }

  public SynchronousEventAdapter(double time) {
    this(stiJNI.new_SynchronousEventAdapter(time), true);
    stiJNI.SynchronousEventAdapter_director_connect(this, swigCPtr, true, true);
  }

  public void loadEvent() {
    if (getClass() == SynchronousEventAdapter.class) stiJNI.SynchronousEventAdapter_loadEvent(swigCPtr, this); else stiJNI.SynchronousEventAdapter_loadEventSwigExplicitSynchronousEventAdapter(swigCPtr, this);
  }

  public void playEvent() {
    if (getClass() == SynchronousEventAdapter.class) stiJNI.SynchronousEventAdapter_playEvent(swigCPtr, this); else stiJNI.SynchronousEventAdapter_playEventSwigExplicitSynchronousEventAdapter(swigCPtr, this);
  }

  public void collectMeasurementData() {
    if (getClass() == SynchronousEventAdapter.class) stiJNI.SynchronousEventAdapter_collectMeasurementData(swigCPtr, this); else stiJNI.SynchronousEventAdapter_collectMeasurementDataSwigExplicitSynchronousEventAdapter(swigCPtr, this);
  }

  public void stopEvent() {
    if (getClass() == SynchronousEventAdapter.class) stiJNI.SynchronousEventAdapter_stopEvent(swigCPtr, this); else stiJNI.SynchronousEventAdapter_stopEventSwigExplicitSynchronousEventAdapter(swigCPtr, this);
  }

  public void pauseEvent() {
    if (getClass() == SynchronousEventAdapter.class) stiJNI.SynchronousEventAdapter_pauseEvent(swigCPtr, this); else stiJNI.SynchronousEventAdapter_pauseEventSwigExplicitSynchronousEventAdapter(swigCPtr, this);
  }

  public void unpauseEvent(boolean retrigger) {
    if (getClass() == SynchronousEventAdapter.class) stiJNI.SynchronousEventAdapter_unpauseEvent(swigCPtr, this, retrigger); else stiJNI.SynchronousEventAdapter_unpauseEventSwigExplicitSynchronousEventAdapter(swigCPtr, this, retrigger);
  }

}
