/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class TaskVector extends java.util.AbstractList<Task> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TaskVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TaskVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_TaskVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TaskVector(Task[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Task element : initialElements) {
      add(element);
    }
  }

  public TaskVector(Iterable<Task> initialElements) {
    this();
    for (Task element : initialElements) {
      add(element);
    }
  }

  public Task get(int index) {
    return doGet(index);
  }

  public Task set(int index, Task e) {
    return doSet(index, e);
  }

  public boolean add(Task e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Task e) {
    modCount++;
    doAdd(index, e);
  }

  public Task remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public TaskVector() {
    this(stiJNI.new_TaskVector__SWIG_0(), true);
  }

  public TaskVector(TaskVector other) {
    this(stiJNI.new_TaskVector__SWIG_1(TaskVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return stiJNI.TaskVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    stiJNI.TaskVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return stiJNI.TaskVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    stiJNI.TaskVector_clear(swigCPtr, this);
  }

  public TaskVector(int count, Task value) {
    this(stiJNI.new_TaskVector__SWIG_2(count, Task.getCPtr(value), value), true);
  }

  private int doSize() {
    return stiJNI.TaskVector_doSize(swigCPtr, this);
  }

  private void doAdd(Task x) {
    stiJNI.TaskVector_doAdd__SWIG_0(swigCPtr, this, Task.getCPtr(x), x);
  }

  private void doAdd(int index, Task x) {
    stiJNI.TaskVector_doAdd__SWIG_1(swigCPtr, this, index, Task.getCPtr(x), x);
  }

  private Task doRemove(int index) {
    long cPtr = stiJNI.TaskVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Task(cPtr, true);
  }

  private Task doGet(int index) {
    long cPtr = stiJNI.TaskVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Task(cPtr, true);
  }

  private Task doSet(int index, Task val) {
    long cPtr = stiJNI.TaskVector_doSet(swigCPtr, this, index, Task.getCPtr(val), val);
    return (cPtr == 0) ? null : new Task(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    stiJNI.TaskVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
