/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class TimeStamp {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TimeStamp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TimeStamp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_TimeStamp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TimeStamp() {
    this(stiJNI.new_TimeStamp__SWIG_0(), true);
  }

  public TimeStamp(int year, int month, int day, int hour, int min, int sec, int millis, int micros, int nanos) {
    this(stiJNI.new_TimeStamp__SWIG_1(year, month, day, hour, min, sec, millis, micros, nanos), true);
  }

  public String print() {
    return stiJNI.TimeStamp_print(swigCPtr, this);
  }

  public String date() {
    return stiJNI.TimeStamp_date(swigCPtr, this);
  }

  public String date_YYYY_MM_DD() {
    return stiJNI.TimeStamp_date_YYYY_MM_DD__SWIG_0(swigCPtr, this);
  }

  public String date_YYYY_MM_DD(String separator) {
    return stiJNI.TimeStamp_date_YYYY_MM_DD__SWIG_1(swigCPtr, this, separator);
  }

  public String time() {
    return stiJNI.TimeStamp_time(swigCPtr, this);
  }

  public String time_hh_mm_ss() {
    return stiJNI.TimeStamp_time_hh_mm_ss__SWIG_0(swigCPtr, this);
  }

  public String time_hh_mm_ss(String separator) {
    return stiJNI.TimeStamp_time_hh_mm_ss__SWIG_1(swigCPtr, this, separator);
  }

  public String time_hh_mm_ss_mmmuuunnn() {
    return stiJNI.TimeStamp_time_hh_mm_ss_mmmuuunnn(swigCPtr, this);
  }

  public String time_mmmuuunnn(String separator) {
    return stiJNI.TimeStamp_time_mmmuuunnn(swigCPtr, this, separator);
  }

  public boolean opLess(TimeStamp rhs) {
    return stiJNI.TimeStamp_opLess(swigCPtr, this, TimeStamp.getCPtr(rhs), rhs);
  }

  public boolean opEquals(TimeStamp rhs) {
    return stiJNI.TimeStamp_opEquals(swigCPtr, this, TimeStamp.getCPtr(rhs), rhs);
  }

  public boolean opNotEquals(TimeStamp rhs) {
    return stiJNI.TimeStamp_opNotEquals(swigCPtr, this, TimeStamp.getCPtr(rhs), rhs);
  }

  public boolean isSameDate(TimeStamp rhs) {
    return stiJNI.TimeStamp_isSameDate(swigCPtr, this, TimeStamp.getCPtr(rhs), rhs);
  }

  public String toString() {
    return stiJNI.TimeStamp_toString(swigCPtr, this);
  }

  public static TimeStamp fromString(String timeStamp) {
    return new TimeStamp(stiJNI.TimeStamp_fromString(timeStamp), true);
  }

  public int year() {
    return stiJNI.TimeStamp_year(swigCPtr, this);
  }

  public int month() {
    return stiJNI.TimeStamp_month(swigCPtr, this);
  }

  public int day() {
    return stiJNI.TimeStamp_day(swigCPtr, this);
  }

  public int hour() {
    return stiJNI.TimeStamp_hour(swigCPtr, this);
  }

  public int minute() {
    return stiJNI.TimeStamp_minute(swigCPtr, this);
  }

  public int sec() {
    return stiJNI.TimeStamp_sec(swigCPtr, this);
  }

  public int millis() {
    return stiJNI.TimeStamp_millis(swigCPtr, this);
  }

  public int micros() {
    return stiJNI.TimeStamp_micros(swigCPtr, this);
  }

  public int nanos() {
    return stiJNI.TimeStamp_nanos(swigCPtr, this);
  }

  public void add_day(int days) {
    stiJNI.TimeStamp_add_day__SWIG_0(swigCPtr, this, days);
  }

  public void add_day() {
    stiJNI.TimeStamp_add_day__SWIG_1(swigCPtr, this);
  }

  public void add_hour(int hours) {
    stiJNI.TimeStamp_add_hour(swigCPtr, this, hours);
  }

  public void add_minute(int minutes) {
    stiJNI.TimeStamp_add_minute(swigCPtr, this, minutes);
  }

  public void add_sec(int seconds) {
    stiJNI.TimeStamp_add_sec(swigCPtr, this, seconds);
  }

  public void add_ns(int ns) {
    stiJNI.TimeStamp_add_ns(swigCPtr, this, ns);
  }

}
