
#include <sti/device/DeviceMessageReceiver.h>
#include <sti/device/DeviceID.h>
#include <sti/device/Device.h>
#include <sti/device/DeviceMessageDispatcher.h>
#include <sti/device/DeviceMessageHandler.h>

#include <string>
#include <set>

using STI::Device::DeviceMessageReceiver;
using STI::Device::DeviceMessageDispatcher;
using STI::Device::DeviceMessageHandler;
using STI::Device::DeviceID;
using STI::Device::Device;
using STI::Utils::LocalCollection;
using STI::Device::DeviceMessageListenerID;


DeviceMessageReceiver::DeviceMessageReceiver(const DeviceID& localID, 
	const std::shared_ptr<STI::Utils::LocalCollection<DeviceID, Device>>& deviceCollection,
	const std::shared_ptr<DeviceMessageDispatcher>& dispatcher)
	: deviceCollection(deviceCollection), localID(localID), localDispatcher(dispatcher)
{
	//Add listener for add/remove of device references to LocalCollection.
	//This way when a new device is added, an event handler is automatically added to the device's dispatcher.
	auto collectionListener = std::make_shared<CollectionListener>(this);
	deviceCollection->addListener(collectionListener);

	//add handler for events generated by local device (intra device messages)
	addDeviceMessageHandler(localID);
}


DeviceMessageReceiver::~DeviceMessageReceiver()
{
	removeAllHandlers();	//remove remote handlers
}


void DeviceMessageReceiver::addDeviceMessageHandler(const DeviceID& sourceDeviceID)
{
	std::shared_ptr<DeviceMessageDispatcher> dispatcher;
	std::shared_ptr<DeviceMessageHandler> handler;

	if (getSourceDeviceMessageDispatcher(sourceDeviceID, dispatcher) && 
		dispatcher->makeMessageHandler(handler)) 
	{
		refreshListenerGroups(sourceDeviceID, handler);	//populate handler with existing listeners
		dispatcher->addMessageHandler(localID, handler);	//add this handler to the remote dispatcher under the local ID
		handlers.add(sourceDeviceID, handler);			//store handler reference locally
	}
}


void DeviceMessageReceiver::removeDeviceMessageHandler(const DeviceID& sourceDeviceID)
{
	std::shared_ptr<DeviceMessageDispatcher> dispatcher;

	std::shared_ptr<DeviceMessageHandler> handler;
	if (handlers.get(sourceDeviceID, handler) && handler != 0) {
		handler->disable();
	}

	//Attempt to remove from the remote dispatcher
	if (getSourceDeviceMessageDispatcher(sourceDeviceID, dispatcher)) {
		dispatcher->removeMessageHandler(localID);	//remove this handler to the remote dispatcher
	}

	handlers.remove(sourceDeviceID);
}


void DeviceMessageReceiver::removeAllHandlers()
{
	std::set<DeviceID> ids;
	handlers.getKeys(ids);

	for (auto& handerID : ids) {
		removeDeviceMessageHandler(handerID);
	}
}


bool DeviceMessageReceiver::getSourceDeviceMessageDispatcher(const DeviceID& sourceDeviceID, 
	std::shared_ptr<DeviceMessageDispatcher>& dispatcher)
{
	bool success = false;
	std::shared_ptr<Device> device;

	if (sourceDeviceID == localID) {
		dispatcher = localDispatcher;
		success = (dispatcher != 0);
	}
	else if (deviceCollection->get(sourceDeviceID, device) && device != 0) {
		device->getMessageDispatcher(dispatcher);
		success = (dispatcher != 0);
	}

	return success;
}


void DeviceMessageReceiver::refreshListenerGroups(const DeviceID& sourceDeviceID, 
	const std::shared_ptr<DeviceMessageHandler>& handler)
{
	refreshListenerGroup(sourceDeviceID, refreshListeners, handler);
	refreshListenerGroup(sourceDeviceID, channelUpdateListeners, handler);
	refreshListenerGroup(sourceDeviceID, attributeUpdateListeners, handler);
	refreshListenerGroup(sourceDeviceID, monitorUpdateListeners, handler);
	refreshListenerGroup(sourceDeviceID, monitorStatusUpdateListeners, handler);
	refreshListenerGroup(sourceDeviceID, taskUpdateListeners, handler);
	refreshListenerGroup(sourceDeviceID, engineSchedulerListeners, handler);
	refreshListenerGroup(sourceDeviceID, engineParserListeners, handler);
	refreshListenerGroup(sourceDeviceID, collectionUpdateListeners, handler);
	refreshListenerGroup(sourceDeviceID, engineStateListeners, handler);
	refreshListenerGroup(sourceDeviceID, engineJobUpdateListeners, handler);
}

void DeviceMessageReceiver::clearAllListenerGroups()
{
	clearListenerGroups(refreshListeners);
	clearListenerGroups(channelUpdateListeners);
	clearListenerGroups(attributeUpdateListeners);
	clearListenerGroups(monitorUpdateListeners);
	clearListenerGroups(monitorStatusUpdateListeners);
	clearListenerGroups(taskUpdateListeners);
	clearListenerGroups(engineSchedulerListeners);
	clearListenerGroups(engineParserListeners);
	clearListenerGroups(collectionUpdateListeners);
	clearListenerGroups(engineStateListeners);
	clearListenerGroups(engineJobUpdateListeners);
}

void DeviceMessageReceiver::removeListener(const DeviceID& sourceDeviceID, const DeviceMessageListenerID& listenerID)
{
	bool success = false;

	switch (listenerID.type) {
	case DeviceMessageType::Refresh:
		success = removeListener(sourceDeviceID, listenerID, refreshListeners);
		break;
	case DeviceMessageType::ChannelUpdate:
		success = removeListener(sourceDeviceID, listenerID, channelUpdateListeners);
		break;
	case DeviceMessageType::AttributeUpdate:
		success = removeListener(sourceDeviceID, listenerID, attributeUpdateListeners);
		break;
	case DeviceMessageType::MonitorUpdate:
		success = removeListener(sourceDeviceID, listenerID, monitorUpdateListeners);
		break;
	case DeviceMessageType::MonitorStatusUpdate:
		success = removeListener(sourceDeviceID, listenerID, monitorStatusUpdateListeners);
		break;
	case DeviceMessageType::TaskUpdate:
		success = removeListener(sourceDeviceID, listenerID, taskUpdateListeners);
		break;
	case DeviceMessageType::EngineScheduler:
		success = removeListener(sourceDeviceID, listenerID, engineSchedulerListeners);
		break;
	case DeviceMessageType::EngineParser:
		success = removeListener(sourceDeviceID, listenerID, engineParserListeners);
		break;
	case DeviceMessageType::CollectionUpdate:
		success = removeListener(sourceDeviceID, listenerID, collectionUpdateListeners);
		break;
	case DeviceMessageType::EngineStatus:
		success = removeListener(sourceDeviceID, listenerID, engineStateListeners);
		break;
	case DeviceMessageType::EngineJobUpdate:
		success = removeListener(sourceDeviceID, listenerID, engineJobUpdateListeners);
		break;	
	}
	
	if (success) {
		std::shared_ptr<DeviceMessageHandler> handler;

		//refresh any installed handlers with updated listener group
		if (handlers.get(sourceDeviceID, handler) && handler != 0) {
			refreshListenerGroups(sourceDeviceID, handler);
		}
	}
}

void DeviceMessageReceiver::clearListeners()
{
	clearAllListenerGroups();
	removeAllHandlers();
}
