#ifndef STI_ENGINE_DEVICEEVENTPARSER_H
#define STI_ENGINE_DEVICEEVENTPARSER_H

#include "fwd/RawEvent_fwd.h"
#include "fwd/SynchronousEvent_fwd.h"
#include "fwd/DeviceID_fwd.h"

#include <set>

namespace STI
{
namespace Engine
{

//Mixin class that enables device parsing.  The device must implement this interface in order
//for the EventEngineParser to delegate to the parseDeviceEvents defined by the device.
//DeviceEventParser also includes an event target.  Device generated events are added by calling addEvent,
//which appends the events to the targeted partner event list for the engine.

class DeviceEventParser
{
public:

	virtual ~DeviceEventParser() {}

	virtual void parseEvents(const STI::Engine::RawEventMap& events, SynchronousEventVector& synchedEvents) const = 0;
	virtual void getEventTargets(std::set<STI::Device::DeviceID>& targetIDs) = 0;

	void setPartnerEventTarget(DeviceEventMap* target);

	//evt is the event generated by the device
	//referenceEvent is the event that prompted the creation of the device generated event.
	void addEvent(const RawEvent& evt, const RawEvent& referenceEvent);
	void clearEventNumber();

private:
	DeviceEventMap* _target;
	unsigned eventNumber;
};


} //Engine
} //STI

#endif
