#ifndef STI_ENGINE_DEVICEEVENTPARSER_H
#define STI_ENGINE_DEVICEEVENTPARSER_H

#include "fwd/RawEvent_fwd.h"
#include "fwd/SynchronousEvent_fwd.h"
#include "fwd/DeviceID_fwd.h"
#include "EngineID.h"

#include <set>
#include <mutex>

namespace STI
{
namespace Engine
{

class EngineID;

//Mixin class that enables device parsing.  The device must implement this interface in order
//for the EventEngineParser to delegate to the parseDeviceEvents defined by the device.
//DeviceEventParser also includes an event target.  Device generated events are added by calling addEvent,
//which appends the events to the targeted partner event list for the engine.

class DeviceEventParser
{
public:

	virtual ~DeviceEventParser() {}

	virtual void getEventTargets(std::set<STI::Device::DeviceID>& targetIDs) = 0;

	void parseEvents(const STI::Engine::RawEventMap& events, SynchronousEventVector& synchedEvents, const STI::Engine::EngineID& engineID, DeviceEventMap* target);

	//void push_error();	//should throw instead
	void addWarning();	//show return stream for adding message

	//evt is the event generated by the device
	//referenceEvent is the event that prompted the creation of the device generated event.
	void addEvent(const RawEvent& evt, const RawEvent& referenceEvent);

	const EngineID& getCurrentEngineID() const { return currentEngineID; }

private:

	virtual void parseEvents(const STI::Engine::RawEventMap& events, SynchronousEventVector& synchedEvents) = 0;

	void setPartnerEventTarget(DeviceEventMap* target);
	void clearEventNumber();

	EngineID currentEngineID;
	DeviceEventMap* _target;
	unsigned eventNumber;

	mutable std::mutex parseMutex;
};


} //Engine
} //STI

#endif
