
#include "EventEngine.h"
#include "EventEngineParser.h"
#include "DeviceEventParser.h"
#include "RawEvent.h"
#include "SynchronousEvent.h"
#include "Channel.h"

#include <memory>
#include <thread>

using STI::Engine::DeviceEventParser;
using STI::Engine::EngineState;
using STI::Engine::EventEngine;
using STI::Engine::ParserCallback;
using STI::Engine::ParserCallbackMessage;
using STI::Engine::ParseID;
using STI::Engine::RawEventVector;
using STI::Engine::TriggerCallback;


EventEngine::EventEngine(const STI::Device::DeviceID& localID, STI::Device::ChannelMap& channels, DeviceEventParser* deviceParser) :
	parser(this, deviceParser), 
	rawEvents(parser.rawEvents), 
	partnerEvents(parser.partnerEvents), 
	measurementBuffer(3),
	localDeviceID(localID),
	localChannels(channels)
{
}

EventEngine::~EventEngine()
{

}

void EventEngine::clear()
{
	rawEvents.clear();
	synchedEvents.clear();
	partnerEvents.clear();

	//If this fails for some reason, getState() will reflect this.
	setState(EngineState::Idle);
}

void EventEngine::parse(const ParseID& parseID, const RawEventVector& events, const STI::Engine::ParserCallback& cb)
{
	std::string errors;
	
	if (parser.parse(events, synchedEvents, errors)) {
		//successfully parsed
		lastParseID = parseID;
	}

//	ParserCallbackMessage message;
//	message.errors = errors;
//	cb.returnResults(message);
}

void EventEngine::handleParsingResults(const ParserCallbackMessage& message)	//ParserCallbackTarget interface
{

}


bool EventEngine::play(const ParseID& parseID, TriggerCallback& triggerCB, STI::Engine::ResultTicket& resultsOut, bool debug)
{
	if (!isState(EngineState::Parsed)) {
		return false;
	}

	//Make sure we are trying to play the shot that is currently parsed on this engine.
	if (parseID != lastParseID) {
		return false;
	}

	//Make ShotID and grab Measurement references generated by parse.
	//These will be filled with data after the shot is played.
	ShotID currentShot;
	auto newMeasurements = std::make_shared<MeasurementVector>();
	for (auto& synchEvent : synchedEvents) {
		auto& evtMeasurements = synchEvent->getMeasurements();
		for (auto& m : evtMeasurements) {
			newMeasurements->push_back(m);
		}
	}
	measurementBuffer.add(currentShot, newMeasurements);	//Add this shot to the buffer

	//Prepare events
	for (auto& synchEvent : synchedEvents) {
		synchEvent->reset();		//resets Measurement events if they've played before
		synchEvent->load();			//loads (or reloads) events if needed
	}

	////all devices that depend on this device for play
	//for (auto& dev : dependentDevices) {
	//	dev->play(parseID, dependentTriggerCB, dependentResultsOut, debug);
	//}

	if (!armTrigger(triggerCB)) {
		return false;
	}

	waitForTrigger();
	triggerCB.triggerFired();		//Callback to the device that called play to confirm that this device is playing.
									//Also, if this device is a delegated system trigger, this indicated 
									//that the rest of the system should now be triggered.

	return playDeviceEvents();
}
// server1.triggerEvent(ch(server1,slow,4), 5.0)		//trigger just server1
// mainserver.triggerEvent(ch(server1,slow,4), 5.0)		//trigger entire system

//play()
//{
//	setState(Arming);
//	setupTriggers();
//
//	//all devices that depend on this device for play
//	for (auto& dev : dependentDevices) {
//		dev->play();
//	}
//
//	waitForDependentDevices();
//
//	if (setState(WaitingForTrigger)) {
//		triggerCB->ready();
//		triggerCB->wait();
//	}
//
//}

bool EventEngine::armTrigger(TriggerCallback& triggerCB)
{
	if (!setState(EngineState::Arming)) {
		return setState(EngineState::Error);;
	}

	//arm triggers on dependent devices ( = those that declare this device as their server)
	//	waitForArmingDevices();

	if (!setState(EngineState::WaitingForTrigger)) {
		return setState(EngineState::Error);;
	}

	triggerCB.ready(localDeviceID);

	return true;
}

void EventEngine::waitForTrigger() const
{
	std::unique_lock<std::mutex> triggerLock(triggerMutex);

	while (isState(EngineState::WaitingForTrigger)) {
		triggerCondition.wait(triggerLock);
	}
}

void EventEngine::trigger(STI::Device::DeviceID& target)
{
	//Triggers a specific device (allows any device to act as the system trigger)
	if (target == localDeviceID) {
		trigger();
	}
}

void EventEngine::trigger()
{
	std::unique_lock<std::mutex> triggerLock(triggerMutex);
	triggerCondition.notify_all();			//releases waitForTrigger
}

bool EventEngine::playDeviceEvents()
{
	if (!setState(EngineState::Playing)) {
		return setState(EngineState::Error);
	}

	//launch measurements thread
	auto measurementThread = std::thread(&EventEngine::measureData, this);
	
	//time.reset();

	//play all events (at appropriate times)
	for (auto& evt : synchedEvents) {
		
		if (!isState(EngineState::Playing))
			break;

		//switch(waitUntil(evt->getTime())),  cases for play, pause, stop ?

		if (waitUntil(evt->getTime())) {	//success if not interrupted
			evt->play();
		}
	}

	measurementThread.join();	//wait for measurement collection to complete

	if (isState(EngineState::Playing)) {
		if (!setState(EngineState::Parsed)) {
			return setState(EngineState::Error);
		}
	}

	return true;	//play and collect were a success
}

bool EventEngine::waitUntil(double time)
{
	return isState(EngineState::Playing);
}


void EventEngine::pause()
{
	setState(EngineState::Paused);
}

void EventEngine::unpause(bool retrigger) 
{
	//if retrigger, require a trigger before resuming (allows hard time resume)
	if (!setState(EngineState::Playing)) {
		setState(EngineState::Error);
		stop();
	}

}

void EventEngine::measureData()
{
	for (auto& evt : synchedEvents) {
		evt->collectData();

		if (!isState(EngineState::Playing))
			break;
	}
}

void EventEngine::stop()
{
	bool success = true;

	switch (getState()) {
	case EngineState::Parsing:
		success = setState(EngineState::Idle);
		break;	
	case EngineState::Arming:
	case EngineState::WaitingForTrigger:
	case EngineState::Playing:
		success = setState(EngineState::Parsed);
		break;
	}

	stopDeviceEvents();
	trigger();			//in case WaitingForTrigger

	if (!success) {
		setState(EngineState::Error);
	}
}

void EventEngine::stopDeviceEvents()
{
	for (auto& evt : synchedEvents) {
		evt->stop();
	}
}

bool EventEngine::isState(EngineState target) const
{
	return stateMachine.isState(target);
}

STI::Engine::EngineState EventEngine::getState() const
{
	return stateMachine.getState();
}

bool EventEngine::setState(EngineState target)
{
	return stateMachine.setState(target);
}

