#ifndef STI_ENGINE_EVENTENGINE_H
#define STI_ENGINE_EVENTENGINE_H

#include "EventEngineParser.h"
#include "MessageGenerator.h"
#include "EventEngineStateMachine.h"
//#include "ParserCallback.h"
#include "ParseID.h"
#include "ResultTicket.h"
#include "ShotID.h"
#include "TimeStamp.h"
#include "TriggerCallback.h"
#include "utils/OrderedBufferMap.h"

#include "DeviceEventDispatcher.h"
#include "DeviceEvent.h"
#include "DeviceCollection.h"

#include "fwd/Channel_fwd.h"
#include "fwd/DeviceEventParser_fwd.h"
#include "fwd/DeviceID_fwd.h"
#include "fwd/Measurement_fwd.h"
#include "fwd/RawEvent_fwd.h"
#include "fwd/SynchronousEvent_fwd.h"

#include <memory>
#include <mutex>

namespace STI
{
namespace Engine
{

class EventEngine;
class EventEngineJob;
class EventEngineDependencyTree;


class EventTime
{
	EventTime(double time);
};

// template<typename ID, typename Job>
// class JobQueue
// {


// };



class EventEngine :  public STI::Device::MessageGenerator	//public ParserCallbackTarget,
{
public:

	//parse queue
	//play queue
	//save queue

	EventEngine(
		const STI::Device::DeviceID& localID, 
		STI::Device::ChannelMap& channels, 
		DeviceEventParser* deviceParser,
		const std::shared_ptr<STI::Device::DeviceEventDispatcher>& dispatcher,
		const std::shared_ptr<STI::Device::DeviceCollection>& collection);
	~EventEngine();

	void clear();

	void parse(const std::shared_ptr<STI::Engine::EventEngineJob>& job);
	void handleParseMessage(const std::shared_ptr<STI::Device::EngineSchedulerMessage>& evt);
	//void parse(const ParseID& parseID, const RawEventVector& events, const STI::Device::DeviceID& server);

	//Could pass in a DocumentationTarget that the engine (attempts) to use to save data.  Falls back on its local DocTarget.
	//DocTarget would be passed from the instigating server, and would save to disk.
	//For all devices, DocTarget would provide persistent access to any data it stored.
	//--in the case of devices using their local DocTarget, only events that failed to be pulled would be available
	//If DocTarget pulls, it is now the owner of the shot's data and is reponsible for providing persistence.
	bool play(const ParseID& parseID, TriggerCallback& triggerCB, ResultTicket& resultsOut, bool debug = false);	//ticket is a callback that will fire when results are ready;  playCB could push event number
	void trigger();
	void trigger(STI::Device::DeviceID& target);		//triggers just target
	void stop();

	void pause();
	void unpause(bool retrigger);		//if retrigger, require a trigger before resuming (allows hard time resume)

	//debugging; separate class?
//	void addBreakpoint(time);
//	void clearBreakpoints();
//	void getBreakpoints(ids);
//	id getBreakpointAt(time);
//	void removeBreakpoint(id);
//	void getResults();

//	Debug: inspect state:  return current values of all out channels, and what RawEvent was last played, what time it thinks it is...

	bool isState(EngineState target) const;
	STI::Engine::EngineState getState() const;

	//Local device details
	STI::Device::DeviceID localDeviceID;	//The DeviceID of the host of this engine
	STI::Device::ChannelMap& localChannels;

	const STI::Engine::ParseID& getLastParseID() { return lastParseID; }

private:

	void parseDevice(const STI::Device::DeviceID& id, const std::shared_ptr<STI::Engine::EventEngineJob>& job);

	bool isTargetServerForDevice(const STI::Device::DeviceID& id);
	void getOwnedDeviceIDs(std::set<STI::Device::DeviceID>& ownedIDs);
	void divideEvents(const RawEventVector& events, RawEventVector& upstreamEvents);

	bool setState(EngineState target);

	bool armTrigger(TriggerCallback& triggerCB);
	void waitForTrigger() const;

//	void handleParsingResults(const ParserCallbackMessage& message);	//ParserCallbackTarget interface
	
	bool playDeviceEvents();
	void measureData();
	void stopDeviceEvents();

	bool waitUntil(double time);

	//Clock time;

	STI::Engine::ParseID lastParseID;		//The ID of the most recently parsed shot

	EventEngineStateMachine stateMachine;
	EventEngineParser parser;
	std::shared_ptr<STI::Device::DeviceCollection> deviceCollection;

	//server events
	std::map<STI::Device::DeviceID, RawEventVector> eventsByTarget;
	std::shared_ptr<EventEngineDependencyTree> dependencyTree;
	std::shared_ptr<EventEngineDependencyTree> localSubtree;

	//local events
	RawEventMap& rawEvents;					//Originating from python timing file (STIpy library)
	SynchronousEventVector synchedEvents;	//Generated by device specific parseDeviceEvents()
	DeviceEventMap& partnerEvents;

	//Each ShotID refers to a single shot's measurement vector.
	STI::Utils::OrderedBufferMap<ShotID, std::shared_ptr<MeasurementVector>> measurementBuffer;

	//trigger
	mutable std::mutex triggerMutex;
	mutable std::condition_variable triggerCondition;

	//parser
	mutable std::mutex parseMutex;
	mutable std::condition_variable parseCondition;

};

} //Engine
} //STI

#endif
