
#include "TestDevice.h"

#include <sti/device/PersistenceManager.h>
#include <sti/engine/Measurement.h>
#include <sti/utils/FileID.h>

#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>

using STI::Utils::MixedValue;
using STI::Utils::MixedValueType;


TestDevice::TestDevice(const STI::Utils::Configuration& config)
: STI::Device::LocalDevice(config)
{
	// *** Define channels *** //

	// Output channels (the device's output actuators)
	addOutputChannel(0, MixedValueType::Double, "coil current");	//outputs a Double
	addOutputChannel(1, MixedValueType::Number, "supply voltage");	//outputs a number

	// Input channels (make measurements that are recorded by the device)
	addInputChannel(2, MixedValueType::Number, "thermocouple voltage");	//measures a number
	addInputChannel(3, MixedValueType::File, "example text file");	//measures data saved as a file
}


void TestDevice::parseEvents(const STI::Engine::RawEventMap& eventsIn, STI::Engine::SynchronousEventVector& synchedEvents)
{
	// * RawEvent: Event class containing a high-level description of the event information: (time, channel, value).
	// * SynchronousEvent: User defined event class responsible for implementing the event on the hardware.
	// 
	// The parseEvents function must convert the RawEvents generated by the timing file into a list of SynchronousEvents
	// that are ready to play on the hardware.
	//
	// * RawEventMap is of type std::map<double, std::vector<RawEvent>>.
	// The key of each map entry is the time (double) of the event(s). The value of each map entry is a vector of RawEvents
	// that are scheduled to occur at this time. In general, multiple events can occur at the same time, as long as they are
	// on distinct channels. It is the job of this function to parse this event information and generate a hardware-level
	// event (SynchronousEvent) capable of implementing the desired changes on the channel(s) specified by the RawEvent(s).
	// 'SynchronousEvent' is called 'synchronous' because all hardware changes on the channels are scheduled to occur at 
	// the same time for each SynchronousEvent. The grouping of RawEvent by their common time in the RawEventMap helps with this.
	// 
	// * SynchronousEventVector is of type std::vector<std::shared_ptr<SynchronousEvent>>.
	// SynchronousEvent itself is an abstract class, and so it first must be implemented by an appropriate derived class that  
	// includes the hardware-specific implementation details. Instances of this custom derived class should then be added 
	// to the synchedEvents vector as shared_ptr's.

	bool inputEvent;
	unsigned fileMeasurementIndex = 0;

	for (auto& tuple : eventsIn) {
		// Here 'tuple' is of type { time, vector<RawEvent> }, where the vector is the set of events at this time.
		inputEvent = false;

		//check for input event
		for (auto& rawEvent : tuple.second) {
			if (rawEvent.isMeasurementEvent()) {
				inputEvent = true;
				break;
			}
		}

		// Example of error checking. When an error is encountered during parsing, an exception should be thrown.
		// This exception is handled by STI and converted to a parsing error message. 
		if (inputEvent && tuple.second.size() > 1) {
			// Error: In this example, when there is an input event, it must be the only event at that time.
			// The EventConflictException constuctor accepts reference to the two offending events, plus a message: 
			throw STI::Engine::EventConflictException(tuple.second.at(0), tuple.second.at(1), 
				"Error: An input event cannot be at the same time as an output event.");
		}

		if (!inputEvent) {
			//Output event
			auto testDeviceOutputEvent = std::make_shared<TestDevice::TestDeviceOutputEvent>(tuple.first);	//time
			
			for (auto& rawEvent : tuple.second) {
				
				if (rawEvent.value().getNumber() > 10) {
					throw STI::Engine::EventParsingException(rawEvent, 
					"The value " + rawEvent.value().print() + " exceeds the maximium allowed value for this channel. Max value is 10.");
				}
				testDeviceOutputEvent->addValue(rawEvent.channel(), rawEvent.value());	//attach values to event for use later
			}
			synchedEvents.push_back(testDeviceOutputEvent);
		}
		else {
			//Input event
			auto& rawEvent = tuple.second.front();	//There is only one event, since we enforced this rule (above) for input events.
			auto fileIndex = fileMeasurementIndex;
			if (rawEvent.channel() == 3) {
				fileMeasurementIndex++;
			}
			auto testDeviceInputEvent = std::make_shared<TestDevice::TestDeviceInputEvent>(tuple.first, this, fileIndex);	//time

			testDeviceInputEvent->addMeasurement(rawEvent);	// REQUIRED: The source RawEvent must be attached to the input event for
															// data to be properly saved later. Skipping this will result in a parse error.

			testDeviceInputEvent->exampleParameter = 2.5;	// Configre other event parameters, as needed...
			
			synchedEvents.push_back(testDeviceInputEvent);
		}
	}
}



// //////////////// TestDeviceOutputEvent //////////////////

// This subclass is used to specify the custom behavior controlling the hardware for each device output channel.

TestDevice::TestDeviceOutputEvent::TestDeviceOutputEvent(double time)
: STI::Engine::SynchronousEvent(time)
{
}

void TestDevice::TestDeviceOutputEvent::addValue(short channel, const STI::Utils::MixedValue& value)
{
	values[channel] = value;
}

void TestDevice::TestDeviceOutputEvent::loadEvent()
{
	// This function is called at the beginning of each shot, before any events are played.
	// Use this function to setup the hardware to prepare for hard timing playback.
	// For example, if this device requires values to be preloaded into some buffer on the hardware
	// (e.g., an FPGA, or an arbitrary waveform generator), this can be done here.

	// Add hardware loading code here...
	for (auto& v : values) {
		std::cout << "Loading channel #" << v.first << " with value " << v.second.getNumber() << "." << std::endl;
	}
}

void TestDevice::TestDeviceOutputEvent::playEvent()
{
	// This function will be called at time specified in the timing file.
	// Use this function to control the hardware to implement the change on the requested channel.

	int x;
	std::cout << "Press enter to simulate hardware trigger..." << std::endl;
	std::cin >> x;	//pause here to simulate wait for hard timing trigger

	// Add hardware play code here...
	for (auto& v : values) {
		std::cout << "Playing channel #" << v.first << " with value " << v.second.getNumber() << "." << std::endl;
	}
}

void TestDevice::TestDeviceOutputEvent::collectMeasurementData()
{
	// This function is called after playEvent() and is used to retrieve any measurement data.
	// The new data is then attached to this event so it can later be saved at the end of the shot.

	// In this case, there is no data to save for an output event.
}

void TestDevice::TestDeviceOutputEvent::stopEvent()
{
	// Custom behavior for when "stop" is called. 
	// Use this to interrupt the hardware and put it back to the desired idle state.
}



// //////////////// TestDeviceInputEvent //////////////////

// This subclass is used to control the hardware for the device's input channel.
// Note that the same event class can be used for both input and output events, if desired. In this 
// example they are separated for clarity.

TestDevice::TestDeviceInputEvent::TestDeviceInputEvent(double time, TestDevice* device, unsigned fileIndex)
: STI::Engine::SynchronousEventAdapter(time), localDevice(device), fileIndex(fileIndex)
{
}

void TestDevice::TestDeviceInputEvent::collectMeasurementData()
{
	// This function is called after playEvent() and is used to retrieve any measurement data.
	// The new data is then attached to this event so it can later be saved at the end of the shot.

	if (getMeasurements().empty() || getMeasurements().front() == 0) {
		return;
	}

	auto measurement = getMeasurements().front();

	if (measurement->channel() == 3) {
		std::shared_ptr<STI::Device::PersistenceManager> persistenceManager;

		if (localDevice == 0 || !localDevice->getPersistenceManager(persistenceManager) || persistenceManager == 0) {
			addError("Unable to create virtual file");
			return;
		}

		STI::Utils::FileID fileID;
		fileID.origin = localDevice->getID().getID();
		fileID.path = "parseEvents";
		fileID.filename = "file_measurement_" + std::to_string(fileIndex) + ".txt";

		auto file = persistenceManager->makeVirtualFileHolder(fileID);
		if (file == 0 || !file->openFile()) {
			addError("Unable to open virtual file");
			return;
		}

		std::ostringstream text;
		text << "Example file measurement from " << localDevice->getID().getID() << "\n";
		text << "event time ns: " << std::fixed << std::setprecision(0) << getTime() << "\n";
		text << "sample value: " << (3.6 * exampleParameter) << "\n";

		const auto payload = text.str();
		if (!file->write(payload.data(), static_cast<unsigned>(payload.size()))) {
			file->closeFile();
			addError("Unable to write virtual file");
			return;
		}

		file->closeFile();
		attachFile(file);

		STI::Utils::MixedValue simulatedData(file->getID());
		setMeasurementResult(simulatedData);
		return;
	}

	STI::Utils::MixedValue simulatedData;
	simulatedData.setValue(3.6 * exampleParameter);	//This value should be set using the actual data retrieved from the hardware!

	setMeasurementResult(simulatedData);
}
