#include <sti/sti.h>
#include <sti/LocalDevice.h>

#include <memory>
#include <fstream>


using STI::Device::LocalDevice;
using STI::Utils::Configuration;
using STI::Network::NetworkDeviceHub;
using STI::Engine::SynchronousEventAdapter;


class TestDevice : public LocalDevice
{
public:

	TestDevice(const Configuration& config) : LocalDevice(config)
	{
		addInputChannel(0, STI::Utils::MixedValueType::File, "");
	}

	void parseEvents(const STI::Engine::RawEventMap& eventsIn, STI::Engine::SynchronousEventVector& synchedEvents)
	{
		for (auto& evts : eventsIn) {
			if (evts.second.at(0).channel() == 0) {
				auto testDeviceEvent = std::make_shared<TestDeviceEvent>(evts.second.at(0).time(), "data.txt", this);
				testDeviceEvent->addMeasurement(evts.second.at(0));

				synchedEvents.push_back(testDeviceEvent);
			}
		}
	}


	//Custom event class
	class TestDeviceEvent : public SynchronousEventAdapter
	{
	public:

		TestDeviceEvent(double time, const std::string& filename, LocalDevice* device) 
			: SynchronousEventAdapter(time), filename(filename), device(device) {}

		void collectMeasurementData()
		{
			//Example of file data generated by event
			std::ofstream file(filename, std::ifstream::binary | std::ios::ate);
			file << "Test data." << std::endl;	//arbitrary data

			auto fileHolder = device->makeFileHolder("", filename);
			attachFile(fileHolder);

			getMeasurements().at(0)->setMeasurementResult(fileHolder->getID());
		}

	private:

		LocalDevice* device;
		std::string filename;
	};

};


int main(int argc, char** argv)
{
	Configuration config({
		{"Device Name", "TestDevice"}, 
		{"IP Address", "localhost"}, 
		{"Module", "0"},
		{"Target Server", "localhost/0/STI Server"}});

	auto device = std::make_shared<TestDevice>(config);

	std::string nameServiceAddr = "192.168.1.14:2809";   //OmniORB NameService
	auto hub = std::make_shared<NetworkDeviceHub>(nameServiceAddr);

	STI::Utils::MixedValue data;
	device->read(0, STI::Utils::MixedValueType::Empty, data);

	hub->addDevice(device);
	hub->run();     	//blocks until ctrl-c or Device terminates
	hub->shutdown();

	return 0;
}
