/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.stanford.testdevice;

import edu.stanford.sti.STI;
import edu.stanford.sti.JNetworkDeviceHub;

import edu.stanford.testdevice.TestJDevice;


public class TestDeviceApplication {


    public static void main(String[] args) {
        
        System.out.println("Hello");
//    STI sti = new STI();

        STI.LoadLibrary();
        //STI.Reload();
	
//        TestJDevice testDevice = new TestJDevice("Java Dev", "localhost", 0, "localhost/0/dev0");
        TestJDevice testDevice = new TestJDevice("devJava", "localhost", 0, "localhost/0/STI Server");    
        
        JNetworkDeviceHub hub = new JNetworkDeviceHub("192.168.1.4:2809");
        hub.addNode(testDevice);

        hub.run();
        
    }
}
