/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JDeviceEventDispatcher {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected JDeviceEventDispatcher(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JDeviceEventDispatcher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JDeviceEventDispatcher(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JDeviceEventDispatcher(SWIGTYPE_p_std__shared_ptrT_STI__Device__DeviceEventDispatcher_t dispatcher) {
    this(stiJNI.new_JDeviceEventDispatcher(SWIGTYPE_p_std__shared_ptrT_STI__Device__DeviceEventDispatcher_t.getCPtr(dispatcher)), true);
  }

  public void addEvent(DeviceEvent evt) {
    stiJNI.JDeviceEventDispatcher_addEvent(swigCPtr, this, DeviceEvent.getCPtr(evt), evt);
  }

  public void clearEvents() {
    stiJNI.JDeviceEventDispatcher_clearEvents(swigCPtr, this);
  }

}
