/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.stanford.sti;

public class JDeviceGraphNode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JDeviceGraphNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JDeviceGraphNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        stiJNI.delete_JDeviceGraphNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JDeviceGraphNode(SWIGTYPE_p_STI__Network__DirectedGraphNodeT_STI__Device__DeviceID_STI__Device__Device_t deviceNode) {
    this(stiJNI.new_JDeviceGraphNode(SWIGTYPE_p_STI__Network__DirectedGraphNodeT_STI__Device__DeviceID_STI__Device__Device_t.getCPtr(deviceNode)), true);
  }

  public DeviceID getID() {
    return new DeviceID(stiJNI.JDeviceGraphNode_getID(swigCPtr, this), false);
  }

  public JDevice getNode() {
    return new JDevice(stiJNI.JDeviceGraphNode_getNode(swigCPtr, this), true);
  }

  public DeviceIDset getOutConnections() {
    return new DeviceIDset(stiJNI.JDeviceGraphNode_getOutConnections(swigCPtr, this), false);
  }

}
