c_compiler_version:      # [linux]
  - 15                   # [linux]
cxx_compiler_version:    # [linux]
  - 15                   # [linux]
c_stdlib_version:        # [linux]
  - "2.17"               # [linux]
