{% set version_data = load_file_data('../sti3_version.json', from_recipe_dir=True) %}
{% set requested_build_type = environ.get('STI3_CONDA_BUILD_TYPE', 'Release') %}
{% set requested_build_type_lower = requested_build_type | lower %}
{% set build_flavor = 'rdbg' if requested_build_type_lower == 'relwithdebinfo' else 'release' %}
{% set build_number = version_data.get('build_number', 0) | int %}

package:
  name: stipy
  version: "{{ version_data.get('version') }}"

source:
  path: ..

build:
  number: {{ build_number }}
  string: "{{ build_flavor }}_py{{ py }}h{{ PKG_HASH }}_{{ build_number }}"
  script_env:
    - STI3_CONDA_BUILD_TYPE

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - python
    - pip
    - pybind11           # for headers/cmake config
    - omniorb            # for omniidl during IDL stub generation
    - vs2022_win-64      # [win]
    # - openssl
  host:
    - python
    - openssl
    - curl 
    - boost-cpp
    - omniorb 
    - catch2
  run:
    # - libgcc             # [linux]
    # - libstdcxx          # [linux]
    - omniorb-libs          # use the conda package instead of vendoring
    - python
    - openssl
    - curl
    # - boost-cpp
    - vc14_runtime       # [win]
    
# test:
#   commands:
#     - ctest --test-dir build --output-on-failure


# test:
#   commands:
#     - test -d "$PREFIX/include/stipy"                                  # [unix]
#     - test -f "$PREFIX/lib/cmake/stipy/stipyConfig.cmake"              # [unix]
#     - python -c "import stipy; print('ok')"                            # [unix]
#     - if not exist %PREFIX%\\Library\\include\\stipy exit 1            # [win]
#     - if not exist %PREFIX%\\Library\\lib\\cmake\\stipy\\stipyConfig.cmake exit 1  # [win]
