package:
  name: stipy
  version: "3.0.1"

source:
  path: ..

build:
  number: 112

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - python
    - pip
    - pybind11           # for headers/cmake config
    - vs2022_win-64      # [win]
    # - openssl
  host:
    - python
    - openssl
    - curl 
    - boost-cpp
    - omniorb 
    - catch2
  run:
    # - libgcc             # [linux]
    # - libstdcxx          # [linux]
    - omniorb-libs          # use the conda package instead of vendoring
    - python
    - openssl
    - curl
    # - boost-cpp
    - vc14_runtime       # [win]
    
# test:
#   commands:
#     - ctest --test-dir build --output-on-failure


# test:
#   commands:
#     - test -d "$PREFIX/include/stipy"                                  # [unix]
#     - test -f "$PREFIX/lib/cmake/stipy/stipyConfig.cmake"              # [unix]
#     - python -c "import stipy; print('ok')"                            # [unix]
#     - if not exist %PREFIX%\\Library\\include\\stipy exit 1            # [win]
#     - if not exist %PREFIX%\\Library\\lib\\cmake\\stipy\\stipyConfig.cmake exit 1  # [win]
