#ifndef STI_NETWORK_NETWORKDEVICEWRAPPER_H
#define STI_NETWORK_NETWORKDEVICEWRAPPER_H

#include "Device.h"
#include "TDevice_i.h"

#include "orbTypes.h"

#include <memory>

namespace STI
{
namespace Network
{


//ACTUALLY this doesn't work, since the Hub can't resolve the child class.  Not possible to know when
//to send a servant reference with this approach...

//WAIT: Maybe this could be generated by the TDeviceHub_i servant.  When a remote call to distribute
//comes in (with a corba reference), we need to wrap 

//thin wrapper around a LocalDevice that also holds a TDevice_i servant of the same Device
class NetworkDeviceWrapper : public STI::Device::Device
{
public:

	NetworkDeviceWrapper(const std::shared_ptr<STI::Device::Device>& device)
		: localDevice(device), deviceServant(device) 
	{
	}

	void write(unsigned input) { localDevice->write(input); }
	bool refresh() { return localDevice->refresh(); }

//	STI::TNetwork::TDevice_ptr getTDeviceReference() { return deviceServant._this(); }

	static bool getTDeviceReference(const typename std::shared_ptr<STI::Device::Device>& device, STI::TNetwork::TDevice_ptr& tDevice)
	{
		std::shared_ptr<NetworkDeviceWrapper> networkDeviceWrapper;
		networkDeviceWrapper = std::dynamic_pointer_cast<NetworkDeviceWrapper>(device);

		if (networkDeviceWrapper) {		//check dynamic_pointer_cast
			//tDevice = networkDeviceWrapper->getTDeviceReference();
			tDevice = networkDeviceWrapper->deviceServant._this();
		}
		return (tDevice != 0 && !tDevice->_is_nil());
	}

private:

	std::shared_ptr<STI::Device::Device> localDevice;
	STI::TNetwork::TDevice_i deviceServant;
};


} //Network
} //STI


#endif

