import stipy
import stipy.stidevicepy as stidevicepy


class TestDevice(stidevicepy.LocalDevice):
    def __init__(self, config):
        stidevicepy.LocalDevice.__init__(self, config)

        # *** Define channels *** #

        # Output channels (the device's output actuators)
        self.addOutputChannel(0, stipy.MixedValueType.Double, "coil current")       #outputs a Double
        self.addOutputChannel(1, stipy.MixedValueType.Number, "supply voltage")     #outputs a number

        # Input channels (make measurements that are recorded by the device)
        self.addInputChannel(2, stipy.MixedValueType.Number, "thermocouple voltage")    #measures a number

        return
    
    def parseEvents(self, eventsIn, synchedEvents):

        # eventsIn type: Dict[float, List[stipy.RawEvent]]
        # synchedEvents type: stidevicepy.SynchronousEventVector

        # * RawEvent: Event class containing a high-level description of the event information: (time, channel, value).
        # * SynchronousEvent: User defined event class responsible for implementing the event on the hardware.

        # The parseEvents function must convert the RawEvents generated by the timing file into a list of SynchronousEvents
        # that are ready to play on the hardware.

        # * eventsIn is of type Dict[float, List[stipy.RawEvent]]
        # The key of each dict entry is the time (float) of the event(s). The value of each entry is a list of RawEvents
        # that are scheduled to occur at this time. In general, multiple events can occur at the same time, as long as they are
        # on distinct channels. It is the job of this function to parse this event information and generate a hardware-level
        # event (SynchronousEvent) capable of implementing the desired changes on the channel(s) specified by the RawEvent(s).
        # 'SynchronousEvent' is called 'synchronous' because all hardware changes on the channels are scheduled to occur at 
        # the same time for each SynchronousEvent. The grouping of RawEvent by their common time in the dictionary helps with this.

        # * synchedEvents is (conceptually) of type List[stidevicepy.SynchronousEvent]. In practice it has (list-like) type SynchronousEventVector.
        # SynchronousEvent itself is an abstract class, and so it first must be implemented by an appropriate derived class that  
        # includes the hardware-specific implementation details. Instances of this custom derived class should then be added 
        # to the synchedEvents list.

        for time, events in eventsIn.items():
            # Here 'tuple' is of type { time, list[RawEvent] }, where the list is the set of events at this time.
            inputEvent = False

            #check for input event
            for evt in events:
                if evt.isMeasurementEvent():
                    print("isMeasurementEvent")
                    inputEvent = True
                    break


            for evt in events:
                testEvent = TestDeviceOutputEvent(time)
                testEvent.addMeasurement(evt)

                synchedEvents.append(testEvent)

        return


class TestDeviceOutputEvent(stidevicepy.SynchronousEvent):
    def __init__(self, time):
        stidevicepy.SynchronousEvent.__init__(self, time)
        self.values = {}

    def addValue(self, channel, value):
        # Collect all values scheduled to play at this time so that can be play (psuedo) synchronously
        self.values[channel] = value

    def loadEvent(self):
        # This function is called at the beginning of each shot, before any events are played.
        # Use this function to setup the hardware to prepare for hard timing playback.
        # For example, if this device requires values to be preloaded into some buffer on the hardware
        # (e.g., an FPGA, or an arbitrary waveform generator), this can be done here.
        for channel, value in self.values.items():
            print("Loading channel #" << channel << " with value " << value.getNumber() << ".")
        return
    
    def collectMeasurementData(self):
        print("collectMeasurementData:")
        tmpMeas=self.getMeasurements()
        print(tmpMeas)
        for m in tmpMeas:
            # val=stidevicepy.MixedValue(123)
            # m.setMeasurementResult(val)
            m.setMeasurementResult(321)
        return
    def stopEvent(self):
        return
    def pauseEvent(self):
        return
    def unpauseEvent(self, retrigger):
        return
    def playEvent(self):
        print("Custom play event!")
        return

