# Example ConfigFile

[NetworkHub]

NameService = 192.168.1.242:2809     # address:port of omniORB NameService

[omniORB]

traceLevel = 0                       # omniORB trace level
endPointPublish = giop:tcp:192.168.1.247:

# Configuration parameters for multiple devices can be placed in the same ConfigFile

[TestDevice1]   # Parameters for device 1

Device Name = TestDevice1
IP Address = localhost 
Module = 0
Target Server = sr-magis/2/Frame2

[TestDevice1.SetupData]	#subsection for device 1
x = 23
y = 45.3

example = [1, 3.7, 5]     # square brackets denote a list of parameters

# parameter lists can also be specified using multiple lines
states = high
       = medium
       = low


[TestDevice2]   # Parameters for device 2

Device Name = TestDevice2
IP Address = localhost 
Module = 0
Target Server = sr-magis/2/Frame2

