# Example Server configuration file

Device Name = Frame2
IP Address = sr-magis 
Module = 2
Target Server = root

[NetworkHub]

NameService = 192.168.1.242:2809     # address:port of omniORB NameService

[omniORB]

traceLevel = 0                       # omniORB trace level
endPointPublish = giop:tcp:192.168.1.247:

[Shot Repository]   # where shots are stored

Path = .sti/server1

