# Example Server configuration file

Device Name = Frame2
IP Address = sr-magis 
Module = 2
Target Server = root

EnableActivate = true
EnableDeactivate = true

[NetworkHub]

NameService = 192.168.88.252:2809     # address:port of omniORB NameService
SelfRebind = true
SelfRebindIntervalSeconds = 30
EnablePrune = true
PruneScope = OwnIncomingSubtree
PruneIntervalSeconds = 300
PruneFailureThreshold = 3
PruneSuspectSeconds = 600

[omniORB]

traceLevel = 0                       # omniORB trace level
endPoint = giop:tcp:192.168.88.252:2811
endPointPublish = giop:tcp:192.168.88.252:2811
clientConnectTimeOutPeriod = 200
clientCallTimeOutPeriod    = 3000
scanGranularity            = 1

[EngineManager]

PlayReady Timeout ms = 2000
Trigger Timeout ms = 2000
PlayComplete Grace ms = 2000

[EventScheduler]

Sequence Mode = Normal


[Metadata]

test = 123
color = blue


[Shot Repository]   # where shots are stored

Path = .sti/server1
