// This file is generated by omniidl (C++ backend) - omniORB_4_2. Do not edit.

#include "deviceNet.h"

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_dyn_library_version = omniORB_4_2_dyn;

static ::CORBA::TypeCode::_Tracker _0RL_tcTrack(__FILE__);

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace STI { namespace TNetwork { 
  const ::CORBA::TypeCode_ptr _tc_TDeviceHub = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TDeviceHub:1.0", "TDeviceHub", &_0RL_tcTrack);
} } 
#else
const ::CORBA::TypeCode_ptr STI::TNetwork::_tc_TDeviceHub = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TDeviceHub:1.0", "TDeviceHub", &_0RL_tcTrack);
#endif

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace STI { namespace TNetwork { 
  const ::CORBA::TypeCode_ptr _tc_TDeviceCollection = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TDeviceCollection:1.0", "TDeviceCollection", &_0RL_tcTrack);
} } 
#else
const ::CORBA::TypeCode_ptr STI::TNetwork::_tc_TDeviceCollection = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TDeviceCollection:1.0", "TDeviceCollection", &_0RL_tcTrack);
#endif

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace STI { namespace TNetwork { 
  const ::CORBA::TypeCode_ptr _tc_TRefreshIndicator = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TRefreshIndicator:1.0", "TRefreshIndicator", &_0RL_tcTrack);
} } 
#else
const ::CORBA::TypeCode_ptr STI::TNetwork::_tc_TRefreshIndicator = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TRefreshIndicator:1.0", "TRefreshIndicator", &_0RL_tcTrack);
#endif

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace STI { namespace TNetwork { 
  const ::CORBA::TypeCode_ptr _tc_TDeviceEventHandler = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TDeviceEventHandler:1.0", "TDeviceEventHandler", &_0RL_tcTrack);
} } 
#else
const ::CORBA::TypeCode_ptr STI::TNetwork::_tc_TDeviceEventHandler = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TDeviceEventHandler:1.0", "TDeviceEventHandler", &_0RL_tcTrack);
#endif

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace STI { namespace TNetwork { 
  const ::CORBA::TypeCode_ptr _tc_TDeviceEventDispatcher = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TDeviceEventDispatcher:1.0", "TDeviceEventDispatcher", &_0RL_tcTrack);
} } 
#else
const ::CORBA::TypeCode_ptr STI::TNetwork::_tc_TDeviceEventDispatcher = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TDeviceEventDispatcher:1.0", "TDeviceEventDispatcher", &_0RL_tcTrack);
#endif

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace STI { namespace TNetwork { 
  const ::CORBA::TypeCode_ptr _tc_TDevice = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TDevice:1.0", "TDevice", &_0RL_tcTrack);
} } 
#else
const ::CORBA::TypeCode_ptr STI::TNetwork::_tc_TDevice = CORBA::TypeCode::PR_interface_tc("IDL:STI/TNetwork/TDevice:1.0", "TDevice", &_0RL_tcTrack);
#endif

static void _0RL_STI_mTNetwork_mTDeviceHub_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_STI_mTNetwork_mTDeviceHub_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(STI::TNetwork::TDeviceHub::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_STI_mTNetwork_mTDeviceHub_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, STI::TNetwork::TDeviceHub_ptr _o)
{
  STI::TNetwork::TDeviceHub_ptr _no = STI::TNetwork::TDeviceHub::_duplicate(_o);
  _a.PR_insert(STI::TNetwork::_tc_TDeviceHub,
               _0RL_STI_mTNetwork_mTDeviceHub_marshal_fn,
               _0RL_STI_mTNetwork_mTDeviceHub_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, STI::TNetwork::TDeviceHub_ptr* _op)
{
  _a.PR_insert(STI::TNetwork::_tc_TDeviceHub,
               _0RL_STI_mTNetwork_mTDeviceHub_marshal_fn,
               _0RL_STI_mTNetwork_mTDeviceHub_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = STI::TNetwork::TDeviceHub::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, STI::TNetwork::TDeviceHub_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(STI::TNetwork::_tc_TDeviceHub,
                    _0RL_STI_mTNetwork_mTDeviceHub_unmarshal_fn,
                    _0RL_STI_mTNetwork_mTDeviceHub_marshal_fn,
                    _0RL_STI_mTNetwork_mTDeviceHub_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (STI::TNetwork::TDeviceHub_ptr)_r->_ptrToObjRef(STI::TNetwork::TDeviceHub::_PD_repoId);
    else
      _o = STI::TNetwork::TDeviceHub::_nil();
    return 1;
  }
  return 0;
}

static void _0RL_STI_mTNetwork_mTDeviceCollection_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_STI_mTNetwork_mTDeviceCollection_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(STI::TNetwork::TDeviceCollection::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_STI_mTNetwork_mTDeviceCollection_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, STI::TNetwork::TDeviceCollection_ptr _o)
{
  STI::TNetwork::TDeviceCollection_ptr _no = STI::TNetwork::TDeviceCollection::_duplicate(_o);
  _a.PR_insert(STI::TNetwork::_tc_TDeviceCollection,
               _0RL_STI_mTNetwork_mTDeviceCollection_marshal_fn,
               _0RL_STI_mTNetwork_mTDeviceCollection_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, STI::TNetwork::TDeviceCollection_ptr* _op)
{
  _a.PR_insert(STI::TNetwork::_tc_TDeviceCollection,
               _0RL_STI_mTNetwork_mTDeviceCollection_marshal_fn,
               _0RL_STI_mTNetwork_mTDeviceCollection_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = STI::TNetwork::TDeviceCollection::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, STI::TNetwork::TDeviceCollection_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(STI::TNetwork::_tc_TDeviceCollection,
                    _0RL_STI_mTNetwork_mTDeviceCollection_unmarshal_fn,
                    _0RL_STI_mTNetwork_mTDeviceCollection_marshal_fn,
                    _0RL_STI_mTNetwork_mTDeviceCollection_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (STI::TNetwork::TDeviceCollection_ptr)_r->_ptrToObjRef(STI::TNetwork::TDeviceCollection::_PD_repoId);
    else
      _o = STI::TNetwork::TDeviceCollection::_nil();
    return 1;
  }
  return 0;
}

static void _0RL_STI_mTNetwork_mTRefreshIndicator_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_STI_mTNetwork_mTRefreshIndicator_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(STI::TNetwork::TRefreshIndicator::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_STI_mTNetwork_mTRefreshIndicator_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, STI::TNetwork::TRefreshIndicator_ptr _o)
{
  STI::TNetwork::TRefreshIndicator_ptr _no = STI::TNetwork::TRefreshIndicator::_duplicate(_o);
  _a.PR_insert(STI::TNetwork::_tc_TRefreshIndicator,
               _0RL_STI_mTNetwork_mTRefreshIndicator_marshal_fn,
               _0RL_STI_mTNetwork_mTRefreshIndicator_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, STI::TNetwork::TRefreshIndicator_ptr* _op)
{
  _a.PR_insert(STI::TNetwork::_tc_TRefreshIndicator,
               _0RL_STI_mTNetwork_mTRefreshIndicator_marshal_fn,
               _0RL_STI_mTNetwork_mTRefreshIndicator_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = STI::TNetwork::TRefreshIndicator::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, STI::TNetwork::TRefreshIndicator_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(STI::TNetwork::_tc_TRefreshIndicator,
                    _0RL_STI_mTNetwork_mTRefreshIndicator_unmarshal_fn,
                    _0RL_STI_mTNetwork_mTRefreshIndicator_marshal_fn,
                    _0RL_STI_mTNetwork_mTRefreshIndicator_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (STI::TNetwork::TRefreshIndicator_ptr)_r->_ptrToObjRef(STI::TNetwork::TRefreshIndicator::_PD_repoId);
    else
      _o = STI::TNetwork::TRefreshIndicator::_nil();
    return 1;
  }
  return 0;
}

static void _0RL_STI_mTNetwork_mTDeviceEventHandler_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_STI_mTNetwork_mTDeviceEventHandler_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(STI::TNetwork::TDeviceEventHandler::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_STI_mTNetwork_mTDeviceEventHandler_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, STI::TNetwork::TDeviceEventHandler_ptr _o)
{
  STI::TNetwork::TDeviceEventHandler_ptr _no = STI::TNetwork::TDeviceEventHandler::_duplicate(_o);
  _a.PR_insert(STI::TNetwork::_tc_TDeviceEventHandler,
               _0RL_STI_mTNetwork_mTDeviceEventHandler_marshal_fn,
               _0RL_STI_mTNetwork_mTDeviceEventHandler_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, STI::TNetwork::TDeviceEventHandler_ptr* _op)
{
  _a.PR_insert(STI::TNetwork::_tc_TDeviceEventHandler,
               _0RL_STI_mTNetwork_mTDeviceEventHandler_marshal_fn,
               _0RL_STI_mTNetwork_mTDeviceEventHandler_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = STI::TNetwork::TDeviceEventHandler::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, STI::TNetwork::TDeviceEventHandler_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(STI::TNetwork::_tc_TDeviceEventHandler,
                    _0RL_STI_mTNetwork_mTDeviceEventHandler_unmarshal_fn,
                    _0RL_STI_mTNetwork_mTDeviceEventHandler_marshal_fn,
                    _0RL_STI_mTNetwork_mTDeviceEventHandler_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (STI::TNetwork::TDeviceEventHandler_ptr)_r->_ptrToObjRef(STI::TNetwork::TDeviceEventHandler::_PD_repoId);
    else
      _o = STI::TNetwork::TDeviceEventHandler::_nil();
    return 1;
  }
  return 0;
}

static void _0RL_STI_mTNetwork_mTDeviceEventDispatcher_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_STI_mTNetwork_mTDeviceEventDispatcher_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(STI::TNetwork::TDeviceEventDispatcher::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_STI_mTNetwork_mTDeviceEventDispatcher_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, STI::TNetwork::TDeviceEventDispatcher_ptr _o)
{
  STI::TNetwork::TDeviceEventDispatcher_ptr _no = STI::TNetwork::TDeviceEventDispatcher::_duplicate(_o);
  _a.PR_insert(STI::TNetwork::_tc_TDeviceEventDispatcher,
               _0RL_STI_mTNetwork_mTDeviceEventDispatcher_marshal_fn,
               _0RL_STI_mTNetwork_mTDeviceEventDispatcher_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, STI::TNetwork::TDeviceEventDispatcher_ptr* _op)
{
  _a.PR_insert(STI::TNetwork::_tc_TDeviceEventDispatcher,
               _0RL_STI_mTNetwork_mTDeviceEventDispatcher_marshal_fn,
               _0RL_STI_mTNetwork_mTDeviceEventDispatcher_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = STI::TNetwork::TDeviceEventDispatcher::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, STI::TNetwork::TDeviceEventDispatcher_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(STI::TNetwork::_tc_TDeviceEventDispatcher,
                    _0RL_STI_mTNetwork_mTDeviceEventDispatcher_unmarshal_fn,
                    _0RL_STI_mTNetwork_mTDeviceEventDispatcher_marshal_fn,
                    _0RL_STI_mTNetwork_mTDeviceEventDispatcher_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (STI::TNetwork::TDeviceEventDispatcher_ptr)_r->_ptrToObjRef(STI::TNetwork::TDeviceEventDispatcher::_PD_repoId);
    else
      _o = STI::TNetwork::TDeviceEventDispatcher::_nil();
    return 1;
  }
  return 0;
}

static void _0RL_STI_mTNetwork_mTDevice_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_STI_mTNetwork_mTDevice_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(STI::TNetwork::TDevice::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_STI_mTNetwork_mTDevice_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, STI::TNetwork::TDevice_ptr _o)
{
  STI::TNetwork::TDevice_ptr _no = STI::TNetwork::TDevice::_duplicate(_o);
  _a.PR_insert(STI::TNetwork::_tc_TDevice,
               _0RL_STI_mTNetwork_mTDevice_marshal_fn,
               _0RL_STI_mTNetwork_mTDevice_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, STI::TNetwork::TDevice_ptr* _op)
{
  _a.PR_insert(STI::TNetwork::_tc_TDevice,
               _0RL_STI_mTNetwork_mTDevice_marshal_fn,
               _0RL_STI_mTNetwork_mTDevice_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = STI::TNetwork::TDevice::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, STI::TNetwork::TDevice_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(STI::TNetwork::_tc_TDevice,
                    _0RL_STI_mTNetwork_mTDevice_unmarshal_fn,
                    _0RL_STI_mTNetwork_mTDevice_marshal_fn,
                    _0RL_STI_mTNetwork_mTDevice_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (STI::TNetwork::TDevice_ptr)_r->_ptrToObjRef(STI::TNetwork::TDevice::_PD_repoId);
    else
      _o = STI::TNetwork::TDevice::_nil();
    return 1;
  }
  return 0;
}

