#ifndef STI_ENGINE_EVENTENGINE_H
#define STI_ENGINE_EVENTENGINE_H

#include "EventEngineParser.h"
#include "EventEngineStateMachine.h"
#include "ParserCallback.h"
#include "ParseID.h"
#include "ResultTicket.h"
#include "ShotID.h"
#include "TimeStamp.h"
#include "TriggerCallback.h"
#include "utils/OrderedBufferMap.h"

#include "fwd/Channel_fwd.h"
#include "fwd/DeviceEventParser_fwd.h"
#include "fwd/DeviceID_fwd.h"
#include "fwd/Measurement_fwd.h"
#include "fwd/RawEvent_fwd.h"
#include "fwd/SynchronousEvent_fwd.h"

#include <memory>
#include <mutex>

namespace STI
{
namespace Engine
{

class EventEngine;


class EventTime
{
	EventTime(double time);
};


class EventEngine : public ParserCallbackTarget
{
public:

	EventEngine(
		const STI::Device::DeviceID& localID, 
		STI::Device::ChannelMap& channels, 
		DeviceEventParser* deviceParser);
	~EventEngine();

	void clear();
	void parse(const ParseID& parseID, const RawEventVector& events, const ParserCallback& cb);
	bool play(const ParseID& parseID, TriggerCallback& triggerCB, ResultTicket& resultsOut, bool debug = false);	//ticket is a callback that will fire when results are ready;  playCB could push event number
	void trigger();
	void trigger(STI::Device::DeviceID& target);		//triggers just target
	void stop();

	void pause();
	void unpause(bool retrigger);		//if retrigger, require a trigger before resuming (allows hard time resume)

	//debugging; separate class?
//	void addBreakpoint(time);
//	void clearBreakpoints();
//	void getBreakpoints(ids);
//	id getBreakpointAt(time);
//	void removeBreakpoint(id);
//	void getResults();

	bool isState(EngineState target) const;
	STI::Engine::EngineState getState() const;

	//Local device details
	const STI::Device::DeviceID& localDeviceID;	//The DeviceID of the host of this engine
	STI::Device::ChannelMap& localChannels;

private:

	bool setState(EngineState target);

	bool armTrigger(TriggerCallback& triggerCB);
	void waitForTrigger() const;

	void handleParsingResults(const ParserCallbackMessage& message);	//ParserCallbackTarget interface
	
	bool playDeviceEvents();
	void measureData();
	void stopDeviceEvents();

	bool waitUntil(double time);

	//Clock time;

	STI::Engine::ParseID lastParseID;		//The ID of the most recently parsed shot

	EventEngineStateMachine stateMachine;
	EventEngineParser parser;
	
	RawEventMap& rawEvents;					//Originating from python timing file (STIpy library)
	SynchronousEventVector synchedEvents;	//Generated by device specific parseDeviceEvents()
	DeviceEventMap& partnerEvents;

	//Each ShotID refers to a single shot's measurement vector.
	STI::Utils::OrderedBufferMap<ShotID, std::shared_ptr<MeasurementVector>> measurementBuffer;

	//trigger
	mutable std::mutex triggerMutex;
	mutable std::condition_variable triggerCondition;

};

} //Engine
} //STI

#endif
