/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_sti_WRAP_H_
#define SWIG_sti_WRAP_H_

class SwigDirector_FileHolder : public STI::Utils::FileHolder, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_FileHolder(JNIEnv *jenv);
    virtual ~SwigDirector_FileHolder();
    virtual std::string getFilename() const;
    virtual bool exists() const;
    virtual bool transferFile(std::shared_ptr< STI::Utils::FileHolder > const &destination);
    virtual unsigned int maxBufferSize() const;
    virtual bool deleteFile();
    virtual std::string md5Checksum();
    virtual bool write(char const *buffer, unsigned int length);
    virtual bool openFile();
    virtual void closeFile();
public:
    bool swig_overrides(int n) {
      return (n < 6 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<6> swig_override;
};

class SwigDirector_MixedValue : public STI::Utils::MixedValue, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_MixedValue(JNIEnv *jenv);
    SwigDirector_MixedValue(JNIEnv *jenv, STI::Utils::MixedValue const &copy);
    SwigDirector_MixedValue(JNIEnv *jenv, STI::Utils::MixedValueType const &value);
    virtual ~SwigDirector_MixedValue();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_DeviceIDDependencyTree : public STI::Utils::DependencyTree< STI::Device::DeviceID >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_DeviceIDDependencyTree(JNIEnv *jenv);
    SwigDirector_DeviceIDDependencyTree(JNIEnv *jenv, std::set< STI::Device::DeviceID > const &nodes);
    SwigDirector_DeviceIDDependencyTree(JNIEnv *jenv, STI::Utils::DependencyTree< STI::Device::DeviceID > const &tree);
    virtual ~SwigDirector_DeviceIDDependencyTree();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_EventEngineDependencyTree : public STI::Engine::EventEngineDependencyTree, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EventEngineDependencyTree(JNIEnv *jenv);
    virtual ~SwigDirector_EventEngineDependencyTree();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_Attribute : public STI::Device::Attribute, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_Attribute(JNIEnv *jenv);
    virtual ~SwigDirector_Attribute();
    virtual std::string const &getKey() const;
    virtual std::string const &getValue() const;
    virtual std::vector< std::string > const &getAllowedValues() const;
    virtual std::string const &getGroup() const;
    virtual void refreshValue();
    virtual bool setValue(std::string const &value);
    virtual STI::Utils::MixedValue const &getMetaData() const;
    virtual STI::Utils::MixedValue getMetaData(std::string const &key) const;
public:
    bool swig_overrides(int n) {
      return (n < 8 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<8> swig_override;
};

class SwigDirector_AttributeRefresher : public STI::Device::AttributeRefresher, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_AttributeRefresher(JNIEnv *jenv);
    virtual ~SwigDirector_AttributeRefresher();
    virtual std::string refresh();
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_AttributeSetter : public STI::Device::AttributeSetter, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_AttributeSetter(JNIEnv *jenv);
    virtual ~SwigDirector_AttributeSetter();
    virtual bool set(std::string const &value);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_LocalAttribute : public STI::Device::LocalAttribute, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_LocalAttribute(JNIEnv *jenv, std::string const &key, std::string const &initalValue);
    SwigDirector_LocalAttribute(JNIEnv *jenv, std::string const &key, std::string const &initalValue, std::vector< std::string > const &allowedValues);
    virtual ~SwigDirector_LocalAttribute();
    virtual std::string const &getKey() const;
    virtual std::string const &getValue() const;
    virtual std::vector< std::string > const &getAllowedValues() const;
    virtual std::string const &getGroup() const;
    virtual void refreshValue();
    virtual bool setValue(std::string const &value);
    virtual STI::Utils::MixedValue const &getMetaData() const;
    virtual STI::Utils::MixedValue getMetaData(std::string const &key) const;
public:
    bool swig_overrides(int n) {
      return (n < 8 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<8> swig_override;
};

class SwigDirector_AttributeRefreshListener : public STI::Device::AttributeRefreshListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_AttributeRefreshListener(JNIEnv *jenv);
    virtual ~SwigDirector_AttributeRefreshListener();
    virtual void handleAttributeRefreshEvent(std::string const &key, std::string const &value);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_JDevice : public STI::Device::JDevice, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_JDevice(JNIEnv *jenv, std::string const &name, std::string const &address, unsigned short module, std::string const &targetServer);
    virtual ~SwigDirector_JDevice();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_DeviceMessage : public STI::Device::DeviceMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_DeviceMessage(JNIEnv *jenv);
    SwigDirector_DeviceMessage(JNIEnv *jenv, STI::Device::DeviceID const &source, STI::Device::DeviceMessageType type);
    SwigDirector_DeviceMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace, STI::Device::DeviceMessageType type);
    virtual ~SwigDirector_DeviceMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_RefreshDeviceMessage : public STI::Device::RefreshDeviceMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_RefreshDeviceMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace);
    virtual ~SwigDirector_RefreshDeviceMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_CollectionUpdateMessage : public STI::Device::CollectionUpdateMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_CollectionUpdateMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace);
    virtual ~SwigDirector_CollectionUpdateMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_ChannelUpdateMessage : public STI::Device::ChannelUpdateMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ChannelUpdateMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace);
    SwigDirector_ChannelUpdateMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace, short channel, STI::Utils::MixedValue const &value);
    SwigDirector_ChannelUpdateMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace, short channel, std::string const &name);
    virtual ~SwigDirector_ChannelUpdateMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_AttributeUpdateMessage : public STI::Device::AttributeUpdateMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_AttributeUpdateMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace);
    SwigDirector_AttributeUpdateMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace, std::string const &key, std::string const &value);
    virtual ~SwigDirector_AttributeUpdateMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_EngineJobUpdateDeviceMessage : public STI::Device::EngineJobUpdateDeviceMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineJobUpdateDeviceMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace);
    virtual ~SwigDirector_EngineJobUpdateDeviceMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_EngineSchedulerMessage : public STI::Device::EngineSchedulerMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineSchedulerMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace, STI::Device::EngineSchedulerMessage::SchedulerMessageType const &type);
    virtual ~SwigDirector_EngineSchedulerMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_EngineParserDeviceMessage : public STI::Device::EngineParserDeviceMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineParserDeviceMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace, STI::Engine::ParseID const &parseID);
    virtual ~SwigDirector_EngineParserDeviceMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_EngineStateMessage : public STI::Device::EngineStateMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineStateMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace);
    SwigDirector_EngineStateMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace, STI::Engine::EngineID const &engineID, STI::Engine::EngineState const &state);
    virtual ~SwigDirector_EngineStateMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_RefreshDeviceMessageListener : public STI::Device::DeviceMessageListener< STI::Device::RefreshDeviceMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_RefreshDeviceMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_RefreshDeviceMessageListener();
    virtual void handleMessage(std::shared_ptr< STI::Device::RefreshDeviceMessage > const &mess);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_ChannelUpdateMessageListener : public STI::Device::DeviceMessageListener< STI::Device::ChannelUpdateMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ChannelUpdateMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_ChannelUpdateMessageListener();
    virtual void handleMessage(std::shared_ptr< STI::Device::ChannelUpdateMessage > const &mess);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_AttributeUpdateMessageListener : public STI::Device::DeviceMessageListener< STI::Device::AttributeUpdateMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_AttributeUpdateMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_AttributeUpdateMessageListener();
    virtual void handleMessage(std::shared_ptr< STI::Device::AttributeUpdateMessage > const &mess);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_EngineSchedulerMessageListener : public STI::Device::DeviceMessageListener< STI::Device::EngineSchedulerMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineSchedulerMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_EngineSchedulerMessageListener();
    virtual void handleMessage(std::shared_ptr< STI::Device::EngineSchedulerMessage > const &mess);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_EngineParserDeviceMessageListener : public STI::Device::DeviceMessageListener< STI::Device::EngineParserDeviceMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineParserDeviceMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_EngineParserDeviceMessageListener();
    virtual void handleMessage(std::shared_ptr< STI::Device::EngineParserDeviceMessage > const &mess);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_CollectionUpdateMessageListener : public STI::Device::DeviceMessageListener< STI::Device::CollectionUpdateMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_CollectionUpdateMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_CollectionUpdateMessageListener();
    virtual void handleMessage(std::shared_ptr< STI::Device::CollectionUpdateMessage > const &mess);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_EngineStateMessageListener : public STI::Device::DeviceMessageListener< STI::Device::EngineStateMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineStateMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_EngineStateMessageListener();
    virtual void handleMessage(std::shared_ptr< STI::Device::EngineStateMessage > const &mess);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_EngineJobUpdateDeviceMessageListener : public STI::Device::DeviceMessageListener< STI::Device::EngineJobUpdateDeviceMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineJobUpdateDeviceMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_EngineJobUpdateDeviceMessageListener();
    virtual void handleMessage(std::shared_ptr< STI::Device::EngineJobUpdateDeviceMessage > const &mess);
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_JEngineJobUpdateDeviceMessage : public STI::Device::JEngineJobUpdateDeviceMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_JEngineJobUpdateDeviceMessage(JNIEnv *jenv, STI::Device::DeviceTrace const &trace);
    SwigDirector_JEngineJobUpdateDeviceMessage(JNIEnv *jenv, STI::Device::EngineJobUpdateDeviceMessage const &mess);
    virtual ~SwigDirector_JEngineJobUpdateDeviceMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_JEngineJobUpdateDeviceMessageListener : public STI::Device::JEngineJobUpdateDeviceMessageListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_JEngineJobUpdateDeviceMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_JEngineJobUpdateDeviceMessageListener();
    virtual void handleMessage(std::shared_ptr< STI::Device::EngineJobUpdateDeviceMessage > const &mess);
    virtual void handleJMessage(std::shared_ptr< STI::Device::JEngineJobUpdateDeviceMessage > const &mess);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_Channel : public STI::Device::Channel, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_Channel(JNIEnv *jenv);
    virtual ~SwigDirector_Channel();
    virtual short getChannelNumber() const;
    virtual STI::Device::ChannelType getType() const;
    virtual STI::Utils::MixedValueType getInputType() const;
    virtual STI::Utils::MixedValueType getOutputType() const;
    virtual void setChannelName(std::string const &name);
    virtual std::string getChannelName() const;
    virtual void saveLastValue(STI::Utils::MixedValue const &value);
    virtual STI::Utils::MixedValue const getLastValue() const;
    virtual STI::Utils::MixedValue const &getMetaData() const;
    virtual STI::Utils::MixedValue getMetaData(std::string const &key) const;
public:
    bool swig_overrides(int n) {
      return (n < 10 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<10> swig_override;
};

class SwigDirector_LocalChannel : public STI::Device::LocalChannel, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_LocalChannel(JNIEnv *jenv);
    SwigDirector_LocalChannel(JNIEnv *jenv, unsigned short channelNumber, STI::Device::ChannelType type, STI::Utils::MixedValueType inputType, STI::Utils::MixedValueType outputType, std::string const &defaultName);
    virtual ~SwigDirector_LocalChannel();
    virtual short getChannelNumber() const;
    virtual STI::Device::ChannelType getType() const;
    virtual STI::Utils::MixedValueType getInputType() const;
    virtual STI::Utils::MixedValueType getOutputType() const;
    virtual void setChannelName(std::string const &name);
    virtual std::string getChannelName() const;
    virtual void saveLastValue(STI::Utils::MixedValue const &value);
    virtual STI::Utils::MixedValue const getLastValue() const;
    virtual STI::Utils::MixedValue const &getMetaData() const;
    virtual STI::Utils::MixedValue getMetaData(std::string const &key) const;
public:
    bool swig_overrides(int n) {
      return (n < 10 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<10> swig_override;
};

class SwigDirector_ChannelRefreshListener : public STI::Device::ChannelRefreshListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ChannelRefreshListener(JNIEnv *jenv);
    virtual ~SwigDirector_ChannelRefreshListener();
    virtual void handleChannelRefreshEvent(short channelNumber, STI::Utils::MixedValue const &value);
    virtual void handleChannelNameRefreshEvent(short channelNumber, std::string const &name);
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};

class SwigDirector_SynchronousEvent : public STI::Engine::SynchronousEvent, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_SynchronousEvent(JNIEnv *jenv, double time);
    virtual ~SwigDirector_SynchronousEvent();
    virtual void waitBeforePlay();
    virtual void waitBeforeCollectData();
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};

class SwigDirector_SynchronousEventAdapter : public STI::Engine::SynchronousEventAdapter, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_SynchronousEventAdapter(JNIEnv *jenv, double time);
    virtual ~SwigDirector_SynchronousEventAdapter();
    virtual void waitBeforePlay();
    virtual void waitBeforeCollectData();
    virtual void loadEvent();
    virtual void playEvent();
    virtual void collectMeasurementData();
    virtual void stopEvent();
    virtual void pauseEvent();
    virtual void unpauseEvent(bool retrigger);
public:
    bool swig_overrides(int n) {
      return (n < 8 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<8> swig_override;
};

class SwigDirector_DeviceCollectionListener : public STI::Utils::LocalCollectionListenerAdapter< STI::Device::DeviceID >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_DeviceCollectionListener(JNIEnv *jenv);
    virtual ~SwigDirector_DeviceCollectionListener();
    virtual void add(STI::Device::DeviceID const &id);
    virtual void remove(STI::Device::DeviceID const &id);
    virtual void refresh();
public:
    bool swig_overrides(int n) {
      return (n < 3 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<3> swig_override;
};

class SwigDirector_JLocalDevice : public STI::Device::JLocalDevice, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_JLocalDevice(JNIEnv *jenv, std::string const &name, std::string const &address, unsigned short module, std::string const &targetServer);
    virtual ~SwigDirector_JLocalDevice();
    virtual void parseEvents(STI::Engine::RawEventMap const &events, std::vector< std::shared_ptr< STI::Engine::SynchronousEventAdapter > > &synchedEvents);
    virtual bool writeChannel(int channel, STI::Utils::MixedValue const &value);
    virtual STI::Utils::MixedValue readChannel(int channel, STI::Utils::MixedValue const &value);
public:
    bool swig_overrides(int n) {
      return (n < 3 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<3> swig_override;
};

class SwigDirector_ParseResult : public STI::Engine::ParseResult, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ParseResult(JNIEnv *jenv);
    virtual ~SwigDirector_ParseResult();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_DeviceIDIndexedGraph : public STI::Utils::IndexedGraph< STI::Device::DeviceID >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_DeviceIDIndexedGraph(JNIEnv *jenv);
    SwigDirector_DeviceIDIndexedGraph(JNIEnv *jenv, STI::Utils::DependencyTree< STI::Device::DeviceID > const &tree);
    virtual ~SwigDirector_DeviceIDIndexedGraph();
public:
    bool swig_overrides(int n) {
      return false;
    }
};


#endif
