#STI Device Configuration Parameters

Device Name = dev1
IP Address = localhost
Module = 0
Target Server = root

[omniORB]

traceLevel = 0
clientTransportRule = * tcp,bidir
offerBiDirectionalGIOP = 1
clientConnectTimeOutPeriod = 100

serverTransportRule = * tcp,bidir
acceptBiDirectionalGIOP = 1
endPoint = giop:tcp::12346
