#STI Device Configuration Parameters

Device Name = dev1
IP Address = localhost
Module = 0
; Target Server = localhost/0/BridgeServer
Target Server = localhost/0/STI Server

[omniORB]

traceLevel = 0
clientTransportRule = * tcp,bidir
offerBiDirectionalGIOP = 1
clientConnectTimeOutPeriod = 100

serverTransportRule = * tcp,bidir
acceptBiDirectionalGIOP = 1
endPoint = giop:tcp::12345
= giop:tcp::12349

#endPointPublish = giop:tcp::12349