#ifndef STI_TNETWORK_DEVICENET_IDL
#define STI_TNETWORK_DEVICENET_IDL

//IDL for the STI::Network::Hub<DeviceID, Device>
//Includes basic types for Network (Hubs, etc), utilities like DeviceCollector,
//and the Device interface.

#include "orbTypes.idl"
#include "logsNet.idl"
#include "tasks.idl"

module STI
{
module TNetwork
{

	interface TTestNetwork
	{
		boolean ping();
	};

	interface TDevice;	
	interface TDeviceHub;

	interface TDevice;

	struct TDeviceNode	//for NodeWalker
	{
		TDeviceID deviceID;
		TDevice node;
		TDeviceIDSeq outConnections;
	};
	typedef sequence<TDeviceNode> TDeviceNodeSeq;

	struct THubNode	//for NodeWalker
	{
		TDeviceHubID hubID;
		TDeviceNodeSeq nodes;
	};

	struct TNodeWalker;
	typedef sequence<TNodeWalker> TNodeWalkerSeq;

	struct TNodeWalker
	{
		THubNode node;
		TNodeWalkerSeq connections;
	};

	interface TDeviceHub
	{
		boolean addHub(in TDeviceHubID hubID, in TDeviceHub hub);
		boolean removeHub(in TDeviceHubID hubID);
	
		boolean refreshNetwork(in TDeviceHubTrace trace);

		boolean distribute(in TDeviceID devID, in TDevice node, in TDeviceHubTrace trace, in TDeviceHubID first);
		boolean distributeNodes(in TDeviceHubID targetHub);
		boolean redistributeNodes(in TDeviceHubTrace trace);
		boolean removeNode(in TDeviceID devID, in TDeviceHubTrace trace);

		readonly attribute TDeviceHubID deviceHubID;		//getID()

		boolean hasNodeID(in TDeviceID devID);

		void walk(inout TNodeWalker root, in TDeviceHubTrace trace);
	};

	interface TDeviceCollection
	{
		boolean add(in TDeviceID deviceID, in TDevice device);
		boolean remove(in TDeviceID deviceID);

		boolean contains(in TDeviceID deviceID);
		unsigned long size();

		boolean get(in TDeviceID deviceID, out TDevice device);
		void getIDs(out TDeviceIDSeq deviceIDseq);

		void cleanup();
		void clear();

		boolean ping();
	};

	interface TRefreshIndicator
	{
		void refresh();
	};

	interface TDeviceMessageHandler
	{
		void addMessage(in TAnyMessage mess);
		void clearMessages();

		readonly attribute TDeviceMessageTypeSeq listenersTypes;

		void setRefreshIndicator(in TRefreshIndicator refresher);
	};

	interface TDeviceMessageDispatcher
	{
		void addMessageHandler(in TDeviceID targetID, in TDeviceMessageHandler handler);
		void removeMessageHandler(in TDeviceID targetID);

		boolean ping();
	};

	interface TShotCallback
	{
		void getRootEventGroup(out TRawEventGroup rootGroup);
	};

	interface TEventEngine;

	
	interface TTriggerCallback
	{
		void ready(in TDeviceID id);
		void triggerFired(in TDeviceID id);
	};

	interface TFileServer;

	interface TResultsCollector
	{
		TShotID getShotID();

		boolean addMeasurements(in TDeviceID deviceID, in TMeasurementSeq measurements, in TFileServer sourceFileServer);
		boolean addAttributes(in TDeviceID deviceID, in TStringPairSeq attributes);
		boolean addMessages(in TEnginePlayingMessageSeq messages);
	};

	interface TEventEngine
	{
		void play(in TEventEngineJob job);
		void playCB(in TEngineJobID jobID, in TTriggerCallback triggerCB, in boolean debug);

		void trigger();
		void triggerTarget(in TDeviceID target);

		void stop();
		void pause();
		void unpause(in boolean retrigger);

		void clear();

    	TDeviceID getDeviceID();
		TEngineState getState();

		TEventEngineDependencyTree getParsedTree();
		boolean getParseResult(in TParseID parseID, out TParseResult parseResult);
	};

	interface TEventEngineDependencyParser
	{
		void getDependants(in TDeviceIDSeq evtTargets, inout TEventEngineDependencyTree tree, 
                                inout TDeviceIDSeq missingTargets, out TEngineParsingMessageSeq messages, in TDeviceTrace trace);
    
    	void addDeviceEventTargets(inout TEventEngineDependencyTree tree, out TEngineParsingMessageSeq messages, in TDeviceTrace trace);

		boolean ping();
	};

	interface TEventEngineScheduler
	{
		TParseJobStatus parse(in TShot shot);
		TParseJobStatus parseSeqEntry(in TShot shot, in TSequenceEntryID sequenceEntryID);
		TParseJobStatus parseSeq(in TShot shot, in TSequenceID sequenceID);

		TPlayJobStatus play(in TParseID parseID, in TEngineJobSourceID source);

		TAddSequenceStatus addSequence(in TSequence sequenceData, in TEngineJobSourceID source);
		
		void closeSequence(in TSequenceID seqid);
    	void cancelSequence(in TSequenceID seqid);

    	TEngineJobStatus getStatusPID(in TParseID pid);
    	TEngineJobStatus getStatusSID(in TShotID sid);
		TEngineJobStatus getStatusSeqID(in TSequenceID seqID);

		TEventEngineDependencyParser getDependencyParser();

    	boolean getJob(in TEngineJobID id, out TEventEngineJob job);
    	void addJob(in TEventEngineJob newJob);
		void cancelJob(in TEngineJobID jobID);

		void cancelAll();

		TEngineJobIDSeq getJobIDs(in TEventEngineJobList jobListType);
    	TEventEngineJobSeq getJobs(in TEventEngineJobList jobListType);

		// void getQueuedJobs(out TEngineJobIDSeq jobIDs);
	    // void getRunningJobs(out TEngineJobIDSeq jobIDs);
    	// void getCompletedJobs(out TEngineJobIDSeq jobIDs);

		void getEngineIDs(out TEngineIDSeq engineIDs);
    	TEngineState getEngineState(in TEngineID engineID);
    	void getEngineStates(out TEngineStateTupleSeq engineStates);

		void clearEngine(in TEngineID engineID);
		void stopEngine(in TEngineID engineID);

		boolean getParseResult(in TParseID parseID, out TParseResult parseResult);
		boolean getShotResult(in TShotID shotID, out TShotResult shotResult);

		boolean ping();
	};

	interface TChannelManager
	{
		void getChannels(out TChannelSeq channels);
		boolean getChannel(in short channelNumber, out TChannel channel);

		boolean setChannelName(in short channelNumber, in string name);

		boolean writeChannel(in short channel, in TMixedValue value);
		boolean readChannel(in short channel, in TMixedValue value, out TMixedValue data);
		void stop();

		boolean ping();
	};

	interface TAttributeManager
	{
	    string getValue(in string key);
	    boolean setValue(in string key, in string value);

		void refreshValue(in string key);

		// TMixedValue getMetaDataAll(in string key);
		// TMixedValue getMetaData(in string key, in string metaKey);

    	boolean getAttribute(in string key, out TAttribute attrib);
    	void getAttributes(out TAttributeSeq attributes);

		boolean ping();
	};


	interface TPersistenceManager
	{
		boolean findShot(in TShotID sid);
		
		boolean getParseResult(in TParseID pid, out TParseResult parseResult);
		boolean getShotResult(in TShotID sid, out TShotResult shotResult);
		boolean getSequenceResult(in TSequenceID seqid, out TSequenceResult sequenceResult);

		boolean saveShot(in TShotID sid, in TFullShotResult fullShotResult, in boolean isOwner);
		
		TShotResultRecord transferResults(in TResultsCollector resultsCollector);

		boolean getMeasurements(in TShotID sid, out TDeviceIDMeasurementsTupleSeq measurements);

		TFileServer getFileServer();

		void addSequence(in TSequenceResult sequenceResult);
		boolean updateSequence(in TSequenceEntryID id, in TShotID shotID, in TEngineJobStatus shotStatus, in boolean isOwner);
		boolean saveSequence(in TSequenceResult sequenceResult, in boolean isOwner);
   
		boolean ping();
	};

	interface TProfileManager
	{
		void getProfiles(out TStringSeq names);
		boolean getProfile(in string name, out TProfile profile);
		boolean saveProfile(in TProfile profile);

		boolean setReadOnly(in string name, in boolean readOnlyProfile);

		boolean loadProfile(in string name, in TProfileType type, in boolean loadDependentDevices);
		boolean saveCurrentProfile(in string name, in TProfileType type, in boolean saveDependentDevices);

		boolean ping();
	};


	interface TTaskManager;

	interface TLogManager
	{
		void getLogNames(out TStringSeq names);

		long getLogCount(in TDeviceID deviceID, in TLogFileFilter filter);
		void getLogIDs(in TLogFileFilter filter, out TLogIDSeq ids);
		void getDeviceLogIDs(in TDeviceID deviceID, in TLogFileFilter filter, out TLogIDSeq ids);

		boolean getLog(in TLogID logID, out TLogFile logFile);
		//boolean getLog(in string name, in string date, in long index, out TLogFile logFile);

		boolean getLogs(in TLogFileFilter filter, out TLogFileSeq files);
		boolean getDeviceLogs(in TDeviceID deviceID, in TLogFileFilter filter, out TLogFileSeq files);

		boolean getLogRecord(in string date, out TLogRecord record);

		boolean ping();
	};

	interface TDevice
	{
		//Node interface
		boolean refresh();
		void kill();
		void disable();

		//Device interface
		TDeviceID getID();

		//Device collector interface
		TDeviceCollection getDeviceCollection();

		//Device message passing
		TDeviceMessageDispatcher getMessageDispatcher();

		//Event engine system
		TEventEngineScheduler getEngineScheduler();

		TChannelManager getChannelManager();
		TAttributeManager getAttributeManager();
		TPersistenceManager getPersistenceManager();
		TProfileManager getProfileManager();
		TTaskManager getTaskManager();
		TLogManager getLogManager();
	};


	interface TFileHolder
	{
		TFileID getID();
		string getFilename();

		boolean exists();
		string md5Checksum();

		boolean transferFile(in TFileHolder destination);
		long maxBufferSize();

		// boolean deleteFile();
		
		boolean write(in OctetSeq buffer);
		// boolean writeString(in string buffer);	//appends string

		boolean openFile();
		// boolean openFileType(in TFileTransferType type, in long offset, out long maxBufferSize);
		void closeFile();
	};

	

	// interface TFileTransferTarget
	// {
	// 	//boolean prepareTarget(in TFileTransferType, out long maxBufferSize, in long offset);	//Check if exists, open file, return buffersize

	// 	boolean exists();
	// 	long maxBufferSize();
	// 	string md5Checksum();

	// 	boolean write(in OctetSeq buffer);
	// 	boolean writeString(in string buffer);	//appends string

	// 	boolean openFile(in TFileTransferType type, in long offset, out long maxBufferSize);
	// 	void closeFile();
	// };

	interface TFileServer
	{
		boolean findFile(in TFileID fileID);
		boolean getFileSize(in TFileID fileID, out long fileSize);
		boolean transferFile(in TFileID source, in TFileHolder destination, in TFileTransferType type);
		boolean transferFilePartial(in TFileID source, in TFileHolder destination, in long offset, in long lines);
		boolean deleteFile(in TFileID fileID);
	};

	interface TBinaryDataStreamTarget
	{
		void start();
		void writeNext(in TBinaryData data);
		void stop();
	};

	interface TBinaryDataStream
	{
		void transfer(in TBinaryDataStreamTarget target);
	};

};	//TNetwork
};	//STI

#endif

