#ifndef STI_TNETWORK_DEVICENET_IDL
#define STI_TNETWORK_DEVICENET_IDL

//IDL for the STI::Network::Hub<DeviceID, Device>
//Includes basic types for Network (Hubs, etc), utilities like DeviceCollector,
//and the Device interface.

#include "orbTypes.idl"

module STI
{
module TNetwork
{
	interface TDevice;	
	interface TDeviceHub;

	interface TDevice;

	struct TDeviceNode	//for NodeWalker
	{
		TDeviceID deviceID;
		TDevice node;
		TDeviceIDSeq outConnections;
	};
	typedef sequence<TDeviceNode> TDeviceNodeSeq;

	struct THubNode	//for NodeWalker
	{
		TDeviceHubID hubID;
		TDeviceNodeSeq nodes;
	};

	struct TNodeWalker;
	typedef sequence<TNodeWalker> TNodeWalkerSeq;

	struct TNodeWalker
	{
		THubNode node;
		TNodeWalkerSeq connections;
	};

	interface TDeviceHub
	{
		boolean addHub(in TDeviceHubID hubID, in TDeviceHub hub);
		boolean removeHub(in TDeviceHubID hubID);
	
//		boolean refresh();
		boolean refreshNetwork(in TDeviceHubTrace trace);

		boolean distribute(in TDeviceID devID, in TDevice node, in TDeviceHubTrace trace, in TDeviceHubID first);
		boolean distributeNodes(in TDeviceHubID targetHub);
		boolean redistributeNodes(in TDeviceHubTrace trace);
		boolean removeNode(in TDeviceID devID, in TDeviceHubTrace trace);

		readonly attribute TDeviceHubID deviceHubID;		//getID()

		void walk(inout TNodeWalker root, in TDeviceHubTrace trace);
	};

	interface TDeviceCollection
	{
		boolean add(in TDeviceID deviceID, in TDevice device);
		boolean remove(in TDeviceID deviceID);

		boolean contains(in TDeviceID deviceID);
		unsigned long size();

		boolean get(in TDeviceID deviceID, out TDevice device);
		void getIDs(out TDeviceIDSeq deviceIDseq);

		void cleanup();
		void clear();
	};

	interface TRefreshIndicator
	{
		void refresh();
	};

	interface TDeviceEventHandler
	{
		void addEvent(in TAnyEvent evt);
		//boolean hasListeners(in TDeviceEvent evt);
		void clearEvents();

		readonly attribute TDeviceEventTypeSeq listenersTypes;

		void setRefreshIndicator(in TRefreshIndicator refresher);
	};

	interface TDeviceEventDispatcher
	{
		void addEventHandler(in TDeviceID targetID, in TDeviceEventHandler handler);
		void removeEventHandler(in TDeviceID targetID);

		//void addEvent(in TDeviceEvent evt);
	};

	interface TParsedShot
	{
		void getEvents(out TRawEventSeq events);
	};

	interface TEventEngine;

	// interface TEventEngineJob
	// {
	// 	TEngineJobID getJobID();
	// 	TDeviceID getJobOwner();
	// 	TEngineJobStatus getStatus();

	// 	void markRunning(in TEngineID id);
	// 	void markComplete();
	// 	void markCancelled();

	// 	TEngineID getEngineID();
	// 	boolean getEngine(out TEventEngine eventEngine);
	// 	void setEventEngine(in TEventEngine eventEngine);

	// 	boolean getParsedShot(out TParsedShot shot);
	// 	boolean getDependencies(out TEventEngineDependencyTree tree);

	// 	TDeviceIDSeq getMissingTargetIDs();
	// };

	struct TEventEngineJob
	{
		TEngineJobID jobID;
		TDeviceID jobOwner;
		TEngineJobStatus status;

		TEngineID engineID;
		//TEventEngine eventEngine;

		TParsedShot shot;
		TEventEngineDependencyTree dependencies;
		TDeviceIDSeq missingTargetIDs;
	};
	
	interface TTriggerCallback
	{
		void ready(in TDeviceID id);
		void triggerFired(in TDeviceID id);
	};

	interface TEventEngine
	{
		void play(in TEventEngineJob job);
		void playCB(in TEngineJobID jobID, in TTriggerCallback triggerCB, in boolean debug);

		void trigger();
		void triggerTarget(in TDeviceID target);

		void stop();
		void pause();
		void unpause(in boolean retrigger);

    	TDeviceID getDeviceID();
		TEngineState getState();
	};

	interface TEventEngineScheduler
	{
		void getDependants(in TDeviceIDSeq evtTargets, inout TEventEngineDependencyTree tree, 
                                inout TDeviceIDSeq missingTargets, in TDeviceTrace trace);
    
    	void addDeviceEventTargets(inout TEventEngineDependencyTree tree, in TDeviceTrace trace);
    
    	void addJob(in TEventEngineJob newJob);
		void cancelJob(in TEngineJobID jobID);
	};

	interface TDevice
	{
		//Node interface
		boolean refresh();

		//Collector interface
		TDeviceCollection getDeviceCollection();

		//Device interface
		TDeviceID getID();
		void write(in unsigned long input);		//temp

		//Device event passing
		TDeviceEventDispatcher getEventDispatcher();

		//Event engine system
		TEventEngineScheduler getEngineScheduler();
	};

};	//TNetwork
};	//STI

#endif

