#ifndef STI_TNETWORK_LOGSNET_IDL
#define STI_TNETWORK_LOGSNET_IDL

//IDL for STI logging

#include "orbTypes.idl"

module STI
{
module TNetwork
{

    struct TLogFileFilter
    {
        string logName;
        string startDate;
        string endDate;
        long startIndex;
        long endIndex;
    };

    enum TLogRecordStatus { LogRecordUnqueried, LogRecordLogsPresent, LogRecordNoLogs, LogRecordError };

    struct TLogID
    {
        TDeviceID deviceID;
        string date;
        string logName;
        unsigned long index;
    };
    typedef sequence<TLogID> TLogIDSeq;

    struct TLogFileRecord
    {
        TLogID id;
        TFileID fileID;

        unsigned long long bytes;
        unsigned long long lineCount;

        TTimeStamp firstEntryTime;
        TTimeStamp lastEntryTime;
    };
    typedef sequence<TLogFileRecord> TLogFileRecordSeq;

    struct TLogNameRecord
    {
        string logName;
        TLogFileRecordSeq files;

        unsigned long long totalBytes;
        unsigned long long totalLines;

        unsigned long nextIndex;
        TTimeStamp lastUpdate;
    };
    typedef sequence<TLogNameRecord> TLogNameRecordSeq;

    struct TDeviceLogRecord
    {
        string deviceID;
        TLogRecordStatus status;
        TStringSeq logNames;
        TLogNameRecordSeq logs;
    };
    typedef sequence<TDeviceLogRecord> TDeviceLogRecordSeq;

    struct TLogRecord
    {
        TTimeStamp timeStamp;
        TDeviceLogRecordSeq deviceLogRecords;
    };

    enum TLogFileType { LogFileFileID, LogFileFileHolder, LogFileString };

    interface TFileHolder;
    struct TLogFile
    {
        TLogID logID;
        TLogFileType type;
        TFileID fileID;
        TFileHolder fileHolder;
        string logString;
    };
    typedef sequence<TLogFile> TLogFileSeq;


};	//TNetwork
};	//STI

#endif
