#ifndef STI_TNETWORK_ORBTYPES_IDL
#define STI_TNETWORK_ORBTYPES_IDL

module STI
{
module TNetwork
{

	struct TDeviceHubID
	{
		string name;
		string address;
		unsigned short moduleNum;
	};
	typedef sequence<TDeviceHubID> TDeviceHubIDSeq;

	struct TDeviceHubTrace
	{
		TDeviceHubIDSeq ids;
	};

	struct TDeviceID 
	{
		string         deviceName;
		string         address;
		unsigned short moduleNum;
		string         targetServer;
	};
	typedef sequence<TDeviceID> TDeviceIDSeq;

	enum TDeviceEventType { Refresh, CollectionUpdate, ChannelUpdate, ChannelsRefresh, AttributeUpdate, AttributesRefresh, MonitorUpdate, Unknown };
	typedef sequence<TDeviceEventType> TDeviceEventTypeSeq;

	struct TAnyEvent
	{
		TDeviceEventType type;
		any evt;
	};

	struct TDeviceEvent
	{
		TDeviceEventType type;
		TDeviceID sourceID;
	};

	struct TRefreshDeviceEvent
	{
		TDeviceEvent base;	//base class data
	};

};	//TNetwork
};	//STI

#endif

