#ifndef STI_TNETWORK_ORBTYPES_IDL
#define STI_TNETWORK_ORBTYPES_IDL

module STI
{
module TNetwork
{

	struct TDeviceHubID
	{
		string name;
		string address;
		unsigned short moduleNum;
	};
	typedef sequence<TDeviceHubID> TDeviceHubIDSeq;

	struct TDeviceHubTrace
	{
		TDeviceHubIDSeq ids;
	};

	struct TDeviceID 
	{
		string         deviceName;
		string         address;
		unsigned short moduleNum;
		string         targetServer;
	};
	typedef sequence<TDeviceID> TDeviceIDSeq;

	struct TDeviceIDVertex
	{
		TDeviceID id;
		sequence<unsigned long> outConnections;
	};
	typedef sequence<TDeviceIDVertex> TDeviceIDVertexSeq;


	struct TTimeStamp
	{
		long year;
		long month;
		long day;
		long hour;
		long min;
		long sec;
		long millis;
		long micros;
		long nanos;
	};


	struct TEventEngineDependencyTree
	{
		TDeviceIDVertexSeq vertices;
	};

	struct TDeviceTrace
	{
		TDeviceIDSeq ids;
	};

	enum TEngineJobStatus { JobNew, JobRunning, JobCompleted, JobCanceled, JobNotFound, JobArchived, JobDeferred };
	enum TRawEventType { RawEventPlay, RawEventMeasurement, RawEventWaveform, RawEventPause, RawEventJump };
	typedef sequence<unsigned long> TGraphPathLabel;

	typedef sequence<octet> OctetSeq;

	enum TFileTransferType { FileTransferBinary, FileTransferString };



	struct TFileID
	{
		string filename;
		string path;
		string origin;	//where file was created
		string persistenceLocation;
		TTimeStamp creationTime;
	};
	typedef sequence<TFileID> TFileIDSeq;

	// struct TFileHolder
	// {
	// 	TFileID fileID;
	// 	TFileServer fileServer;
	// };
	

	interface TFileHolder;
	typedef sequence<TFileHolder> TFileHolderSeq;

	enum TBinaryType { BinaryChar, BinaryUChar, BinaryUShort, BinaryShort, BinaryULong, BinaryLong, BinaryFloat, BinaryDouble, BinaryStream };

	interface TBinaryDataStream;

	union TMixedBinaryData switch(TBinaryType)
	{
		case BinaryUChar: 	sequence<char> 				data_uchar;
		case BinaryChar: 	sequence<char> 				data_char;
		case BinaryUShort: 	sequence<unsigned short> 	data_ushort;
		case BinaryShort: 	sequence<short> 			data_short; 
		case BinaryULong: 	sequence<unsigned long> 	data_ulong;
		case BinaryLong: 	sequence<long> 				data_long;
		case BinaryFloat: 	sequence<float> 			data_float;
		case BinaryDouble: 	sequence<double> 			data_double;
		case BinaryStream:	TBinaryDataStream			data_stream;
	};

	struct TBinaryData
	{
		short wordsize;
		TMixedBinaryData data;
	};


	struct TImage;
	typedef sequence<TImage> TImageSeq;

	enum TImageDataType { ImageDataBinary, ImageDataFile };

	union TImageData switch(TImageDataType) 
	{
		case ImageDataBinary: 	TBinaryData 	binary;
		case ImageDataFile: 	TFileID 		file;
	};

	struct TStringPair
	{
		string key;
		string value;
	};
	typedef sequence<TStringPair> TStringPairSeq;


	struct TImage
	{
	    TImageData imageData;
		TStringPairSeq metaData;

		string filename;
		string extension;

		TFileID fileID;

		long height;
		long width;

		//boolean isChild;
		//TImageSeq children;
	};


	union TMixedValue;
	typedef sequence<TMixedValue> TMixedValueSeq;
	enum TMixedValueType { MixedValueEmpty, MixedValueBoolean, MixedValueInt, MixedValueDouble, MixedValueString, MixedValueVector, MixedValueVectorInt, MixedValueBinary, MixedValueFile, MixedValueImage, MixedValueNumber, MixedValueAny};
	
	union TMixedValue switch(TMixedValueType) 
	{
		case MixedValueEmpty: 		boolean 		empty;
		case MixedValueBoolean: 	boolean 		value_b;
		case MixedValueInt:			long    		value_i;
		case MixedValueDouble: 		double  		value_d;
		case MixedValueString:		string  		value_s;
		case MixedValueVector: 		TMixedValueSeq 	values;
		case MixedValueVectorInt: 	sequence<long> 	valuesInt;
		case MixedValueBinary: 		TBinaryData 	valueBin;
		case MixedValueFile: 		TFileID			value_file;
		case MixedValueImage:		TImage			value_image;
	};

	typedef sequence<string> TStringSeq;

	struct TAttribute
	{
		string key;
		string value;
		string group;
		TStringSeq allowedValues;
		TMixedValue metaData;
	};
	typedef sequence<TAttribute> TAttributeSeq;

	enum TMonitorStatus { MonitorActive, MonitorInactive, MonitorMissing };

	struct TMonitor
	{
		string id;
		string group;
		TMonitorStatus status;
		TMixedValue value;
		TMixedValue metaData;
	};
	typedef sequence<TMonitor> TMonitorSeq;

	struct TStackFrame
	{
		unsigned long file;
		unsigned long line;
		unsigned long func;
	};
	typedef sequence<TStackFrame> TStackFrameSeq;

	struct TRawEventTargetDevice 
	{
		boolean isAbstract;
		string name;
		TDeviceID targetDeviceID;
	};
	
	struct TRawEventTargetChannel 
	{
		boolean isAbstract;
		string _name;
		unsigned short channel;
	};

	struct TRawEventTarget 
	{
		TRawEventTargetDevice device;
    	TRawEventTargetChannel channel;
	};


	struct TParsedVar
	{
		string name;
		string groupName;
		TMixedValue value;
		TStackFrameSeq trace;
	};
	typedef sequence<TParsedVar> TParsedVarSeq;


	struct TRawEvent
	{
		double time;
		TRawEventTarget target;
		// TMixedValue value;
		TParsedVar parsedValue;
		string description;
		string groupName;
		TStackFrameSeq stackTrace;

		boolean isMeasurement;
		TRawEventType rawEventType;

		TGraphPathLabel eventGraphPath;
	};
	typedef sequence<TRawEvent> TRawEventSeq;


	struct TMeasurement
	{
		TMixedValue measurementResult;
	
		double time;
		unsigned short channel;
		TGraphPathLabel measurementGraphPath;
		string fullGroupName;
		TDeviceID device;
	};
	typedef sequence<TMeasurement> TMeasurementSeq;

	struct TDeviceIDMeasurementsTuple
	{
		TDeviceID id;
		TMeasurementSeq measurements;
	};
	typedef sequence<TDeviceIDMeasurementsTuple> TDeviceIDMeasurementsTupleSeq;

	struct TEngineID
	{
		long engineNumber;
	};
	typedef sequence<TEngineID> TEngineIDSeq;

	enum TEngineState { EngineIdle, EngineParsing, EngineParsed, EnginePreparingPlay, EnginePlayReady, EngineWaitingForTrigger, EnginePlaying, EnginePaused, EngineUnknown, EngineMissing, EngineError };

	enum TEventEngineJobType { EngineJobParse, EngineJobPlay, EngineJobSequence };
	
	struct TEngineJobSourceID
	{
		string user;
		string machine;
	};


	enum TShotType { ShotTypeSingle, ShotTypeSequence, ShotTypeSingleUndocumented, ShotTypeSequenceEntry };

	struct TSequenceIndex
	{
		long index;
		long repeat;
	};
	struct TSequenceID
	{
		TTimeStamp timestamp;
		TEngineJobSourceID jobSourceID;
	};
	struct TSequenceEntryID
	{
		TSequenceID seqID;
		TSequenceIndex seqIndex;
	};


	struct TShotConfig
	{
		TShotType shotType;
		
		TEngineJobSourceID jobSourceID;

		long targetEnginePool;

		string file;
		string comment;
	};


	struct TParseID
	{
		TTimeStamp parseTimestamp;
		// TShotConfig shotConfig;
		TShotType shotType;
		TEngineJobSourceID jobSourceID;

		TSequenceEntryID sequenceEntryID;
	};

	struct TParseJobStatus
	{
		TEngineJobStatus status;
		TParseID pid;
	};

	struct TShotID
	{
		TParseID parseID;
		TEngineJobSourceID jobSourceID;

		TTimeStamp submissionTime;
	};

	struct TPlayJobStatus
	{
		TEngineJobStatus status;
		TShotID sid;
	};

	struct TAddSequenceStatus
	{
		TEngineJobStatus status;
		TSequenceID seqid;
	};


	struct TEngineJobID
	{
    	TEventEngineJobType type;
    	TParseID pid;
    	TShotID sid;
		TSequenceID seqid;
	};
	typedef sequence<TEngineJobID> TEngineJobIDSeq;


	struct TShot;

	interface TShotCallback;

	interface TFileServer;

	struct TStackTraceData
	{
		TFileIDSeq timingFiles;
		TStringSeq functionNames;
		TFileServer fileServer;
	};

	struct TStackTraceResult
	{
		TParseID parseID;
		TStackTraceData stackTraceData;
	};

	struct TParsedTag
	{
		string name;
		string groupName;
		TStackFrameSeq trace;
	};
	typedef sequence<TParsedTag> TParsedTagSeq;


	struct RefPointPair
	{
		string name;
		double time;
	};
	typedef sequence<RefPointPair> RefPointPairSeq;

	struct TRawEventGroup;
	typedef sequence<TRawEventGroup> TRawEventGroupSeq;

	struct TRawEventGroup
	{
		string name;
		string parentName;
	    double timeOffset;
		RefPointPairSeq referencePoints;

		TRawEventSeq events;
		TStackTraceData stackTraceData;

    // std::map<std::string, RawEventTarget> targets;   //replace abstract targets in event list
    // std::map<std::string, RawEventTargetDevice> targetDevices;   //replace abstract devices in event list

		TParsedVarSeq overwrittenVars;

		TParsedVarSeq parsedVars;
		TParsedTagSeq parsedTags; 

		TRawEventGroupSeq subgroups;

		TMixedValue metaData;
	};


	struct TShot
	{
		TShotConfig shotConfig;
		TShotCallback shotCallback;
	};

	enum TEventEngineJobList { EngineJobListQueued, EngineJobListRunning, EngineJobListCompleted, EngineJobListArchived };


	enum TSequenceType { SequenceTypeOpen, SequenceTypeClosed };

	struct TSequenceEntry
	{
		TSequenceIndex index;
		TParsedVarSeq overwritten;
	};

	struct TSequenceEntryTuple
	{
		TSequenceIndex index;
		TSequenceEntry entry;
	};
	typedef sequence<TSequenceEntryTuple> TSequenceEntryTupleSeq;

	struct TSequence
	{
		TSequenceEntryTupleSeq sequenceTable;
		long repeats;
		TSequenceType type;
	};

	struct TEngineJobStatusTuple
	{
		TSequenceIndex index;
		TEngineJobStatus status;
	};
	typedef sequence<TEngineJobStatusTuple> TEngineJobStatusTupleSeq;

	struct TShotIDTuple
	{
		TSequenceIndex index;
		TShotID sid;
	};
	typedef sequence<TShotIDTuple> TShotIDTupleSeq;

	struct TSequenceResult
	{
		TSequenceID seqid;
		TSequence sequenceData;

		TEngineJobStatusTupleSeq status;
		TShotIDTupleSeq shots;
	};



	interface TPersistenceManager;
	

	//DeviceMessage *************************//

	enum TDeviceMessageType { MessageRefresh, MessageCollectionUpdate, MessageChannelUpdate, MessageChannelsRefresh, 
							MessageAttributeUpdate, MessageAttributesRefresh, MessageMonitorUpdate, MessageMonitorStatusUpdate, MessageEngineScheduler,
							MessageEngineStatus, MessageEngineParser, MessageEngineJobUpdate, MessageUnknown };
	typedef sequence<TDeviceMessageType> TDeviceMessageTypeSeq;

	struct TAnyMessage
	{
		TDeviceMessageType type;
		any mess;
	};

	struct TDeviceMessage
	{
		TDeviceMessageType type;
		TDeviceTrace sourceTrace;
	};

	struct TRefreshDeviceMessage
	{
		TDeviceMessage base;	//base class data
	};

	enum TCollectionMessageType { CollectionMessageAdd, CollectionMessageRemove, CollectionMessageRefresh };

	struct TCollectionUpdateMessage
	{
		TDeviceMessage base;	//base class data
		TCollectionMessageType collectionUpdateType;
	};

	enum TParsingMessageType { ParsingError, ParsingWarning, ParsingInformation };

	struct TEngineParsingMessage
	{
		TParsingMessageType type;

		TDeviceID sourceID;
		short id_code;
		string name;
		string message;
		TRawEventSeq events;
	};


	typedef sequence<TEngineParsingMessage> TEngineParsingMessageSeq;

	enum TPlayingMessageType { PlayingError, PlayingWarning, PlayingInformation };
	
	struct TEnginePlayingMessage
	{
		TPlayingMessageType type;

		TDeviceID sourceID;
		short id_code;
		string name;
		string message;
	};


	typedef sequence<TEnginePlayingMessage> TEnginePlayingMessageSeq;

	struct TEventEngineJob
	{
		TEngineJobID jobID;
		TDeviceID jobOwner;
		TEngineJobStatus status;

		TEngineID engineID;
		//TEventEngine eventEngine;

		TShot shot;
		TEventEngineDependencyTree dependencies;
		TDeviceIDSeq missingTargetIDs;

		TEngineParsingMessageSeq messages;
		TEnginePlayingMessageSeq playingMessages;
	};
	typedef sequence<TEventEngineJob> TEventEngineJobSeq;


	enum TSchedulerMessageType { SchedulerParseComplete, SchedulerYieldParse, SchedulerPartialParse, SchedulerPlayReady, SchedulerPlayComplete, SchedulerYieldPlay };
	
	interface TEventEngine;

	struct TEngineSchedulerMessage
	{
		TDeviceMessage base;	//base class data

		TSchedulerMessageType type;
		TEngineJobID jobID;

		//TDeviceID originalSource;	//device that generated the original message
		TEventEngine engine;

		TRawEventGroup handledEvents;		//:device generated events that are being sent upstream for documentation, but they have already been parsed
		TRawEventGroup unhandledEvents;	//:device generated events that have not been parsed and are being sent upstream so their target can be found. 

		TRawEventGroup upstreamPartnerEvents;

		TEngineParsingMessageSeq messages;
		TEnginePlayingMessageSeq playMessages;

		TEngineState engineState;
	};

	// enum TEngineJobUpdateTarget {  JobUpdateTargetQueued, JobUpdateTargetRunning, JobUpdateTargetCompleted };


	struct TEngineParsingMessageCount
	{
		short errorCount;
		short warningCount;
		short infoCount;
	};

	struct TEnginePlayingMessageCount
	{
		short errorCount;
		short warningCount;
		short infoCount;
	};

	struct TEngineJobUpdateDeviceMessage
	{
		TDeviceMessage base;	//base class data

		TEventEngineJobList targetList;
		// TEventEngineJob engineJob;
		
		TEngineJobID jobID;
		TDeviceID jobOwner;
		TEngineJobStatus jobStatus;

		TEngineID engineID;
		TShotConfig shotConfig;
		TParsedVarSeq overwrittenVars;

		TEngineParsingMessageCount parsingMessageCount;
		TEnginePlayingMessageCount playingMessageCount;
	};

	struct TAttributeTuple
	{
		string key;
		string value;
	};
	typedef sequence<TAttributeTuple> TAttributeTupleSeq;

	struct TAttributeUpdateMessage
	{
		TDeviceMessage base;	//base class data
		TAttributeTupleSeq attributes;		//{key, value} pairs
	};

	struct TMonitorUpdateTuple
	{
		string id;
		TMixedValue value;
	};
	typedef sequence<TMonitorUpdateTuple> TMonitorUpdateTupleSeq;

	struct TMonitorUpdateMessage
	{
		TDeviceMessage base;	//base class data
		TMonitorUpdateTupleSeq updates;		//{key, value} pairs
	};


	struct TMonitorStatusUpdateTuple
	{
		string id;
		TMonitorStatus status;
	};
	typedef sequence<TMonitorStatusUpdateTuple> TMonitorStatusUpdateTupleSeq;

	struct TMonitorStatusUpdateMessage
	{
		TDeviceMessage base;	//base class data
		TMonitorStatusUpdateTupleSeq updates;		//{key, value} pairs
	};
	
	enum TChannelUpdateMessageType { ChannelUpdataValue, ChannelUpdateName };

	struct TChannelUpdateTuple
	{
		short channelNumber;
		TMixedValue value;
	};
	typedef sequence<TChannelUpdateTuple> TChannelUpdateTupleSeq;

	struct TChannelUpdateMessage
	{
		TDeviceMessage base;	//base class data

		TChannelUpdateMessageType channelUpdateType;

		TChannelUpdateTupleSeq channelValues;	//{channel, value} pairs

		//only used for ChannelName messages
		short channelNumber;
		string channelName;
	};


	struct TEngineStateTuple
	{
		TEngineID engineID;
		TEngineState state;
	};
	typedef sequence<TEngineStateTuple> TEngineStateTupleSeq;

	struct TEngineStateMessage
	{
		TDeviceMessage base;	//base class data
		TEngineStateTupleSeq engineStates;	//{engineID, state} pairs
	};


	struct TEngineParserDeviceMessage
	{
		TDeviceMessage base;	//base class data
		TParseID pid;
		TEngineParsingMessageSeq messages;
	};

	//**********************************//


	enum TChannelType { TChannelOutput, TChannelInput };

	struct TChannel
	{
		short channelNumber;
		string channelName;

		TChannelType type;
		TMixedValueType inputType;
		TMixedValueType outputType;
		
		TMixedValue lastValue;

		TMixedValue metaData;
	};
	typedef sequence<TChannel> TChannelSeq;


	enum TRecordStatus { TRecordUnqueried, TRecordComplete, TRecordMissingDevice, TRecordMissingResults, TRecordError };

	struct TShotResultRecord;
	typedef sequence<TShotResultRecord> TShotResultRecordSeq;

	struct TShotResultRecord
	{
		TDeviceID deviceID;
		TRecordStatus recordStatus;
		TShotResultRecordSeq dependencies;
	};

	struct TDeviceIDAttributesTuple
	{
		TDeviceID id;
		TAttributeTupleSeq attributes;
	};

	typedef sequence<TDeviceIDAttributesTuple> TDeviceIDAttributesTupleSeq;

	struct TShotID;


	struct TParseResult
	{
		TParseID parseID;
		TShotConfig shotConfig;

		TRawEventGroup baseEventGroup;
		TEventEngineDependencyTree parsedDevices;
		TEngineParsingMessageSeq messages;
		TStackTraceResult stackTraceResult;
	};


	struct TShotResult
	{
		TShotID sid;
		TTimeStamp playTime;

		// TMeasurementSeq measurements;
		TDeviceIDMeasurementsTupleSeq measurements;
		TDeviceIDAttributesTupleSeq attributes;
		TEnginePlayingMessageSeq messages;

		TShotResultRecord shotResultRecord;
	};

	struct TFullShotResult
	{
		TParseResult parseResult;
		TShotResult shotResult;
	};

	enum TProfileType { ProfileAttribute, ProfileChannel, ProfileAll };

	struct TProfile
	{
		string name;
		TProfileType type;
		boolean readOnlyProfile;
		TAttributeTupleSeq attributeData;
		TChannelUpdateTupleSeq channelData;
	};

};	//TNetwork
};	//STI


#endif

