#ifndef STI_TNETWORK_ORBTYPES_IDL
#define STI_TNETWORK_ORBTYPES_IDL

module STI
{
module TNetwork
{

	struct TDeviceHubID
	{
		string name;
		string address;
		unsigned short moduleNum;
	};
	typedef sequence<TDeviceHubID> TDeviceHubIDSeq;

	struct TDeviceHubTrace
	{
		TDeviceHubIDSeq ids;
	};

	struct TDeviceID 
	{
		string         deviceName;
		string         address;
		unsigned short moduleNum;
		string         targetServer;
	};
	typedef sequence<TDeviceID> TDeviceIDSeq;

	struct TDeviceIDVertex
	{
		TDeviceID id;
		sequence<unsigned long> outConnections;
	};
	typedef sequence<TDeviceIDVertex> TDeviceIDVertexSeq;

	struct TEventEngineDependencyTree
	{
		TDeviceIDVertexSeq vertices;
	};

	struct TDeviceTrace
	{
		TDeviceIDSeq ids;
	};

	enum TEngineJobStatus { New, Running, Completed, Cancelled };
	enum TRawEventType { RawEventPlay, RawEventMeasurement, RawEventWaveform, RawEventPause, RawEventJump };
	typedef sequence<unsigned long> TGraphPathLabel;

//	union TMixedValue;
	struct TMixedValue;
	typedef sequence<TMixedValue> TMixedValueSeq;
	enum TMixedValueType { MixedValueBoolean, MixedValueInt, MixedValueDouble, MixedValueString, MixedValueVector, MixedValueEmpty, MixedValueFile, MixedValueImage, MixedValueAny};
	
	// union TMixedValue switch(TMixedValueType) {
	// 	case MixedValueBoolean: boolean value_b;
	// 	case MixedValueInt:		long    value_i;
	// 	case MixedValueDouble: 	double  value_d;
	// 	case MixedValueString:	string  value_s;
	// 	case MixedValueVector: 	TMixedValueSeq value_v;
	// 	case MixedValueEmpty: 	boolean empty;
	// 	case MixedValueFile: 	TFile	value_file;
	// 	case MixedValueImage:	TImage	value_image;
	// };

	struct TMixedValue
	{
		TMixedValueSeq values;

		TMixedValueType type;

		boolean value_b;
		long    value_i;
		double  value_d;
		string  value_s;
	};

	struct TRawEvent
	{
		double time;
		unsigned short channel;
		TMixedValue value;
		string description;
		//TEventStackTrace trace;
		boolean isMeasurement;
		TRawEventType rawEventType;
		TDeviceID targetDeviceID;

		TGraphPathLabel eventGraphPath;
	};
	typedef sequence<TRawEvent> TRawEventSeq;

	struct TEngineID
	{
		short engineNumber;
	};

	enum TEngineState { EngineIdle, EngineParsing, EngineParsed, EnginePreparingPlay, EnginePlayReady, EngineWaitingForTrigger, EnginePlaying, EnginePaused, EngineUnknown, EngineMissing, EngineError };

	enum TEventEngineJobType { EngineJobParse, EngineJobPlay };
	
	struct TTimeStamp
	{
		double timestamp;
	};

	struct TEngineJobSourceID
	{
		string user;
		string machine;
	};

	struct TParseID
	{
		TTimeStamp parseTimestamp;
		
		TEngineJobSourceID jobSourceID;

		string file;
		string comment;
	};

	struct TShotID
	{
		TParseID parseID;
		
		TTimeStamp submissionTime;
		TTimeStamp playTime;

		TEngineJobSourceID jobSourceID;
	};

	struct TEngineJobID
	{
    	TEventEngineJobType type;
    	TParseID pid;
    	TShotID sid;
	};


	enum TDeviceEventType { MessageRefresh, MessageCollectionUpdate, MessageChannelUpdate, MessageChannelsRefresh, 
							MessageAttributeUpdate, MessageAttributesRefresh, MessageMonitorUpdate, MessageEngineScheduler,
							MessageEngineStatus, MessageEngineParser, MessageUnknown };
	typedef sequence<TDeviceEventType> TDeviceEventTypeSeq;

	struct TAnyEvent
	{
		TDeviceEventType type;
		any evt;
	};

	struct TDeviceEvent
	{
		TDeviceEventType type;
		TDeviceID sourceID;
	};

	struct TRefreshDeviceEvent
	{
		TDeviceEvent base;	//base class data
	};


	enum TSchedulerMessageType { SchedulerParseComplete, SchedulerYieldParse, SchedulerPartialParse, SchedulerPlayReady, SchedulerYieldPlay };
	
	interface TEventEngine;

	struct TEngineSchedulerMessage
	{
		TDeviceEvent base;	//base class data

		TSchedulerMessageType type;
		TEngineJobID jobID;

		TDeviceID originalSource;	//device that generated the original message
		TEventEngine engine;

		TRawEventSeq handledEvents;		//:device generated events that are being sent upstream for documentation, but they have already been parsed
		TRawEventSeq unhandledEvents;	//:device generated events that have not been parsed and are being sent upstream so their target can be found. 
	};


	enum TChannelType { TChannelOutput, TChannelInput };


	struct TChannel
	{
		short channelNumber;
		string channelName;

		TChannelType type;
		TMixedValueType inputType;
		TMixedValueType outputType;
		
		TMixedValue lastValue;

		TMixedValue metaData;
	};
	typedef sequence<TChannel> TChannelSeq;

	// struct TEngineSchedulerParseMessage
	// {
	// 	TDeviceEvent base;	//base class data

	// 	TEngineJobID jobID;
	// 	TSchedulerMessageType type;

	// 	TDeviceID originalSource;	//device that generated the original message

	// 	TRawEventSeq handledEvents;		//:device generated events that are being sent upstream for documentation, but they have already been parsed
	// 	TRawEventSeq unhandledEvents;	//:device generated events that have not been parsed and are being sent upstream so their target can be found. 
	// };

	// struct TEngineSchedulerPlayMessage
	// {
	// 	TDeviceEvent base;	//base class data

	// 	TEngineJobID jobID;
	// 	TSchedulerMessageType type;

	// 	TDeviceID originalSource;	//device that generated the original message

	// 	TEventEngine engine;
	// };

};	//TNetwork
};	//STI

#endif

