#ifndef STI_TNETWORK_TASKS_IDL
#define STI_TNETWORK_TASKS_IDL

//IDL for STI asynchronous tasks

#include "orbTypes.idl"

module STI
{
module TNetwork
{
    struct TTask
    {
        string taskID;
        TTaskStatus status;
        TMixedValue metaData;
        boolean hasLastRunTime;
        TTimeStamp lastRunTime;
    };
    typedef sequence<TTask> TTaskSeq;


    interface TTaskManager
    {
        void getTaskIDs(out TStringSeq ids);

        TTaskStatus getTaskStatus(in string taskID);
        boolean getTaskLastRunTime(in string taskID, out TTimeStamp lastRunTime);

        void setStatus(in string taskID, in TTaskStatus newStatus);

        boolean getTask(in string taskID, out TTask task);
        void getTasks(out TTaskSeq tasks);

        void removeTask(in string taskID);
        void clear();

        void activateTask(in string taskID);
        void deactivateTask(in string taskID);

        void runTask(in string taskID);

        double secondsToNextRun(in string taskID);

        boolean ping();
    };

};	//TNetwork
};	//STI

#endif
