/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_sti_WRAP_H_
#define SWIG_sti_WRAP_H_

class SwigDirector_JDevice : public STI::Device::JDevice, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_JDevice(JNIEnv *jenv, std::shared_ptr< STI::Device::Device > const &device);
    SwigDirector_JDevice(JNIEnv *jenv, std::string const &name, std::string const &address, unsigned short module, std::string const &targetServer);
    virtual ~SwigDirector_JDevice();
    virtual void write(unsigned int input);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_JLocalDevice : public STI::Device::JLocalDevice, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_JLocalDevice(JNIEnv *jenv, std::string const &name, std::string const &address, unsigned short module, std::string const &targetServer);
    virtual ~SwigDirector_JLocalDevice();
    virtual void write(unsigned int input);
    virtual void parseEvents(int temp);
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};

class SwigDirector_DeviceEvent : public STI::Device::DeviceEvent, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_DeviceEvent(JNIEnv *jenv);
    SwigDirector_DeviceEvent(JNIEnv *jenv, STI::Device::DeviceID const &source, STI::Device::DeviceEventType type);
    virtual ~SwigDirector_DeviceEvent();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_RefreshDeviceEvent : public STI::Device::RefreshDeviceEvent, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_RefreshDeviceEvent(JNIEnv *jenv, STI::Device::DeviceID const &source);
    virtual ~SwigDirector_RefreshDeviceEvent();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_ChannelUpdateDeviceEvent : public STI::Device::ChannelUpdateDeviceEvent, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ChannelUpdateDeviceEvent(JNIEnv *jenv, STI::Device::DeviceID const &source);
    virtual ~SwigDirector_ChannelUpdateDeviceEvent();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_EngineSchedulerMessage : public STI::Device::EngineSchedulerMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineSchedulerMessage(JNIEnv *jenv, STI::Device::DeviceID const &source, STI::Device::DeviceID originalSource, STI::Device::EngineSchedulerMessage::SchedulerMessageType const &type);
    virtual ~SwigDirector_EngineSchedulerMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_EngineParserMessage : public STI::Device::EngineParserMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineParserMessage(JNIEnv *jenv);
    virtual ~SwigDirector_EngineParserMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_EventEngineMessage : public STI::Device::EventEngineMessage, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EventEngineMessage(JNIEnv *jenv);
    virtual ~SwigDirector_EventEngineMessage();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_RefreshDeviceEventListener : public STI::Device::DeviceEventListener< STI::Device::RefreshDeviceEvent >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_RefreshDeviceEventListener(JNIEnv *jenv);
    virtual ~SwigDirector_RefreshDeviceEventListener();
    virtual void handleEvent(std::shared_ptr< STI::Device::RefreshDeviceEvent > const &evt);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_ChannelUpdateDeviceEventListener : public STI::Device::DeviceEventListener< STI::Device::ChannelUpdateDeviceEvent >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ChannelUpdateDeviceEventListener(JNIEnv *jenv);
    virtual ~SwigDirector_ChannelUpdateDeviceEventListener();
    virtual void handleEvent(std::shared_ptr< STI::Device::ChannelUpdateDeviceEvent > const &evt);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_EngineSchedulerMessageListener : public STI::Device::DeviceEventListener< STI::Device::EngineSchedulerMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineSchedulerMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_EngineSchedulerMessageListener();
    virtual void handleEvent(std::shared_ptr< STI::Device::EngineSchedulerMessage > const &evt);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_EngineParserMessageListener : public STI::Device::DeviceEventListener< STI::Device::EngineParserMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EngineParserMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_EngineParserMessageListener();
    virtual void handleEvent(std::shared_ptr< STI::Device::EngineParserMessage > const &evt);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_EventEngineMessageListener : public STI::Device::DeviceEventListener< STI::Device::EventEngineMessage >, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_EventEngineMessageListener(JNIEnv *jenv);
    virtual ~SwigDirector_EventEngineMessageListener();
    virtual void handleEvent(std::shared_ptr< STI::Device::EventEngineMessage > const &evt);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_ParsedShot : public STI::Engine::ParsedShot, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ParsedShot(JNIEnv *jenv);
    virtual ~SwigDirector_ParsedShot();
    virtual void getEvents(std::shared_ptr< std::vector< STI::Engine::RawEvent > > &ets);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};


#endif
