import stipy
import stipy.stidevicepy as stidevicepy

import traceback


class TestDevice(stidevicepy.LocalDevice):
    def __init__(self, config):
        stidevicepy.LocalDevice.__init__(self, config)

        # *** Define channels *** #

        # Output channels (the device's output actuators)
        self.addOutputChannel(0, stipy.MixedValueType.Double, "coil current")       #outputs a Double
        self.addOutputChannel(1, stipy.MixedValueType.Number, "supply voltage")     #outputs a number

        # Input channels (make measurements that are recorded by the device)
        self.addInputChannel(2, stipy.MixedValueType.Number, "thermocouple voltage")    #measures a number

        # self.addEventTarget("TestDevice2", "localhost", 2, 'sr-magis/2/STI Server')   #partner device
        self.partnerID = stipy.DeviceID("TestDevice2", "localhost", 2, 'sr-magis/2/Frame2')
        self.addEventTarget(self.partnerID)   #partner device

        self.addAttribute("Enable Load Error", "On", ["On", "Off"])

        return
    
    def parseEvents(self, eventsIn, synchedEvents):

        # eventsIn type: Dict[float, List[stipy.RawEvent]]
        # synchedEvents type: stidevicepy.SynchronousEventVector

        # * RawEvent: Event class containing a high-level description of the event information: (time, channel, value).
        # * SynchronousEvent: User defined event class responsible for implementing the event on the hardware.

        # The parseEvents function must convert the RawEvents generated by the timing file into a list of SynchronousEvents
        # that are ready to play on the hardware.

        # * eventsIn is of type Dict[float, List[stipy.RawEvent]]
        # The key of each dict entry is the time (float) of the event(s). The value of each entry is a list of RawEvents
        # that are scheduled to occur at this time. In general, multiple events can occur at the same time, as long as they are
        # on distinct channels. It is the job of this function to parse this event information and generate a hardware-level
        # event (SynchronousEvent) capable of implementing the desired changes on the channel(s) specified by the RawEvent(s).
        # 'SynchronousEvent' is called 'synchronous' because all hardware changes on the channels are scheduled to occur at 
        # the same time for each SynchronousEvent. The grouping of RawEvent by their common time in the dictionary helps with this.

        # * synchedEvents is (conceptually) of type List[stidevicepy.SynchronousEvent]. In practice it has (list-like) type SynchronousEventVector.
        # SynchronousEvent itself is an abstract class, and so it first must be implemented by an appropriate derived class that  
        # includes the hardware-specific implementation details. Instances of this custom derived class should then be added 
        # to the synchedEvents list.

        partnerCh = stipy.RawEventTargetChannel(0)

        num = 0

        for time, events in eventsIn.items():
            # Here 'tuple' is of type { time, list[RawEvent] }, where the list is the set of events at this time.
            inputEvent = False
            num += 1
            #check for input event
            for evt in events:
                num += 1
                if evt.isMeasurementEvent():
                    # print("isMeasurementEvent")
                    inputEvent = True
                    break
            
            # x = [1,2]
            # y = x[3]

            # Example of error checking. When an error is encountered during parsing, an exception should be thrown.
            # This exception is handled by STI and converted to a parsing error message. 
            # if inputEvent and tuple.second.size() > 1:

            if inputEvent and len(events) > 1:
                # Error: In this example, when there is an input event, it must be the only event at that time.
                # The EventConflictException constuctor accepts reference to the two offending events, plus a message: 
                raise stipy.EventConflictException(events[0], events[1], "Error: An input event cannot be at the same time as an output event.")
            
            if not inputEvent:
                # Output event
                print("Enable load error: " + str(self.getAttributeManager().getValue("Enable Load Error")))
                testDeviceOutputEvent = TestDeviceOutputEvent(time, num, loadError=(self.getAttributeManager().getValue("Enable Load Error") == "On"))

                for evt in events:
                    if evt.value().getValue() > 10:
                        raise stipy.EventParsingException(evt, "The value " + str(evt.value()) + " exceeds the maximium allowed value for this channel. Max value is 10.")
                    testDeviceOutputEvent.addValue(evt.channel(), evt.value())  # attach values to event for use later

                    if evt.channel() == 0:
                        # Example of sending a partner event when this device has an output event on channel 0 
                        self.partner(self.partnerID).addEvent(time, partnerCh, 3.2*evt.value().getValue(), evt)  #partner device output channel

                synchedEvents.append(testDeviceOutputEvent)

            else:
                testDeviceInputEvent = TestDeviceInputEvent(time)
                testDeviceInputEvent.addMeasurement(events[0])  # REQUIRED: The source RawEvent must be attached to the input event for
															    # data to be properly saved later. Skipping this will result in a parse error.
                
                testDeviceInputEvent.exampleParameter = 2.5;	# Configre other event parameters, as needed...
            
                synchedEvents.append(testDeviceInputEvent)
            
        return


################### TestDeviceOutputEvent ##################

# This subclass is used to specify the custom behavior controlling the hardware for each device output channel.

class TestDeviceOutputEvent(stidevicepy.SynchronousEvent):
    def __init__(self, time, id=None, loadError=False):
        stidevicepy.SynchronousEvent.__init__(self, time)
        self.values = {}
        self.id = id
        self.loadError = loadError
    def addValue(self, channel, value):
        # Collect all values scheduled to play at this time so that can be play (psuedo) synchronously
        self.values[channel] = value

    def loadEvent(self):
        # This function is called at the beginning of each shot, before any events are played.
        # Use this function to setup the hardware to prepare for hard timing playback.
        # For example, if this device requires values to be preloaded into some buffer on the hardware
        # (e.g., an FPGA, or an arbitrary waveform generator), this can be done here.
        if self.loadError:
            print("Raising load error for event ID " + str(self.id))
            self.addError("Test Err 1").appendMessage("A test load error message.")

        # self.addWarning("Test Warn").appendMessage("A test load warning message. ")
        for channel, value in self.values.items():
            print("Loading channel #" + str(channel) + " with value " + str(value) + ".")
        return
    
    def playEvent(self):
        # This function will be called at time specified in the timing file.
        # Use this function to control the hardware to implement the change on the requested channel.

        # Add hardware play code here...
        # self.addWarning("Test Err").appendMessage("A test error message. " + str(self.id))
        # self.addWarning("Test Warn").appendMessage("A test warning message. ")
        # self.addInfoMessage("Test Info").appendMessage("A test info message. ")
        # self.addError("Test Err 1").appendMessage("A test error message.")
        for channel, value in self.values.items():
            print("Playing channel #" + str(channel) + " with value " + str(value) + ".")

        return
    def collectMeasurementData(self):
        # This function is called after playEvent() and is used to retrieve any measurement data.
        # The new data is then attached to this event so it can later be saved at the end of the shot.

        # In this case, there is no data to save for an output event.
        return
    def stopEvent(self):
        # Custom behavior for when "stop" is called. 
        # Use this to interrupt the hardware and put it back to the desired idle state.
        return
    def pauseEvent(self):
        return
    def unpauseEvent(self, retrigger):
        return


################## TestDeviceInputEvent ###############

# This subclass is used to control the hardware for the device's input channel.
# Note that the same event class can be used for both input and output events, if desired. In this 
# example they are separated for clarity.

class TestDeviceInputEvent(stidevicepy.SynchronousEvent):
    def __init__(self, time):
        stidevicepy.SynchronousEvent.__init__(self, time)
        self.exampleParameter = 0

    def collectMeasurementData(self):
        # This function is called after playEvent() and is used to retrieve any measurement data.
        # The new data is then attached to this event so it can later be saved at the end of the shot.
        for m in self.getMeasurements():
            m.setMeasurementResult(3.6 * self.exampleParameter)


